export interface Battery {
  id: number;
  brand: string;
  name: string;
  capacity: number;
  coldCranking: number;
  voltage: number;
  terminals: "standard" | "reverse";
  technology: "AGM" | "EFB" | "WET" | "GEL";
  suitableFor: string[];
  price: number;
  priceOld?: number;
  inStock: boolean;
  weight: number;
}

export const BATTERY_BRANDS = ["Bosch", "Varta", "Optima", "Exide", "Banner", "Moll"] as const;
export const BATTERY_TECHS: Battery["technology"][] = ["AGM", "EFB", "WET", "GEL"];
export const BATTERY_CAPACITIES = [60, 70, 74, 80, 90, 95, 100, 110, 120, 140, 180, 225] as const;

export const batteries: Battery[] = [
  {
    id: 1,
    brand: "Bosch",
    name: "S5 AGM 95Ah 850A",
    capacity: 95,
    coldCranking: 850,
    voltage: 12,
    terminals: "standard",
    technology: "AGM",
    suitableFor: ["Mercedes Sprinter W906", "Mercedes Sprinter W907", "VW Crafter"],
    price: 7890,
    priceOld: 8600,
    inStock: true,
    weight: 25.0,
  },
  {
    id: 2,
    brand: "Varta",
    name: "Blue Dynamic E44 77Ah 780A",
    capacity: 77,
    coldCranking: 780,
    voltage: 12,
    terminals: "standard",
    technology: "WET",
    suitableFor: ["Mercedes Vito W639", "Mercedes Vito W447"],
    price: 4290,
    inStock: true,
    weight: 18.5,
  },
  {
    id: 3,
    brand: "Bosch",
    name: "S4 Silver 74Ah 680A",
    capacity: 74,
    coldCranking: 680,
    voltage: 12,
    terminals: "standard",
    technology: "WET",
    suitableFor: ["Mercedes Sprinter W901", "Mercedes Sprinter W903", "VW LT"],
    price: 3890,
    inStock: true,
    weight: 17.8,
  },
  {
    id: 4,
    brand: "Varta",
    name: "Silver Dynamic AGM 105Ah 950A",
    capacity: 105,
    coldCranking: 950,
    voltage: 12,
    terminals: "reverse",
    technology: "AGM",
    suitableFor: ["Mercedes Sprinter W907 (2018+)"],
    price: 10200,
    priceOld: 11500,
    inStock: true,
    weight: 30.2,
  },
  {
    id: 5,
    brand: "Banner",
    name: "Running Bull EFB 80Ah 720A",
    capacity: 80,
    coldCranking: 720,
    voltage: 12,
    terminals: "standard",
    technology: "EFB",
    suitableFor: ["Mercedes Sprinter W906", "VW Crafter"],
    price: 5600,
    inStock: true,
    weight: 20.4,
  },
  {
    id: 6,
    brand: "Exide",
    name: "Premium EA900 90Ah 900A",
    capacity: 90,
    coldCranking: 900,
    voltage: 12,
    terminals: "standard",
    technology: "WET",
    suitableFor: ["Mercedes Sprinter W906", "VW Crafter 2006–2017"],
    price: 5100,
    inStock: false,
    weight: 22.0,
  },
  {
    id: 7,
    brand: "Optima",
    name: "Red Top 50Ah 815A",
    capacity: 50,
    coldCranking: 815,
    voltage: 12,
    terminals: "standard",
    technology: "GEL",
    suitableFor: ["Спецтехніка", "Нестандартне встановлення"],
    price: 9800,
    inStock: true,
    weight: 15.4,
  },
  {
    id: 8,
    brand: "Moll",
    name: "M3 Plus 110Ah 920A",
    capacity: 110,
    coldCranking: 920,
    voltage: 12,
    terminals: "standard",
    technology: "WET",
    suitableFor: ["Mercedes Sprinter W906 CDI 3.0"],
    price: 6400,
    inStock: true,
    weight: 27.5,
  },
  {
    id: 9,
    brand: "Bosch",
    name: "S5 AGM 70Ah 760A",
    capacity: 70,
    coldCranking: 760,
    voltage: 12,
    terminals: "standard",
    technology: "AGM",
    suitableFor: ["Mercedes Vito W639", "Mercedes Vito W447"],
    price: 6200,
    inStock: true,
    weight: 21.3,
  },
  {
    id: 10,
    brand: "Varta",
    name: "Black Dynamic C15 60Ah 540A",
    capacity: 60,
    coldCranking: 540,
    voltage: 12,
    terminals: "standard",
    technology: "WET",
    suitableFor: ["VW LT 28–35", "Mercedes Sprinter W901 (бензин)"],
    price: 2890,
    inStock: true,
    weight: 15.0,
  },
  {
    id: 11,
    brand: "Banner",
    name: "Power Bull P9533 95Ah 760A",
    capacity: 95,
    coldCranking: 760,
    voltage: 12,
    terminals: "standard",
    technology: "WET",
    suitableFor: ["Mercedes Sprinter W906", "VW Crafter"],
    price: 4800,
    inStock: true,
    weight: 24.1,
  },
  {
    id: 12,
    brand: "Exide",
    name: "Equipment Gel ES900 80Ah",
    capacity: 80,
    coldCranking: 400,
    voltage: 12,
    terminals: "standard",
    technology: "GEL",
    suitableFor: ["Спецтехніка", "Сонячні панелі", "Інвертори"],
    price: 7200,
    inStock: false,
    weight: 24.0,
  },
];
