import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "sp-001",
    slug: "bosch-amortyzator-peredni-sprinter",
    name: "Амортизатор передній Bosch",
    nameUK: "Амортизатор передній",
    brand: "Bosch",
    sku: "0986479R20",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 2480,
    priceOld: 2990,
    currency: "UAH",
    inStock: true,
    stockCount: 8,
    images: ["/products/shock-absorber-1.jpg"],
    description: "Оригінальний амортизатор передній для Mercedes Sprinter W901-905. Газомаслянний, підвищена надійність. Відповідає заводським специфікаціям.",
    specs: [
      { label: "Тип", value: "Газомаслянний" },
      { label: "Вісь", value: "Передня" },
      { label: "Довжина (стиснутий)", value: "365 мм" },
      { label: "Довжина (розтягнутий)", value: "600 мм" },
      { label: "Хід штока", value: "235 мм" },
      { label: "Діаметр штока", value: "22 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI", "2.0 TDI"] },
    ],
    rating: 4.8,
    reviewCount: 47,
    isNew: false,
    isBestseller: true,
    deliveryDays: 1,
    weight: 2.4,
    oem: ["9013261100", "9013260800"],
    tags: ["амортизатор", "підвіска", "sprinter"],
  },
  {
    id: "sp-002",
    slug: "febi-kolodky-transmisni-sprinter",
    name: "Колодки гальмівні передні Febi",
    nameUK: "Колодки гальмівні передні",
    brand: "Febi Bilstein",
    sku: "FEBI16644",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 890,
    priceOld: undefined,
    currency: "UAH",
    inStock: true,
    stockCount: 24,
    images: ["/products/brake-pads-1.jpg"],
    description: "Гальмівні колодки передні для Mercedes Sprinter та Vito. Матеріал: низькометалевий з індикатором зносу. Висока ефективність гальмування.",
    specs: [
      { label: "Тип", value: "Дискові" },
      { label: "Вісь", value: "Передня" },
      { label: "Матеріал", value: "Низькометалевий" },
      { label: "Індикатор зносу", value: "Так" },
      { label: "Висота", value: "60 мм" },
      { label: "Товщина", value: "17 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["2.2 CDI", "2.3", "2.9 TDI"] },
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["2.3", "2.2 CDI"] },
    ],
    rating: 4.7,
    reviewCount: 93,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.8,
    oem: ["0014201020", "A0014201020"],
    tags: ["колодки", "гальма", "передні"],
  },
  {
    id: "sp-003",
    slug: "mahle-filtr-maslyany-sprinter",
    name: "Фільтр масляний Mahle",
    nameUK: "Фільтр масляний",
    brand: "Mahle",
    sku: "OX153D",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter", "mercedes-vito", "mercedes-lt"],
    price: 320,
    currency: "UAH",
    inStock: true,
    stockCount: 52,
    images: ["/products/oil-filter-1.jpg"],
    description: "Масляний фільтр для дизельних двигунів Mercedes. Ефективна фільтрація, якість OEM. Підходить для 2.2 CDI та 2.7 CDI.",
    specs: [
      { label: "Тип", value: "Картриджний" },
      { label: "Висота", value: "97 мм" },
      { label: "Зовнішній діаметр", value: "76 мм" },
      { label: "Різьба", value: "M22×1.5" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2018", engines: ["2.2 CDI", "2.7 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.9,
    reviewCount: 128,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.3,
    oem: ["A6111800009", "6111800009"],
    tags: ["фільтр", "масло", "двигун"],
  },
  {
    id: "sp-004",
    slug: "meyle-kermove-nakonechnyk-sprinter",
    name: "Наконечник кермової тяги Meyle",
    nameUK: "Наконечник кермової тяги",
    brand: "Meyle",
    sku: "3160200006HD",
    category: "suspension",
    subcategory: "arms",
    vehicles: ["mercedes-sprinter"],
    price: 650,
    priceOld: 780,
    currency: "UAH",
    inStock: true,
    stockCount: 16,
    images: ["/products/steering-end-1.jpg"],
    description: "Наконечник рульової тяги HD (Heavy Duty) для Sprinter. Посилена конструкція для комерційного транспорту. Зносостійкий матеріал кульового шарніра.",
    specs: [
      { label: "Сторона", value: "Права / Ліва (Universal)" },
      { label: "Різьба", value: "M14×1.5 (RH)" },
      { label: "Тип", value: "HD (Heavy Duty)" },
      { label: "Матеріал", value: "Сталь + сфероїдальний чавун" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 35,
    deliveryDays: 2,
    weight: 0.5,
    oem: ["9014601848", "9014602548"],
    tags: ["кермо", "наконечник", "тяга"],
  },
  {
    id: "sp-005",
    slug: "valeo-disk-zcheplennya-sprinter",
    name: "Диск зчеплення Valeo",
    nameUK: "Диск зчеплення",
    brand: "Valeo",
    sku: "286302",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 3200,
    priceOld: 3800,
    currency: "UAH",
    inStock: true,
    stockCount: 5,
    images: ["/products/clutch-disc-1.jpg"],
    description: "Диск зчеплення ведений для Mercedes Sprinter з двигуном 2.2 CDI. Комплект KIT3P (диск + кошик + підшипник вижимний).",
    specs: [
      { label: "Тип", value: "KIT3P (3 деталі)" },
      { label: "Діаметр", value: "240 мм" },
      { label: "Кількість зубів", value: "22" },
      { label: "Товщина", value: "8.3 мм (нова)" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI"] },
    ],
    rating: 4.7,
    reviewCount: 22,
    isNew: false,
    deliveryDays: 2,
    weight: 4.2,
    oem: ["A0022508504"],
    tags: ["зчеплення", "диск", "трансмісія"],
  },
  {
    id: "sp-006",
    slug: "behr-radyator-okholodzhennya-sprinter",
    name: "Радіатор охолодження Behr",
    nameUK: "Радіатор охолодження двигуна",
    brand: "Behr Hella",
    sku: "8MK376716574",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-sprinter"],
    price: 4800,
    priceOld: 5600,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: ["/products/radiator-1.jpg"],
    description: "Радіатор охолодження двигуна Behr Hella для Sprinter 2.2/2.7 CDI. Алюмінієвий, висока ефективність тепловіддачі.",
    specs: [
      { label: "Матеріал", value: "Алюміній" },
      { label: "Ширина", value: "688 мм" },
      { label: "Висота", value: "458 мм" },
      { label: "Кількість рядів", value: "1" },
      { label: "Підключення", value: "ліве/праве знизу" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.5,
    reviewCount: 18,
    isNew: true,
    deliveryDays: 3,
    weight: 5.8,
    oem: ["9015001703"],
    tags: ["радіатор", "охолодження", "двигун"],
  },
  {
    id: "sp-007",
    slug: "kayaba-amortyzator-zad-sprinter",
    name: "Амортизатор задній KYB",
    nameUK: "Амортизатор задній",
    brand: "KYB",
    sku: "553370",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 1950,
    currency: "UAH",
    inStock: true,
    stockCount: 12,
    images: ["/products/shock-rear-1.jpg"],
    description: "Амортизатор задній KYB Excel-G для Sprinter. Двотрубний газомаслянний. Оригінальна якість від японського виробника.",
    specs: [
      { label: "Тип", value: "Газомаслянний двотрубний" },
      { label: "Вісь", value: "Задня" },
      { label: "Серія", value: "Excel-G" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.8,
    reviewCount: 61,
    isBestseller: true,
    deliveryDays: 1,
    weight: 2.1,
    oem: ["9063200631"],
    tags: ["амортизатор", "задній", "підвіска"],
  },
  {
    id: "sp-008",
    slug: "mann-filtr-povitryany-vito",
    name: "Фільтр повітряний Mann",
    nameUK: "Повітряний фільтр",
    brand: "Mann Filter",
    sku: "C35154",
    category: "engine",
    subcategory: "intake",
    vehicles: ["mercedes-vito", "mercedes-sprinter"],
    price: 280,
    currency: "UAH",
    inStock: true,
    stockCount: 38,
    images: ["/products/air-filter-1.jpg"],
    description: "Повітряний фільтр Mann для Mercedes Vito/Sprinter CDI. Трапецієподібний, висока фільтрація. Рекомендований виробником.",
    specs: [
      { label: "Тип", value: "Паперовий" },
      { label: "Форма", value: "Прямокутна" },
      { label: "Довжина", value: "285 мм" },
      { label: "Ширина", value: "195 мм" },
      { label: "Висота", value: "57 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1999–2014", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Sprinter", years: "2000–2012", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.9,
    reviewCount: 204,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.2,
    tags: ["фільтр", "повітря", "впуск"],
  },
  {
    id: "sp-009",
    slug: "ate-disk-galimivny-peredni-sprinter",
    name: "Диск гальмівний передній ATE",
    nameUK: "Гальмівний диск передній",
    brand: "ATE",
    sku: "24011002271",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-sprinter"],
    price: 1640,
    priceOld: 1900,
    currency: "UAH",
    inStock: true,
    stockCount: 7,
    images: ["/products/brake-disc-1.jpg"],
    description: "Гальмівний диск передній ATE PowerDisc для Sprinter W901. Вентильований, з покриттям проти іржі. Пара.",
    specs: [
      { label: "Тип", value: "Вентильований" },
      { label: "Вісь", value: "Передня" },
      { label: "Зовнішній діаметр", value: "300 мм" },
      { label: "Товщина", value: "28 мм (нова)" },
      { label: "Мінімальна товщина", value: "25 мм" },
      { label: "Кількість отворів", value: "5" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 44,
    deliveryDays: 2,
    weight: 7.2,
    oem: ["0014212112"],
    tags: ["диск", "гальма", "передній"],
  },
  {
    id: "sp-010",
    slug: "bosch-dzerkalo-bichne-sprinter",
    name: "Дзеркало бічне ліве Bosch",
    nameUK: "Бічне дзеркало ліве",
    brand: "Bosch",
    sku: "BSP25069",
    category: "body",
    subcategory: "mirrors",
    vehicles: ["mercedes-sprinter"],
    price: 3200,
    priceOld: 3800,
    currency: "UAH",
    inStock: true,
    stockCount: 4,
    images: ["/products/mirror-1.jpg"],
    description: "Дзеркало заднього виду бічне ліве з підігрівом для Sprinter W906. Електроскладання, підігрів, широкий кут огляду.",
    specs: [
      { label: "Сторона", value: "Ліва" },
      { label: "Підігрів", value: "Так" },
      { label: "Електрорегулювання", value: "Так" },
      { label: "Складання", value: "Електричне" },
      { label: "Під ґрунт", value: "Так" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 19,
    isNew: true,
    deliveryDays: 3,
    weight: 2.6,
    oem: ["A9068104116"],
    tags: ["дзеркало", "кузов", "ліве"],
  },
  {
    id: "sp-011",
    slug: "ngk-svicha-nakalu-sprinter",
    name: "Свіча розжарення NGK",
    nameUK: "Свіча розжарення",
    brand: "NGK",
    sku: "Y-735U",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 480,
    currency: "UAH",
    inStock: true,
    stockCount: 32,
    images: ["/products/glow-plug-1.jpg"],
    description: "Свіча розжарення NGK для дизельних двигунів Mercedes 2.2 CDI. Швидкий прогрів за 2–4 секунди. Ресурс 80 000 км.",
    specs: [
      { label: "Різьба", value: "M10×1.0" },
      { label: "Довжина різьби", value: "24 мм" },
      { label: "Напруга", value: "11.5 В" },
      { label: "Час нагріву", value: "2–4 с" },
      { label: "Температура нагріву", value: "850°C" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2010", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.8,
    reviewCount: 87,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.08,
    oem: ["0011594401"],
    tags: ["свіча", "розжарення", "дизель"],
  },
  {
    id: "sp-012",
    slug: "dolz-nassos-okholodzhennya-sprinter",
    name: "Насос охолодження Dolz",
    nameUK: "Помпа водяна",
    brand: "Dolz",
    sku: "M218",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-sprinter"],
    price: 1280,
    priceOld: 1520,
    currency: "UAH",
    inStock: true,
    stockCount: 9,
    images: ["/products/water-pump-1.jpg"],
    description: "Водяна помпа Dolz для Mercedes Sprinter 2.2 CDI. Кераміко-графітове ущільнення. Підходить для заміни з ременем ГРМ.",
    specs: [
      { label: "Кількість лопатей", value: "6" },
      { label: "Матеріал крильчатки", value: "Алюмінієвий сплав" },
      { label: "Ущільнення", value: "Кераміко-графітове" },
      { label: "Тип з'єднання", value: "Клиновий ремінь" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 31,
    deliveryDays: 2,
    weight: 0.9,
    oem: ["6112001101", "A6112001101"],
    tags: ["помпа", "охолодження", "двигун"],
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string, subcategory?: string): Product[] {
  return products.filter(
    (p) =>
      p.category === category &&
      (!subcategory || p.subcategory === subcategory)
  );
}

export function getProductsByVehicle(vehicleSlug: string): Product[] {
  return products.filter((p) => p.vehicles.includes(vehicleSlug));
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isBestseller || p.isNew).slice(0, 8);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}

export function getAllProducts(): Product[] {
  return products;
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(
      (p) =>
        p.id !== product.id &&
        (p.category === product.category ||
          p.vehicles.some((v) => product.vehicles.includes(v)))
    )
    .slice(0, limit);
}
