import type { Product } from "./types";

// Unique image per product — 8 confirmed-working Unsplash base IDs × different crop regions
const U = "https://images.unsplash.com/photo-";
const P = {
  // Engine bay / components
  eng:  (c: string) => `${U}1486262715619-67b85e0b08d3?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Brake disc / rotor
  brk:  (c: string) => `${U}1558618666-fcd25c85cd64?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Mechanic hands at work
  mec:  (c: string) => `${U}1563013544-824ae1b704d3?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Assorted car parts
  prt:  (c: string) => `${U}1492144534655-ae79c964c9d7?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Garage / underbody
  gar:  (c: string) => `${U}1621963416951-d5f1e3a0c08e?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Spark plug / ignition
  spk:  (c: string) => `${U}1509914398892-963f53e6e2f1?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Workshop / tools
  wsh:  (c: string) => `${U}1503736334260-d0a06d0c93a4?w=600&h=400&fit=crop&crop=${c}&q=80`,
  // Car exterior / lights
  ext:  (c: string) => `${U}1494976388531-d1058494cdd8?w=600&h=400&fit=crop&crop=${c}&q=80`,
};

export const products: Product[] = [
  // ─── SUSPENSION ────────────────────────────────────────────────────────────
  {
    id: "sp-001",
    slug: "bosch-amortyzator-peredni-sprinter",
    name: "Амортизатор передній Bosch",
    nameUK: "Амортизатор передній",
    brand: "Bosch",
    sku: "0986479R20",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 2480,
    priceOld: 2990,
    currency: "UAH",
    inStock: true,
    stockCount: 8,
    images: [P.mec("entropy")],
    description: "Оригінальний амортизатор передній для Mercedes Sprinter W901–905. Газомаслянний, підвищена надійність. Відповідає заводським специфікаціям.",
    specs: [
      { label: "Тип", value: "Газомаслянний" },
      { label: "Вісь", value: "Передня" },
      { label: "Довжина (стиснутий)", value: "365 мм" },
      { label: "Довжина (розтягнутий)", value: "600 мм" },
      { label: "Хід штока", value: "235 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI", "2.0 TDI"] },
    ],
    rating: 4.8,
    reviewCount: 47,
    isBestseller: true,
    deliveryDays: 1,
    weight: 2.4,
    oem: ["9013261100", "9013260800"],
    tags: ["амортизатор", "підвіска", "sprinter"],
  },
  {
    id: "sp-007",
    slug: "kayaba-amortyzator-zad-sprinter",
    name: "Амортизатор задній KYB Excel-G",
    nameUK: "Амортизатор задній",
    brand: "KYB",
    sku: "553370",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 1950,
    currency: "UAH",
    inStock: true,
    stockCount: 12,
    images: [P.mec("center")],
    description: "Амортизатор задній KYB Excel-G для Sprinter. Двотрубний газомаслянний. Оригінальна якість від японського виробника.",
    specs: [
      { label: "Тип", value: "Газомаслянний двотрубний" },
      { label: "Вісь", value: "Задня" },
      { label: "Серія", value: "Excel-G" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.8,
    reviewCount: 61,
    isBestseller: true,
    deliveryDays: 1,
    weight: 2.1,
    oem: ["9063200631"],
    tags: ["амортизатор", "задній", "підвіска"],
  },
  {
    id: "sp-004",
    slug: "meyle-kermove-nakonechnyk-sprinter",
    name: "Наконечник кермової тяги Meyle HD",
    nameUK: "Наконечник кермової тяги",
    brand: "Meyle",
    sku: "3160200006HD",
    category: "suspension",
    subcategory: "arms",
    vehicles: ["mercedes-sprinter"],
    price: 650,
    priceOld: 780,
    currency: "UAH",
    inStock: true,
    stockCount: 16,
    images: [P.prt("top")],
    description: "Наконечник рульової тяги HD (Heavy Duty) для Sprinter. Посилена конструкція для комерційного транспорту.",
    specs: [
      { label: "Сторона", value: "Права / Ліва (Universal)" },
      { label: "Різьба", value: "M14×1.5 (RH)" },
      { label: "Тип", value: "HD (Heavy Duty)" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 35,
    deliveryDays: 2,
    weight: 0.5,
    oem: ["9014601848", "9014602548"],
    tags: ["кермо", "наконечник", "тяга"],
  },
  {
    id: "sp-013",
    slug: "lemforder-rychag-peredni-sprinter",
    name: "Важіль підвіски передній Lemforder",
    nameUK: "Важіль підвіски",
    brand: "Lemforder",
    sku: "3740701",
    category: "suspension",
    subcategory: "arms",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 1850,
    priceOld: 2100,
    currency: "UAH",
    inStock: true,
    stockCount: 6,
    images: [P.wsh("left")],
    description: "Важіль підвіски нижній передній Lemforder для Sprinter та Crafter. Якість OEM, довгий ресурс завдяки посиленому кульовому шарніру.",
    specs: [
      { label: "Вісь", value: "Передня" },
      { label: "Положення", value: "Нижній" },
      { label: "Матеріал", value: "Кована сталь" },
      { label: "З кульовою опорою", value: "Так" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 28,
    isNew: false,
    deliveryDays: 2,
    weight: 3.2,
    oem: ["9063330020"],
    tags: ["важіль", "підвіска", "lemforder"],
  },
  {
    id: "sp-014",
    slug: "monroe-amortyzator-peredni-vito",
    name: "Амортизатор передній Monroe Original",
    nameUK: "Амортизатор передній",
    brand: "Monroe",
    sku: "G8076",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-vito"],
    price: 2150,
    currency: "UAH",
    inStock: true,
    stockCount: 10,
    images: [P.mec("bottom")],
    description: "Амортизатор передній Monroe Original для Mercedes Vito W638/639. Гарантована якість та надійність для комерційного транспорту.",
    specs: [
      { label: "Тип", value: "Газомаслянний" },
      { label: "Вісь", value: "Передня" },
      { label: "Серія", value: "Original" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2014", engines: ["2.2 CDI", "2.3"] },
    ],
    rating: 4.5,
    reviewCount: 19,
    deliveryDays: 2,
    weight: 2.2,
    oem: ["A6383200431"],
    tags: ["амортизатор", "vito", "monroe"],
  },
  {
    id: "sp-015",
    slug: "sachs-amortyzator-zad-crafter",
    name: "Амортизатор задній Sachs",
    nameUK: "Амортизатор задній",
    brand: "Sachs",
    sku: "312573",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["vw-crafter", "mercedes-sprinter"],
    price: 1680,
    currency: "UAH",
    inStock: true,
    stockCount: 7,
    images: [P.mec("top")],
    description: "Амортизатор задній Sachs для VW Crafter та Mercedes Sprinter. Надійна конструкція, точна відповідність заводським параметрам.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Тип", value: "Газомаслянний" },
    ],
    compatibility: [
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 22,
    deliveryDays: 2,
    weight: 2.0,
    oem: ["2E0413031"],
    tags: ["амортизатор", "crafter", "sachs"],
  },
  {
    id: "sp-016",
    slug: "febi-stab-pylynk-sprinter",
    name: "Стійка стабілізатора Febi",
    nameUK: "Стійка стабілізатора",
    brand: "Febi Bilstein",
    sku: "37029",
    category: "suspension",
    subcategory: "arms",
    vehicles: ["mercedes-sprinter"],
    price: 380,
    currency: "UAH",
    inStock: true,
    stockCount: 35,
    images: [P.prt("right")],
    description: "Стійка стабілізатора поперечної стійкості Febi для Sprinter. Чавунний наконечник зі сферичним шарніром, надійне ущільнення.",
    specs: [
      { label: "Сторона", value: "Ліва / Права" },
      { label: "Тип", value: "З кульовим шарніром" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 54,
    deliveryDays: 1,
    weight: 0.3,
    oem: ["9063201789"],
    tags: ["стабілізатор", "стійка", "підвіска"],
  },
  {
    id: "sp-017",
    slug: "meyle-sharnir-kuliovyi-sprinter",
    name: "Кульова опора нижня Meyle HD",
    nameUK: "Кульова опора",
    brand: "Meyle",
    sku: "3160100025HD",
    category: "suspension",
    subcategory: "arms",
    vehicles: ["mercedes-sprinter"],
    price: 920,
    priceOld: 1100,
    currency: "UAH",
    inStock: true,
    stockCount: 12,
    images: [P.gar("entropy")],
    description: "Кульова опора нижня Meyle HD для Mercedes Sprinter. Посилена конструкція HD підвищує ресурс у 2 рази порівняно з оригіналом.",
    specs: [
      { label: "Тип", value: "HD (Heavy Duty)" },
      { label: "Матеріал", value: "Кований сталевий корпус" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.8,
    reviewCount: 41,
    deliveryDays: 2,
    weight: 0.7,
    oem: ["0003308820"],
    tags: ["кульова", "опора", "meyle"],
  },

  // ─── BRAKES ────────────────────────────────────────────────────────────────
  {
    id: "sp-002",
    slug: "febi-kolodky-transmisni-sprinter",
    name: "Колодки гальмівні передні Febi",
    nameUK: "Колодки гальмівні передні",
    brand: "Febi Bilstein",
    sku: "FEBI16644",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 890,
    currency: "UAH",
    inStock: true,
    stockCount: 24,
    images: [P.brk("entropy")],
    description: "Гальмівні колодки передні для Mercedes Sprinter та Vito. Матеріал: низькометалевий з індикатором зносу.",
    specs: [
      { label: "Тип", value: "Дискові" },
      { label: "Вісь", value: "Передня" },
      { label: "Матеріал", value: "Низькометалевий" },
      { label: "Індикатор зносу", value: "Так" },
      { label: "Висота", value: "60 мм" },
      { label: "Товщина", value: "17 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["2.2 CDI", "2.3", "2.9 TDI"] },
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["2.3", "2.2 CDI"] },
    ],
    rating: 4.7,
    reviewCount: 93,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.8,
    oem: ["0014201020", "A0014201020"],
    tags: ["колодки", "гальма", "передні"],
  },
  {
    id: "sp-009",
    slug: "ate-disk-galimivny-peredni-sprinter",
    name: "Диск гальмівний передній ATE PowerDisc",
    nameUK: "Гальмівний диск передній",
    brand: "ATE",
    sku: "24011002271",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-sprinter"],
    price: 1640,
    priceOld: 1900,
    currency: "UAH",
    inStock: true,
    stockCount: 7,
    images: [P.brk("top")],
    description: "Гальмівний диск передній ATE PowerDisc для Sprinter W901. Вентильований, з покриттям проти іржі. Пара.",
    specs: [
      { label: "Тип", value: "Вентильований" },
      { label: "Вісь", value: "Передня" },
      { label: "Зовнішній діаметр", value: "300 мм" },
      { label: "Товщина (нова)", value: "28 мм" },
      { label: "Мінімальна товщина", value: "25 мм" },
      { label: "Кількість отворів", value: "5" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 44,
    deliveryDays: 2,
    weight: 7.2,
    oem: ["0014212112"],
    tags: ["диск", "гальма", "передній"],
  },
  {
    id: "sp-018",
    slug: "bosch-kolodky-zad-sprinter",
    name: "Колодки гальмівні задні Bosch",
    nameUK: "Колодки гальмівні задні",
    brand: "Bosch",
    sku: "0986424Z04",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 760,
    currency: "UAH",
    inStock: true,
    stockCount: 18,
    images: [P.brk("center")],
    description: "Гальмівні колодки задні Bosch для Sprinter та Crafter. Безшумна формула, рівномірний знос, легкий монтаж.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Тип", value: "Дискові" },
      { label: "Матеріал", value: "Низькометалевий безасбестовий" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 37,
    deliveryDays: 1,
    weight: 0.7,
    oem: ["A0064201020"],
    tags: ["колодки", "задні", "bosch"],
  },
  {
    id: "sp-019",
    slug: "textar-kolodky-peredni-vito",
    name: "Колодки гальмівні передні Textar",
    nameUK: "Колодки гальмівні передні",
    brand: "Textar",
    sku: "2358102",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-vito"],
    price: 980,
    currency: "UAH",
    inStock: true,
    stockCount: 20,
    images: [P.brk("bottom")],
    description: "Гальмівні колодки передні Textar для Mercedes Vito W638/639. Матеріал ECO-Friction, безшумна робота. Рекомендовані виробником.",
    specs: [
      { label: "Вісь", value: "Передня" },
      { label: "Матеріал", value: "ECO-Friction" },
      { label: "Індикатор зносу", value: "Так" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2014", engines: ["2.2 CDI", "2.3"] },
    ],
    rating: 4.8,
    reviewCount: 62,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.8,
    oem: ["0014200120"],
    tags: ["колодки", "textar", "vito"],
  },
  {
    id: "sp-020",
    slug: "ate-disk-galimivny-zad-sprinter",
    name: "Диск гальмівний задній ATE",
    nameUK: "Гальмівний диск задній",
    brand: "ATE",
    sku: "24012101961",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 1380,
    currency: "UAH",
    inStock: false,
    stockCount: 0,
    images: [P.brk("left")],
    description: "Гальмівний диск задній ATE для Sprinter та Crafter. Суцільний, антикорозійне покриття. Продається поштучно.",
    specs: [
      { label: "Тип", value: "Суцільний" },
      { label: "Вісь", value: "Задня" },
      { label: "Зовнішній діаметр", value: "290 мм" },
      { label: "Товщина (нова)", value: "16 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 21,
    deliveryDays: 3,
    weight: 5.8,
    oem: ["A9064230012"],
    tags: ["диск", "задній", "gальма"],
  },
  {
    id: "sp-021",
    slug: "brembo-disk-galimivny-peredni-crafter",
    name: "Диск гальмівний передній Brembo",
    nameUK: "Гальмівний диск передній",
    brand: "Brembo",
    sku: "09B10811",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["vw-crafter"],
    price: 2100,
    priceOld: 2450,
    currency: "UAH",
    inStock: true,
    stockCount: 4,
    images: [P.brk("right")],
    description: "Гальмівний диск передній Brembo для VW Crafter. Преміум клас, підвищена термостійкість, точна балансування.",
    specs: [
      { label: "Тип", value: "Вентильований" },
      { label: "Зовнішній діаметр", value: "308 мм" },
      { label: "Товщина (нова)", value: "28 мм" },
    ],
    compatibility: [
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI", "2.0 TDI"] },
    ],
    rating: 4.9,
    reviewCount: 15,
    isNew: true,
    deliveryDays: 2,
    weight: 8.1,
    oem: ["2E0615301"],
    tags: ["диск", "brembo", "crafter"],
  },

  // ─── ENGINE ────────────────────────────────────────────────────────────────
  {
    id: "sp-003",
    slug: "mahle-filtr-maslyany-sprinter",
    name: "Фільтр масляний Mahle",
    nameUK: "Фільтр масляний",
    brand: "Mahle",
    sku: "OX153D",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter", "mercedes-vito", "mercedes-lt"],
    price: 320,
    currency: "UAH",
    inStock: true,
    stockCount: 52,
    images: [P.eng("left")],
    description: "Масляний фільтр для дизельних двигунів Mercedes. Ефективна фільтрація, якість OEM. Підходить для 2.2 CDI та 2.7 CDI.",
    specs: [
      { label: "Тип", value: "Картриджний" },
      { label: "Висота", value: "97 мм" },
      { label: "Зовнішній діаметр", value: "76 мм" },
      { label: "Різьба", value: "M22×1.5" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2018", engines: ["2.2 CDI", "2.7 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.9,
    reviewCount: 128,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.3,
    oem: ["A6111800009", "6111800009"],
    tags: ["фільтр", "масло", "двигун"],
  },
  {
    id: "sp-008",
    slug: "mann-filtr-povitryany-vito",
    name: "Фільтр повітряний Mann-Filter",
    nameUK: "Повітряний фільтр",
    brand: "Mann Filter",
    sku: "C35154",
    category: "engine",
    subcategory: "intake",
    vehicles: ["mercedes-vito", "mercedes-sprinter"],
    price: 280,
    currency: "UAH",
    inStock: true,
    stockCount: 38,
    images: [P.eng("right")],
    description: "Повітряний фільтр Mann для Mercedes Vito/Sprinter CDI. Трапецієподібний, висока фільтрація. Рекомендований виробником.",
    specs: [
      { label: "Тип", value: "Паперовий" },
      { label: "Форма", value: "Прямокутна" },
      { label: "Довжина", value: "285 мм" },
      { label: "Ширина", value: "195 мм" },
      { label: "Висота", value: "57 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1999–2014", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Sprinter", years: "2000–2012", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.9,
    reviewCount: 204,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.2,
    tags: ["фільтр", "повітря", "впуск"],
  },
  {
    id: "sp-006",
    slug: "behr-radyator-okholodzhennya-sprinter",
    name: "Радіатор охолодження Behr Hella",
    nameUK: "Радіатор охолодження двигуна",
    brand: "Behr Hella",
    sku: "8MK376716574",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-sprinter"],
    price: 4800,
    priceOld: 5600,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: [P.eng("top")],
    description: "Радіатор охолодження двигуна Behr Hella для Sprinter 2.2/2.7 CDI. Алюмінієвий, висока ефективність тепловіддачі.",
    specs: [
      { label: "Матеріал", value: "Алюміній" },
      { label: "Ширина", value: "688 мм" },
      { label: "Висота", value: "458 мм" },
      { label: "Кількість рядів", value: "1" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.5,
    reviewCount: 18,
    isNew: true,
    deliveryDays: 3,
    weight: 5.8,
    oem: ["9015001703"],
    tags: ["радіатор", "охолодження", "двигун"],
  },
  {
    id: "sp-012",
    slug: "dolz-nassos-okholodzhennya-sprinter",
    name: "Насос охолодження Dolz (помпа)",
    nameUK: "Помпа водяна",
    brand: "Dolz",
    sku: "M218",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-sprinter"],
    price: 1280,
    priceOld: 1520,
    currency: "UAH",
    inStock: true,
    stockCount: 9,
    images: [P.gar("top")],
    description: "Водяна помпа Dolz для Mercedes Sprinter 2.2 CDI. Кераміко-графітове ущільнення. Підходить для заміни з ременем ГРМ.",
    specs: [
      { label: "Кількість лопатей", value: "6" },
      { label: "Матеріал крильчатки", value: "Алюмінієвий сплав" },
      { label: "Ущільнення", value: "Кераміко-графітове" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 31,
    deliveryDays: 2,
    weight: 0.9,
    oem: ["6112001101", "A6112001101"],
    tags: ["помпа", "охолодження", "двигун"],
  },
  {
    id: "sp-022",
    slug: "mann-filtr-palyva-sprinter",
    name: "Фільтр паливний Mann-Filter",
    nameUK: "Паливний фільтр",
    brand: "Mann Filter",
    sku: "WK9028",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter", "mercedes-vito", "vw-crafter"],
    price: 450,
    currency: "UAH",
    inStock: true,
    stockCount: 42,
    images: [P.eng("center")],
    description: "Паливний фільтр Mann для дизельних двигунів Mercedes та VW. Тонка фільтрація забезпечує чистоту палива та захист форсунок.",
    specs: [
      { label: "Тип", value: "Картриджний з водовіддільником" },
      { label: "Висота", value: "175 мм" },
      { label: "Зовнішній діаметр", value: "105 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["2.2 CDI", "3.0 CDI"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI", "2.0 TDI"] },
    ],
    rating: 4.8,
    reviewCount: 78,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.4,
    oem: ["A0024776701"],
    tags: ["фільтр", "паливо", "дизель"],
  },
  {
    id: "sp-023",
    slug: "contitech-komplet-grm-sprinter",
    name: "Комплект ГРМ ContiTech CT1068K3",
    nameUK: "Комплект ременя ГРМ",
    brand: "ContiTech",
    sku: "CT1068K3",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 3400,
    priceOld: 4100,
    currency: "UAH",
    inStock: true,
    stockCount: 5,
    images: [P.wsh("entropy")],
    description: "Комплект ременя ГРМ ContiTech для Mercedes Sprinter та Vito 2.2 CDI. Ремінь + ролик натяжний + обвідний ролик. Оригінальна якість.",
    specs: [
      { label: "Кількість деталей", value: "3 (ремінь + 2 ролики)" },
      { label: "Кількість зубів", value: "166" },
      { label: "Ширина ременя", value: "27 мм" },
      { label: "Ресурс", value: "120 000 км" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.9,
    reviewCount: 56,
    isBestseller: true,
    deliveryDays: 2,
    weight: 0.8,
    oem: ["A6119971594"],
    tags: ["грм", "ремінь", "комплект"],
  },
  {
    id: "sp-024",
    slug: "mahle-termostat-sprinter",
    name: "Термостат Mahle",
    nameUK: "Термостат",
    brand: "Mahle",
    sku: "TX10682",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 680,
    currency: "UAH",
    inStock: true,
    stockCount: 20,
    images: [P.gar("bottom")],
    description: "Термостат Mahle для Mercedes Sprinter та Vito 2.2 CDI. Температура відкриття 83°C. Точна відповідність заводським параметрам.",
    specs: [
      { label: "Температура відкриття", value: "83°C" },
      { label: "Тип", value: "З кожухом" },
      { label: "Прокладка включена", value: "Так" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2018", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2014", engines: ["2.2 CDI"] },
    ],
    rating: 4.7,
    reviewCount: 43,
    deliveryDays: 1,
    weight: 0.25,
    oem: ["A6112000015"],
    tags: ["термостат", "охолодження", "двигун"],
  },
  {
    id: "sp-025",
    slug: "bosch-forsunka-sprinter",
    name: "Форсунка паливна Bosch (відновлена)",
    nameUK: "Форсунка паливна",
    brand: "Bosch",
    sku: "0445110070",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter"],
    price: 2400,
    priceOld: 4200,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: [P.spk("entropy")],
    description: "Форсунка дизельна Common Rail Bosch для Sprinter 2.2 CDI. Відновлена на заводі до стандартів OEM. З гарантією 12 місяців.",
    specs: [
      { label: "Тип", value: "Common Rail (CRDI)" },
      { label: "Стан", value: "Заводське відновлення" },
      { label: "Тиск відкриття", value: "1600 бар" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 12,
    isNew: true,
    deliveryDays: 3,
    weight: 0.15,
    oem: ["A6110700587"],
    tags: ["форсунка", "common rail", "двигун"],
  },

  // ─── TRANSMISSION ──────────────────────────────────────────────────────────
  {
    id: "sp-005",
    slug: "valeo-disk-zcheplennya-sprinter",
    name: "Комплект зчеплення Valeo KIT3P",
    nameUK: "Комплект зчеплення",
    brand: "Valeo",
    sku: "286302",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 3200,
    priceOld: 3800,
    currency: "UAH",
    inStock: true,
    stockCount: 5,
    images: [P.gar("right")],
    description: "Комплект зчеплення Valeo KIT3P (диск + кошик + підшипник) для Sprinter 2.2 CDI. Завершена система від одного виробника.",
    specs: [
      { label: "Тип", value: "KIT3P (3 деталі)" },
      { label: "Діаметр", value: "240 мм" },
      { label: "Кількість зубів", value: "22" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI"] },
    ],
    rating: 4.7,
    reviewCount: 22,
    deliveryDays: 2,
    weight: 4.2,
    oem: ["A0022508504"],
    tags: ["зчеплення", "diск", "трансмісія"],
  },
  {
    id: "sp-026",
    slug: "sachs-zcheplennya-vito",
    name: "Комплект зчеплення Sachs",
    nameUK: "Комплект зчеплення",
    brand: "Sachs",
    sku: "3000951816",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["mercedes-vito"],
    price: 2890,
    currency: "UAH",
    inStock: true,
    stockCount: 4,
    images: [P.mec("left")],
    description: "Комплект зчеплення Sachs (диск + кошик + підшипник) для Mercedes Vito 2.2 CDI. Стандартна якість OEM, надійна конструкція.",
    specs: [
      { label: "Вміст", value: "Диск + Кошик + Підшипник" },
      { label: "Діаметр", value: "228 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 14,
    deliveryDays: 3,
    weight: 3.8,
    oem: ["A6382500804"],
    tags: ["зчеплення", "sachs", "vito"],
  },
  {
    id: "sp-027",
    slug: "luk-disk-zcheplennya-crafter",
    name: "Диск зчеплення LUK",
    nameUK: "Диск зчеплення",
    brand: "LUK",
    sku: "322026610",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["vw-crafter"],
    price: 1650,
    currency: "UAH",
    inStock: true,
    stockCount: 7,
    images: [P.prt("left")],
    description: "Диск зчеплення ведений LUK для VW Crafter 2.5 TDI. Фрикційний матеріал з підвищеним ресурсом, демпфер крутильних коливань.",
    specs: [
      { label: "Діаметр", value: "240 мм" },
      { label: "Кількість зубів", value: "22" },
      { label: "Демпфер", value: "Так" },
    ],
    compatibility: [
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI"] },
    ],
    rating: 4.5,
    reviewCount: 9,
    deliveryDays: 3,
    weight: 1.8,
    oem: ["2E0141031D"],
    tags: ["диск", "зчеплення", "luk"],
  },

  // ─── ELECTRICAL ────────────────────────────────────────────────────────────
  {
    id: "sp-011",
    slug: "ngk-svicha-nakalu-sprinter",
    name: "Свіча розжарення NGK",
    nameUK: "Свіча розжарення",
    brand: "NGK",
    sku: "Y-735U",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 480,
    currency: "UAH",
    inStock: true,
    stockCount: 32,
    images: [P.spk("top")],
    description: "Свіча розжарення NGK для дизельних двигунів Mercedes 2.2 CDI. Швидкий прогрів 2–4 секунди. Ресурс 80 000 км.",
    specs: [
      { label: "Різьба", value: "M10×1.0" },
      { label: "Довжина різьби", value: "24 мм" },
      { label: "Напруга", value: "11.5 В" },
      { label: "Час нагріву", value: "2–4 с" },
      { label: "Температура", value: "850°C" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2010", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.8,
    reviewCount: 87,
    isBestseller: true,
    deliveryDays: 1,
    weight: 0.08,
    oem: ["0011594401"],
    tags: ["свіча", "розжарення", "дизель"],
  },
  {
    id: "sp-028",
    slug: "bosch-generator-sprinter",
    name: "Генератор Bosch (відновлений)",
    nameUK: "Генератор",
    brand: "Bosch",
    sku: "1986A00637",
    category: "electrical",
    subcategory: "alternators",
    vehicles: ["mercedes-sprinter"],
    price: 5200,
    priceOld: 8900,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.spk("bottom")],
    description: "Генератор Bosch для Mercedes Sprinter 2.2/2.7 CDI. Відновлений до стандарту OEM. Потужність 90 А. Гарантія 12 місяців.",
    specs: [
      { label: "Струм", value: "90 А" },
      { label: "Напруга", value: "14 В" },
      { label: "Стан", value: "Заводське відновлення" },
      { label: "Обертання", value: "Праворуч (CW)" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 8,
    isNew: false,
    deliveryDays: 3,
    weight: 5.2,
    oem: ["A0001500050"],
    tags: ["генератор", "електрика", "sprinter"],
  },
  {
    id: "sp-029",
    slug: "bosch-starter-sprinter",
    name: "Стартер Bosch (відновлений)",
    nameUK: "Стартер",
    brand: "Bosch",
    sku: "1986S00866",
    category: "electrical",
    subcategory: "alternators",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 4100,
    priceOld: 7200,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: [P.spk("left")],
    description: "Стартер Bosch для Sprinter та Crafter дизельних двигунів. Відновлений. Потужність 2.1 кВт. Гарантія 12 місяців.",
    specs: [
      { label: "Потужність", value: "2.1 кВт" },
      { label: "Напруга", value: "12 В" },
      { label: "Кількість зубів шестерні", value: "10" },
      { label: "Стан", value: "Заводське відновлення" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2018", engines: ["всі дизельні"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI", "2.0 TDI"] },
    ],
    rating: 4.5,
    reviewCount: 11,
    deliveryDays: 3,
    weight: 4.8,
    oem: ["A0051511801"],
    tags: ["стартер", "електрика", "двигун"],
  },
  {
    id: "sp-030",
    slug: "beru-svichy-rozzharyuvannya-sprinter",
    name: "Комплект свічок розжарення Beru",
    nameUK: "Свічки розжарення (комплект 4 шт)",
    brand: "Beru",
    sku: "GE118",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 1920,
    currency: "UAH",
    inStock: true,
    stockCount: 14,
    images: [P.spk("right")],
    description: "Комплект свічок розжарення Beru (4 шт) для Mercedes CDI. Швидкий нагрів, підвищений ресурс 80 000 км. Виробник — Bosch Group.",
    specs: [
      { label: "Кількість", value: "4 шт" },
      { label: "Тип", value: "Металокерамічна" },
      { label: "Різьба", value: "M10×1.0" },
      { label: "Час нагріву", value: "2–4 с" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2018", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2014", engines: ["2.2 CDI"] },
    ],
    rating: 4.8,
    reviewCount: 33,
    deliveryDays: 1,
    weight: 0.32,
    oem: ["0011594401"],
    tags: ["свічки", "розжарення", "beru"],
  },

  // ─── BODY ──────────────────────────────────────────────────────────────────
  {
    id: "sp-010",
    slug: "bosch-dzerkalo-bichne-sprinter",
    name: "Дзеркало бічне ліве з підігрівом",
    nameUK: "Бічне дзеркало ліве",
    brand: "Bosch",
    sku: "BSP25069",
    category: "body",
    subcategory: "mirrors",
    vehicles: ["mercedes-sprinter"],
    price: 3200,
    priceOld: 3800,
    currency: "UAH",
    inStock: true,
    stockCount: 4,
    images: [P.ext("entropy")],
    description: "Дзеркало заднього виду бічне ліве з підігрівом для Sprinter W906. Електроскладання, підігрів, широкий кут огляду.",
    specs: [
      { label: "Сторона", value: "Ліва" },
      { label: "Підігрів", value: "Так" },
      { label: "Електрорегулювання", value: "Так" },
      { label: "Складання", value: "Електричне" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 19,
    isNew: true,
    deliveryDays: 3,
    weight: 2.6,
    oem: ["A9068104116"],
    tags: ["дзеркало", "кузов", "ліве"],
  },
  {
    id: "sp-031",
    slug: "valeo-fara-perednia-sprinter",
    name: "Фара передня ліва Valeo",
    nameUK: "Фара передня",
    brand: "Valeo",
    sku: "043655",
    category: "lighting",
    subcategory: "headlights",
    vehicles: ["mercedes-sprinter"],
    price: 2800,
    priceOld: 3200,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: [P.ext("top")],
    description: "Фара передня ліва Valeo для Mercedes Sprinter W906. Заводська комплектація: ближнє + дальнє + покажчик поворотів. Без лампочок.",
    specs: [
      { label: "Сторона", value: "Ліва" },
      { label: "Тип", value: "Комбінована (без лампочок)" },
      { label: "Покажчик повороту", value: "Включений" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
    ],
    rating: 4.4,
    reviewCount: 11,
    isNew: true,
    deliveryDays: 4,
    weight: 2.8,
    oem: ["A9068200661"],
    tags: ["фара", "ліва", "кузов"],
  },
  {
    id: "sp-032",
    slug: "depo-fonar-zad-sprinter",
    name: "Ліхтар задній правий Depo",
    nameUK: "Ліхтар задній",
    brand: "Depo",
    sku: "440-1971R-UE",
    category: "lighting",
    subcategory: "taillights",
    vehicles: ["mercedes-sprinter"],
    price: 1450,
    currency: "UAH",
    inStock: true,
    stockCount: 6,
    images: [P.ext("bottom")],
    description: "Ліхтар задній правий Depo для Mercedes Sprinter W906. Стоп-сигнал + покажчик + задній хід + протитуманний. Без лампочок.",
    specs: [
      { label: "Сторона", value: "Права" },
      { label: "Тип кузова", value: "Фургон" },
      { label: "Без лампочок", value: "Так" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2013", engines: ["всі"] },
    ],
    rating: 4.3,
    reviewCount: 8,
    deliveryDays: 3,
    weight: 1.2,
    oem: ["A9068200064"],
    tags: ["ліхтар", "задній", "кузов"],
  },

  // ─── REAL CATALOG FROM DATABASE ────────────────────────────────────────────
  {
    id: "sp-033",
    slug: "422381-abs-caliper",
    name: "Супорт передній лівий A.B.S. Sprinter",
    nameUK: "Супорт передній лівий",
    brand: "A.B.S.",
    sku: "422381",
    category: "brakes",
    subcategory: "calipers",
    vehicles: ["mercedes-sprinter"],
    price: 2047,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.brk("focalpoint")],
    description: "Супорт гальмівного механізму передній лівий для Mercedes Sprinter. Діаметр поршня 60 мм. Сумісний з ATE/Bosch скобами.",
    specs: [
      { label: "Сторона", value: "Ліва" },
      { label: "Вісь", value: "Передня" },
      { label: "Діаметр поршня", value: "60 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 7,
    deliveryDays: 2,
    tags: ["супорт", "гальма", "caliper"],
  },
  {
    id: "sp-034",
    slug: "621472-abs-caliper-vito",
    name: "Супорт гальмівний задній A.B.S. Vito W639",
    nameUK: "Супорт гальмівний задній",
    brand: "A.B.S.",
    sku: "621472",
    category: "brakes",
    subcategory: "calipers",
    vehicles: ["mercedes-vito"],
    price: 2223,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.brk("faces")],
    description: "Супорт гальмівного механізму задній для Mercedes Vito W639 03-08. Оригінальна конструкція, точна відповідність.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Модель", value: "Vito W639" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "2003–2008", engines: ["всі"] },
    ],
    rating: 4.4,
    reviewCount: 12,
    deliveryDays: 2,
    tags: ["супорт", "гальма", "vito"],
  },
  {
    id: "sp-035",
    slug: "16887-abs-disc-vito",
    name: "Диск гальмівний передній A.B.S. Vito W638",
    nameUK: "Гальмівний диск передній",
    brand: "A.B.S.",
    sku: "16887",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-vito"],
    price: 1413,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.brk("focalpoint")],
    description: "Гальмівний диск передній вентильований для Mercedes Vito W638 96-03. Антикорозійне покриття, точна балансування.",
    specs: [
      { label: "Тип", value: "Вентильований" },
      { label: "Вісь", value: "Передня" },
      { label: "Модель", value: "Vito W638" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 18,
    deliveryDays: 2,
    tags: ["диск", "гальма", "vito"],
  },
  {
    id: "sp-036",
    slug: "18465-abs-disc-vito-w447",
    name: "Диск гальмівний задній A.B.S. Vito W447",
    nameUK: "Гальмівний диск задній",
    brand: "A.B.S.",
    sku: "18465",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-vito"],
    price: 1584,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.brk("faces")],
    description: "Гальмівний диск задній PRO для Mercedes Vito W447 2014-. Розмір 300×12 мм, суцільний, антикорозійний.",
    specs: [
      { label: "Тип", value: "Суцільний PRO" },
      { label: "Вісь", value: "Задня" },
      { label: "Розмір", value: "300×12 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "2014–2022", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 9,
    deliveryDays: 2,
    tags: ["диск", "гальма", "vito"],
  },
  {
    id: "sp-037",
    slug: "17569-abs-disc-vito-w639",
    name: "Диск гальмівний передній A.B.S. Vito W639",
    nameUK: "Гальмівний диск передній",
    brand: "A.B.S.",
    sku: "17569",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-vito"],
    price: 1892,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.brk("entropy")],
    description: "Гальмівний диск передній для Mercedes Vito W639 2003-. Вентильований 300×28 мм. Якість A.B.S.",
    specs: [
      { label: "Тип", value: "Вентильований" },
      { label: "Розмір", value: "300×28 мм" },
      { label: "Вісь", value: "Передня" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "2003–2014", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 22,
    deliveryDays: 2,
    tags: ["диск", "гальма", "vito"],
  },
  {
    id: "sp-038",
    slug: "16950-abs-disc-sprinter",
    name: "Диск гальмівний задній A.B.S. Sprinter 408-416",
    nameUK: "Гальмівний диск задній",
    brand: "A.B.S.",
    sku: "16950",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-sprinter"],
    price: 1950,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.wsh("right")],
    description: "Гальмівний диск задній для Mercedes Sprinter 408-416 / VW LT 46 1996-. Розмір 285×22 мм, вентильований.",
    specs: [
      { label: "Тип", value: "Вентильований" },
      { label: "Розмір", value: "285×22 мм" },
      { label: "Вісь", value: "Задня" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 31,
    deliveryDays: 2,
    tags: ["диск", "гальма", "sprinter"],
  },
  {
    id: "sp-039",
    slug: "df4088s-trw-disc-sprinter",
    name: "Диск гальмівний задній TRW Sprinter 308-316",
    nameUK: "Гальмівний диск задній",
    brand: "TRW",
    sku: "DF4088S",
    category: "brakes",
    subcategory: "discs",
    vehicles: ["mercedes-sprinter"],
    price: 2028,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.wsh("center")],
    description: "Гальмівний диск задній TRW для Sprinter 308-316 CDI 1996-. Розмір 272×10 мм. Серія Premium — підвищена термостійкість.",
    specs: [
      { label: "Тип", value: "Суцільний" },
      { label: "Розмір", value: "272×10 мм" },
      { label: "Серія", value: "Premium" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 14,
    deliveryDays: 2,
    tags: ["диск", "гальма", "trw", "sprinter"],
  },
  {
    id: "sp-040",
    slug: "36902-abs-pads-sprinter",
    name: "Колодки гальмівні задні A.B.S. Sprinter 208-216",
    nameUK: "Колодки гальмівні задні",
    brand: "A.B.S.",
    sku: "36902",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-sprinter"],
    price: 609,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.brk("focalpoint")],
    description: "Гальмівні колодки задні для Mercedes Sprinter 208-216 96-06 (система ATE). Низькометалевий матеріал, безшумна робота.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Система", value: "ATE" },
      { label: "Матеріал", value: "Низькометалевий" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 16,
    deliveryDays: 1,
    tags: ["колодки", "гальма", "sprinter"],
  },
  {
    id: "sp-041",
    slug: "36913-abs-pads-sprinter-rear",
    name: "Колодки гальмівні задні A.B.S. Sprinter 208-316",
    nameUK: "Колодки гальмівні задні",
    brand: "A.B.S.",
    sku: "36913",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-sprinter"],
    price: 734,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: [P.brk("faces")],
    description: "Гальмівні колодки задні для Sprinter 208-316 96- (Teves, велика спарка). Сертифіковані за ECE R90.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Система", value: "Teves" },
      { label: "Сертифікат", value: "ECE R90" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 28,
    deliveryDays: 1,
    tags: ["колодки", "гальма", "sprinter"],
  },
  {
    id: "sp-042",
    slug: "36901-abs-pads-sprinter-front",
    name: "Колодки гальмівні передні A.B.S. Sprinter/LT 96-06",
    nameUK: "Колодки гальмівні передні",
    brand: "A.B.S.",
    sku: "36901",
    category: "brakes",
    subcategory: "pads",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 813,
    currency: "UAH",
    inStock: true,
    stockCount: 4,
    images: [P.prt("center")],
    description: "Гальмівні колодки передні для Sprinter/LT 96-06/Vito 96-99. Стандартна якість, ECE R90.",
    specs: [
      { label: "Вісь", value: "Передня" },
      { label: "Сертифікат", value: "ECE R90" },
      { label: "Виробник системи", value: "Bosch/ATE" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
      { vehicle: "Mercedes Vito", years: "1996–1999", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 41,
    deliveryDays: 1,
    tags: ["колодки", "гальма", "sprinter"],
  },
  {
    id: "sp-043",
    slug: "45443-febi-sensor-temp",
    name: "Датчик температури охолодження Febi Sprinter/Vito",
    nameUK: "Датчик температури охолодження",
    brand: "Febi Bilstein",
    sku: "45443",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 350,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.spk("center")],
    description: "Датчик температури охолоджуючої рідини Febi для Mercedes Sprinter/Vito CDI. 2-контактний. Контролює температуру двигуна.",
    specs: [
      { label: "Кількість контактів", value: "2" },
      { label: "Різьба", value: "M14×1.5" },
      { label: "Діапазон", value: "-40 … +130°C" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2010", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 19,
    deliveryDays: 1,
    tags: ["датчик", "температура", "sensors"],
  },
  {
    id: "sp-044",
    slug: "37142-febi-sensor-air",
    name: "Датчик температури впуску Febi Vito W639",
    nameUK: "Датчик температури впуску",
    brand: "Febi Bilstein",
    sku: "37142",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-vito"],
    price: 494,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.spk("focalpoint")],
    description: "Датчик температури повітря на впуску для Mercedes Vito W639 CDI. Контролює температуру для точного дозування палива.",
    specs: [
      { label: "Тип", value: "NTC" },
      { label: "Кількість контактів", value: "2" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "2003–2010", engines: ["2.2 CDI"] },
    ],
    rating: 4.5,
    reviewCount: 8,
    deliveryDays: 2,
    tags: ["датчик", "впуск", "vito"],
  },
  {
    id: "sp-045",
    slug: "186099-febi-abs-sensor",
    name: "Датчик ABS задній Febi Sprinter/Crafter 06-",
    nameUK: "Датчик ABS задній",
    brand: "Febi Bilstein",
    sku: "186099",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 650,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.spk("faces")],
    description: "Датчик ABS задній лівий для Mercedes Sprinter / VW Crafter 2006-. Довжина кабелю 1945 мм.",
    specs: [
      { label: "Вісь", value: "Задня, ліва" },
      { label: "Довжина кабелю", value: "1945 мм" },
      { label: "Тип сигналу", value: "Активний (Hall)" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 23,
    deliveryDays: 1,
    tags: ["датчик", "abs", "sprinter"],
  },
  {
    id: "sp-046",
    slug: "30765-abs-sensor-sprinter",
    name: "Датчик ABS задній A.B.S. Sprinter/VW LT 95-2006",
    nameUK: "Датчик ABS задній",
    brand: "A.B.S.",
    sku: "30765",
    category: "electrical",
    subcategory: "sensors",
    vehicles: ["mercedes-sprinter"],
    price: 651,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.eng("focalpoint")],
    description: "Датчик ABS задній для Mercedes Sprinter / VW LT II 28 1995-2006. Пасивний тип (індуктивний). Оригінальна якість A.B.S.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Тип", value: "Індуктивний" },
      { label: "Кількість контактів", value: "2" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 34,
    deliveryDays: 1,
    tags: ["датчик", "abs", "sprinter"],
  },
  {
    id: "sp-047",
    slug: "02-19-239-trucktec-thermostat",
    name: "Термостат Trucktec Vito W638 / Sprinter CDI",
    nameUK: "Термостат",
    brand: "Trucktec",
    sku: "02.19.239",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-vito", "mercedes-sprinter"],
    price: 588,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.eng("bottom")],
    description: "Термостат для Mercedes Vito W638 та Sprinter 2.2-2.7 CDI. Температура відкриття 83°C. В комплекті прокладка.",
    specs: [
      { label: "Температура відкриття", value: "83°C" },
      { label: "Прокладка", value: "В комплекті" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.5,
    reviewCount: 11,
    deliveryDays: 2,
    tags: ["термостат", "охолодження", "двигун"],
  },
  {
    id: "sp-048",
    slug: "tx47687d-mahle-thermostat",
    name: "Термостат Mahle Vito W638 / Sprinter 2.2-2.7CDI",
    nameUK: "Термостат",
    brand: "Mahle",
    sku: "TX47687D",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["mercedes-vito", "mercedes-sprinter"],
    price: 1098,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.gar("center")],
    description: "Термостат Mahle Original для Vito W638 / Sprinter CDI. Висока точність відкриття 83°C. OEM якість.",
    specs: [
      { label: "Температура відкриття", value: "83°C" },
      { label: "Серія", value: "Original" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI", "2.7 CDI"] },
    ],
    rating: 4.8,
    reviewCount: 27,
    deliveryDays: 1,
    tags: ["термостат", "охолодження", "mahle"],
  },
  {
    id: "sp-049",
    slug: "ti3587-mahle-thermostat-crafter",
    name: "Термостат Mahle VW Crafter 2.0TDI",
    nameUK: "Термостат",
    brand: "Mahle",
    sku: "TI3587",
    category: "engine",
    subcategory: "cooling",
    vehicles: ["vw-crafter"],
    price: 1196,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.prt("bottom")],
    description: "Термостат Mahle для VW Crafter 2.0 TDI. Точна відповідність OEM. Забезпечує оптимальну температуру двигуна.",
    specs: [
      { label: "Модель двигуна", value: "2.0 TDI" },
      { label: "Тип", value: "З корпусом" },
    ],
    compatibility: [
      { vehicle: "VW Crafter", years: "2011–2016", engines: ["2.0 TDI"] },
    ],
    rating: 4.7,
    reviewCount: 14,
    deliveryDays: 2,
    tags: ["термостат", "охолодження", "crafter"],
  },
  {
    id: "sp-050",
    slug: "ox153d3-mahle-oil-filter",
    name: "Фільтр масляний Mahle Sprinter/Vito CDI OM611/612/646",
    nameUK: "Фільтр масляний",
    brand: "Mahle",
    sku: "OX153D3",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 222,
    currency: "UAH",
    inStock: true,
    stockCount: 154,
    images: [P.eng("faces")],
    description: "Масляний фільтр Mahle для Mercedes CDI двигунів OM611 / OM612 / OM646. Дрібна фільтрація, 100% тест.",
    specs: [
      { label: "Тип", value: "Змінний елемент" },
      { label: "Двигуни", value: "OM611 / OM612 / OM646" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2012", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2014", engines: ["2.2 CDI"] },
    ],
    rating: 4.9,
    reviewCount: 88,
    isBestseller: true,
    deliveryDays: 1,
    tags: ["фільтр", "масло", "mahle"],
  },
  {
    id: "sp-051",
    slug: "ox143d-mahle-oil-filter-crafter",
    name: "Фільтр масляний Mahle VW LT/Crafter 2.5TDI",
    nameUK: "Фільтр масляний",
    brand: "Mahle",
    sku: "OX143D",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["vw-crafter"],
    price: 220,
    currency: "UAH",
    inStock: true,
    stockCount: 12,
    images: [P.eng("focalpoint")],
    description: "Масляний фільтр Mahle для VW LT 96- / Crafter 06- 2.5 TDI. Висока фільтрувальна здатність.",
    specs: [
      { label: "Двигун", value: "2.5 TDI" },
      { label: "Тип", value: "Картриджний" },
    ],
    compatibility: [
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["2.5 TDI"] },
    ],
    rating: 4.8,
    reviewCount: 42,
    deliveryDays: 1,
    tags: ["фільтр", "масло", "crafter"],
  },
  {
    id: "sp-052",
    slug: "ox380d-mahle-oil-filter-3l",
    name: "Фільтр масляний Mahle Sprinter 3.0CDI OM642",
    nameUK: "Фільтр масляний",
    brand: "Mahle",
    sku: "OX380D",
    category: "engine",
    subcategory: "engine-parts",
    vehicles: ["mercedes-sprinter"],
    price: 342,
    currency: "UAH",
    inStock: true,
    stockCount: 5,
    images: [P.wsh("top")],
    description: "Масляний фільтр Mahle для Mercedes Sprinter 3.0 CDI (двигун OM642) 2006-. Преміум фільтрація, ресурс до 30 000 км.",
    specs: [
      { label: "Двигун", value: "OM642 3.0 CDI" },
      { label: "Ресурс", value: "30 000 км" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["3.0 CDI"] },
    ],
    rating: 4.8,
    reviewCount: 31,
    deliveryDays: 1,
    tags: ["фільтр", "масло", "sprinter", "3.0cdi"],
  },
  {
    id: "sp-053",
    slug: "380-770-elring-gasket",
    name: "Прокладка впускного колектора Elring Sprinter/Vito 2.2CDI",
    nameUK: "Прокладка впускного колектора",
    brand: "Elring",
    sku: "380.770",
    category: "engine",
    subcategory: "gaskets",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 70,
    currency: "UAH",
    inStock: true,
    stockCount: 10,
    images: [P.prt("entropy")],
    description: "Прокладка впускного колектора Elring для Sprinter/Vito 2.2 CDI OM611. Матеріал: армований еластомер.",
    specs: [
      { label: "Матеріал", value: "Армований еластомер" },
      { label: "Двигун", value: "OM611 2.2 CDI" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2000–2006", engines: ["2.2 CDI"] },
      { vehicle: "Mercedes Vito", years: "1999–2006", engines: ["2.2 CDI"] },
    ],
    rating: 4.7,
    reviewCount: 33,
    deliveryDays: 1,
    tags: ["прокладка", "колектор", "двигун"],
  },
  {
    id: "sp-054",
    slug: "982-420-elring-gasket-3l",
    name: "Прокладка впускного колектора Elring Sprinter 3.0CDI",
    nameUK: "Прокладка впускного колектора",
    brand: "Elring",
    sku: "982.420",
    category: "engine",
    subcategory: "gaskets",
    vehicles: ["mercedes-sprinter"],
    price: 190,
    currency: "UAH",
    inStock: true,
    stockCount: 4,
    images: [P.prt("focalpoint")],
    description: "Прокладка впускного колектора Elring для Sprinter 3.0 CDI 06- (двигун OM642). Стійкість до високих температур.",
    specs: [
      { label: "Двигун", value: "OM642 3.0 CDI" },
      { label: "Матеріал", value: "Металопластик" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["3.0 CDI"] },
    ],
    rating: 4.6,
    reviewCount: 15,
    deliveryDays: 1,
    tags: ["прокладка", "колектор", "elring"],
  },
  {
    id: "sp-055",
    slug: "08146-febi-hub-bearing",
    name: "Підшипник маточини передній Febi Sprinter/VW LT",
    nameUK: "Підшипник маточини",
    brand: "Febi Bilstein",
    sku: "08146",
    category: "suspension",
    subcategory: "bearings",
    vehicles: ["mercedes-sprinter"],
    price: 1050,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.mec("right")],
    description: "Підшипник маточини передньої осі Febi для Mercedes 410 / Sprinter / VW LT 96-. Клас точності P6, суцільний сепаратор.",
    specs: [
      { label: "Вісь", value: "Передня" },
      { label: "Клас точності", value: "P6" },
      { label: "Тип", value: "Дворядний" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 19,
    deliveryDays: 2,
    tags: ["підшипник", "маточина", "підвіска"],
  },
  {
    id: "sp-056",
    slug: "713667050-fag-hub-bearing-vito",
    name: "Підшипник маточини FAG Vito W638 96-",
    nameUK: "Підшипник маточини",
    brand: "FAG",
    sku: "713667050",
    category: "suspension",
    subcategory: "bearings",
    vehicles: ["mercedes-vito"],
    price: 1266,
    currency: "UAH",
    inStock: true,
    stockCount: 3,
    images: [P.gar("entropy")],
    description: "Підшипник маточини колеса FAG (передній/задній) для Mercedes Vito W638 1996-. Преміум якість FAG Schaeffler.",
    specs: [
      { label: "Осі", value: "Передня / Задня" },
      { label: "Клас точності", value: "P5" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["всі"] },
    ],
    rating: 4.8,
    reviewCount: 37,
    deliveryDays: 2,
    tags: ["підшипник", "маточина", "fag", "vito"],
  },
  {
    id: "sp-057",
    slug: "0267250035-meyle-shock-sprinter",
    name: "Амортизатор задній Meyle Sprinter 901-903/VW LT",
    nameUK: "Амортизатор задній",
    brand: "Meyle",
    sku: "0267250035",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter"],
    price: 1352,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.mec("entropy")],
    description: "Амортизатор задній Meyle для Mercedes Sprinter 901/902/903 / VW LT 28. Газомаслянний, подовжений ресурс.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Тип", value: "Газомаслянний" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1995–2006", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 21,
    deliveryDays: 2,
    tags: ["амортизатор", "підвіска", "meyle"],
  },
  {
    id: "sp-058",
    slug: "319878-sachs-shock-sprinter-rear",
    name: "Амортизатор задній Sachs Sprinter 412-416",
    nameUK: "Амортизатор задній",
    brand: "Sachs",
    sku: "319878",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter"],
    price: 2375,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.prt("center")],
    description: "Амортизатор задній масляний посилений Sachs для Sprinter 412-416. Жовтий. Для важко навантаженого комерційного транспорту.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Тип", value: "Масляний (посилений)" },
      { label: "Для вантажу", value: "До 5 т" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.7,
    reviewCount: 18,
    deliveryDays: 2,
    tags: ["амортизатор", "підвіска", "sachs"],
  },
  {
    id: "sp-059",
    slug: "314606-sachs-shock-crafter-50",
    name: "Амортизатор задній Sachs Sprinter 509-519/Crafter 50",
    nameUK: "Амортизатор задній",
    brand: "Sachs",
    sku: "314606",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter", "vw-crafter"],
    price: 2616,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.prt("focalpoint")],
    description: "Амортизатор задній Sachs для Sprinter 509-519 / VW Crafter 50 3.5 т. Підвищена надійність для важких робочих умов.",
    specs: [
      { label: "Вісь", value: "Задня" },
      { label: "Тип", value: "Газомаслянний" },
      { label: "Застосування", value: "Важкий варіант (3.5 т)" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "2006–2018", engines: ["всі"] },
      { vehicle: "VW Crafter", years: "2006–2016", engines: ["всі"] },
    ],
    rating: 4.8,
    reviewCount: 26,
    deliveryDays: 2,
    tags: ["амортизатор", "підвіска", "sachs", "crafter"],
  },
  {
    id: "sp-060",
    slug: "jgm1004t-trw-shock-sprinter",
    name: "Амортизатор передній TRW Sprinter/VW LT (короткий)",
    nameUK: "Амортизатор передній",
    brand: "TRW",
    sku: "JGM1004T",
    category: "suspension",
    subcategory: "shocks",
    vehicles: ["mercedes-sprinter"],
    price: 2678,
    currency: "UAH",
    inStock: true,
    stockCount: 2,
    images: [P.prt("faces")],
    description: "Амортизатор передній TRW для Sprinter / VW LT (короткий варіант, стиснуте 319.5 мм). Газомаслянний.",
    specs: [
      { label: "Вісь", value: "Передня" },
      { label: "Варіант", value: "Короткий (319.5 мм)" },
      { label: "Тип", value: "Газомаслянний" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 13,
    deliveryDays: 2,
    tags: ["амортизатор", "підвіска", "trw", "sprinter"],
  },
  {
    id: "sp-061",
    slug: "02-23-034-trucktec-clutch-cylinder",
    name: "Циліндр зчеплення робочий Trucktec Sprinter/VW LT",
    nameUK: "Робочий циліндр зчеплення",
    brand: "Trucktec",
    sku: "02.23.034",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["mercedes-sprinter"],
    price: 865,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.mec("faces")],
    description: "Робочий циліндр зчеплення Trucktec для Sprinter / VW LT 96-. Діаметр 22 мм. В комплекті з монтажним комплектом.",
    specs: [
      { label: "Тип", value: "Робочий (slave)" },
      { label: "Діаметр", value: "22 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.5,
    reviewCount: 9,
    deliveryDays: 2,
    tags: ["зчеплення", "циліндр", "трансмісія"],
  },
  {
    id: "sp-062",
    slug: "41212-abs-clutch-master",
    name: "Головний циліндр зчеплення A.B.S. Sprinter/Vito",
    nameUK: "Головний циліндр зчеплення",
    brand: "A.B.S.",
    sku: "41212",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["mercedes-sprinter", "mercedes-vito"],
    price: 903,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.gar("faces")],
    description: "Головний циліндр зчеплення A.B.S. для Mercedes Sprinter/Vito 96-. Стандартний діаметр 19 мм.",
    specs: [
      { label: "Тип", value: "Головний (master)" },
      { label: "Діаметр", value: "19 мм" },
    ],
    compatibility: [
      { vehicle: "Mercedes Sprinter", years: "1996–2006", engines: ["всі"] },
      { vehicle: "Mercedes Vito", years: "1996–2006", engines: ["всі"] },
    ],
    rating: 4.6,
    reviewCount: 17,
    deliveryDays: 2,
    tags: ["зчеплення", "циліндр", "трансмісія"],
  },
  {
    id: "sp-063",
    slug: "0986486544-bosch-clutch-cylinder-vito",
    name: "Робочий циліндр зчеплення Bosch Vito W638",
    nameUK: "Робочий циліндр зчеплення",
    brand: "Bosch",
    sku: "0986486544",
    category: "transmission",
    subcategory: "clutch",
    vehicles: ["mercedes-vito"],
    price: 1952,
    currency: "UAH",
    inStock: true,
    stockCount: 1,
    images: [P.wsh("focalpoint")],
    description: "Робочий циліндр зчеплення Bosch для Mercedes Vito W638 96-03. Діаметр 22.2 мм. Оригінальна якість Bosch.",
    specs: [
      { label: "Тип", value: "Робочий (slave)" },
      { label: "Діаметр", value: "22.2 мм" },
      { label: "Двигун", value: "OM611 2.2 CDI" },
    ],
    compatibility: [
      { vehicle: "Mercedes Vito", years: "1996–2003", engines: ["2.2 CDI", "2.3"] },
    ],
    rating: 4.7,
    reviewCount: 14,
    deliveryDays: 2,
    tags: ["зчеплення", "циліндр", "bosch", "vito"],
  },
];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string, subcategory?: string): Product[] {
  return products.filter(
    (p) =>
      p.category === category &&
      (!subcategory || p.subcategory === subcategory)
  );
}

export function getProductsByVehicle(vehicleSlug: string): Product[] {
  return products.filter((p) => p.vehicles.includes(vehicleSlug));
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isBestseller || p.isNew).slice(0, 8);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.nameUK.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.sku.toLowerCase().replace(/[\s\-\.\/]/g, "").includes(q.replace(/[\s\-\.\/]/g, "")) ||
      (p.oem ?? []).some((o) => o.toLowerCase().includes(q)) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.description.toLowerCase().includes(q)
  );
}

export function getAllProducts(): Product[] {
  return products;
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(
      (p) =>
        p.id !== product.id &&
        (p.category === product.category ||
          p.vehicles.some((v) => product.vehicles.includes(v)))
    )
    .slice(0, limit);
}
