/**
 * Every string, price and image on the studio route lives here.
 *
 * The brand below is a placeholder identity — replace `STUDIO`, the service
 * prices and the `src` values with the real studio's assets and nothing in the
 * component layer needs to change. Artwork is generated by
 * `scripts/generate-studio-art.mjs`; swapping in photography is a matter of
 * pointing `src` at the new files and keeping `width` / `height` accurate so
 * the reserved aspect ratio stays correct and no layout shift occurs.
 */

export type Media = {
  src: string;
  width: number;
  height: number;
  alt: string;
};

export const STUDIO = {
  name: "ATELIER IVOIRE",
  mark: "IVOIRE",
  tagline: "NAIL STUDIO / CREATIVE BEAUTY",
  label: "NAIL STUDIO · EST. 2024",
  city: "Berlin",
  address: ["Torstraße 114", "10119 Berlin, DE"],
  email: "studio@atelier-ivoire.com",
  phone: "+49 30 1234 5678",
  instagram: "@atelier.ivoire",
  instagramUrl: "https://instagram.com",
  hours: ["Tue — Fri  10:00 — 20:00", "Sat  10:00 — 18:00"],
} as const;

export const NAV_ITEMS = [
  { index: "01", label: "Home", id: "home", media: art("hero-primary", 1400, 1750, "Almond nails in a soft nude lacquer") },
  { index: "02", label: "Services", id: "services", media: art("service-manicure", 1200, 1500, "A five-finger study in nude lacquer") },
  { index: "03", label: "Work", id: "work", media: art("work-09", 1000, 1250, "Deep cherry lacquer on rounded nails") },
  { index: "04", label: "About", id: "about", media: art("about-01", 1100, 1400, "Pearl lacquer catching the light") },
  { index: "05", label: "Contact", id: "contact", media: art("work-03", 1000, 1000, "Blush oval nails on a rose ground") },
] as const;

export type Service = {
  index: string;
  title: string;
  sub: string;
  copy: string;
  duration: string;
  price: string;
  media: Media;
  tint: string;
};

export const SERVICES: Service[] = [
  {
    index: "01",
    title: "Manicure",
    sub: "Structure & finish",
    copy: "Dry cuticle work, hand-filed shaping and a finish calibrated to read as skin rather than product.",
    duration: "60 MIN",
    price: "from €45",
    media: art("service-manicure", 1200, 1500, "Five nude-lacquered nails in a soft fan"),
    tint: "#EFE9E0",
  },
  {
    index: "02",
    title: "Pedicure",
    sub: "The long ritual",
    copy: "A slow, warm-water treatment. Callus refinement, contour filing, and a lacquer laid in three thin coats.",
    duration: "75 MIN",
    price: "from €60",
    media: art("service-pedicure", 1200, 1500, "Oval nails finished in ivory"),
    tint: "#E8E5DF",
  },
  {
    index: "03",
    title: "Nail Art",
    sub: "Commissioned detail",
    copy: "Hand-painted line work, chrome transfer and micro-inlay. Drawn on the nail, never printed onto it.",
    duration: "45 MIN",
    price: "from €35",
    media: art("service-nailart", 1200, 1500, "Mixed rosewood, chrome and pearl lacquers"),
    tint: "#F0E5E0",
  },
  {
    index: "04",
    title: "Gel / BIAB",
    sub: "Builder in a bottle",
    copy: "A flexible apex built over the natural plate. Weeks of wear with none of the weight of an extension.",
    duration: "90 MIN",
    price: "from €55",
    media: art("service-gel", 1200, 1500, "Square nails in a warm clay lacquer"),
    tint: "#EDE4D9",
  },
  {
    index: "05",
    title: "Signature Care",
    sub: "The full appointment",
    copy: "Hands and feet, treated as one. Two hours, one artist, and an espresso finish in matte or high gloss.",
    duration: "120 MIN",
    price: "from €120",
    media: art("service-signature", 1200, 1500, "Coffin nails in a deep espresso lacquer"),
    tint: "#E4DED6",
  },
];

export type Work = {
  no: string;
  title: string;
  category: string;
  media: Media;
  span: "tall" | "wide" | "square" | "hero" | "narrow";
};

export const WORKS: Work[] = [
  { no: "024", title: "Chrome / Nude", category: "Gel · Almond", media: art("work-01", 900, 1200, "Chrome-finished almond nails"), span: "tall" },
  { no: "031", title: "Noir Ballerina", category: "Extension · Coffin", media: art("work-02", 1200, 900, "Five coffin nails in noir and chrome"), span: "wide" },
  { no: "007", title: "Blush Study", category: "BIAB · Oval", media: art("work-03", 1000, 1000, "Blush lacquer on oval nails"), span: "square" },
  { no: "042", title: "Pearl Square", category: "Gel · Square", media: art("work-04", 900, 1350, "Pearl lacquer on square nails"), span: "narrow" },
  { no: "016", title: "Clay Editorial", category: "Signature · Almond", media: art("work-05", 1200, 1500, "Warm clay lacquer across five nails"), span: "hero" },
  { no: "055", title: "Ivory Gradient", category: "Manicure · Almond", media: art("work-06", 1400, 900, "A gradient of ivory, nude and clay lacquers"), span: "wide" },
  { no: "063", title: "Olive Matte", category: "Nail Art · Oval", media: art("work-07", 900, 1200, "Muted olive lacquer on oval nails"), span: "tall" },
  { no: "071", title: "Liquid Chrome", category: "Press-on · Coffin", media: art("work-08", 1000, 1400, "A single chrome coffin nail on espresso"), span: "narrow" },
  { no: "088", title: "Cherry Lacquer", category: "Gel · Rounded", media: art("work-09", 1000, 1250, "Deep cherry lacquer, high gloss"), span: "tall" },
];

export const STATS = [
  { index: "01", value: 500, suffix: "+", label: "Clients" },
  { index: "02", value: 4.9, suffix: "", label: "Average rating", decimals: 1 },
  { index: "03", value: 5, suffix: "+", label: "Years experience" },
  { index: "04", value: 100, suffix: "%", label: "Attention to detail" },
] as const;

export const TESTIMONIALS = [
  {
    quote: "The most beautiful nails I've ever had.",
    name: "Marta K.",
    meta: "Signature Care · Third year",
  },
  {
    quote: "Two hours that feel like a week away.",
    name: "Elena V.",
    meta: "Gel / BIAB · Monthly",
  },
  {
    quote: "Nobody believes they are not my own.",
    name: "Sophie R.",
    meta: "Extensions · Since 2022",
  },
  {
    quote: "Precision I have not found anywhere else in the city.",
    name: "Ada L.",
    meta: "Nail Art · Commissioned",
  },
] as const;

export const MARQUEE_WORDS = [
  "NAILS",
  "BEAUTY",
  "ART",
  "CARE",
  "DETAIL",
] as const;

export const ABOUT_MEDIA = {
  primary: art("about-01", 1100, 1400, "Pearl lacquer catching a soft studio light"),
  secondary: art("about-02", 1100, 800, "A close study of nude lacquer and warm skin"),
};

export const HERO_MEDIA = {
  primary: art("hero-primary", 1400, 1750, "Four almond nails finished in a soft nude lacquer"),
  secondary: art("hero-secondary", 1000, 1400, "Coffin nails in a deep noir lacquer"),
};

function art(name: string, width: number, height: number, alt: string): Media {
  return { src: `/studio/art/${name}.svg`, width, height, alt };
}
