import type { Product } from "./types";

/**
 * The catalogue. Prices are in euro cents, VAT included, as shown on the shelf.
 * Tea carries 6 % Belgian VAT; objects and vouchers carry 21 %.
 *
 * Every passport field is either true or explicitly null. Where a garden is
 * unknown we say so in `unknown` rather than inventing a mountain.
 */
export const products: Product[] = [
  // ─── Sheng pu-erh ──────────────────────────────────────────────────────────
  {
    slug: "bingdao-gushu-2021",
    name: "Bingdao Gushu",
    hanzi: "冰岛古树",
    pinyin: "Bīngdǎo Gǔshù",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["caneSugar", "orchid", "coolMint", "apricot", "wetStone"],
    vat: 6,
    vaultEligible: true,
    featured: true,
    passport: {
      regionId: "lincang",
      altitudeM: 1750,
      harvestYear: 2021,
      harvestMonth: 4,
      producer: { nl: "Coöperatie Bingdao Laozhai", en: "Bingdao Laozhai cooperative" },
      cultivar: "Mengku Da Ye",
      oxidation: 8,
      roast: "none",
      storage: {
        nl: "Droog bewaren bij 60–70 % relatieve vochtigheid, weg van geur.",
        en: "Keep dry at 60–70 % relative humidity, away from anything that smells.",
      },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 12 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 3, resteeps: 2 },
    variants: [
      { sku: "WY-SH-BG21-25", grams: 25, price: 3900, stock: 24 },
      { sku: "WY-SH-BG21-357", grams: 357, price: 42000, stock: 6, label: { nl: "cake 357 g", en: "cake 357 g" } },
    ],
    copy: {
      tagline: {
        nl: "Lincang, 1750 m, oude bomen van het dorp Laozhai.",
        en: "Lincang, 1750 m, old trees from the village of Laozhai.",
      },
      description: {
        nl: "Bingdao is duur omdat het dorp klein is en iedereen dat weet. Wat je ervoor terugkrijgt is een zoetheid die niet op suiker lijkt maar op ijssuiker: koel, helder, en ze blijft minutenlang achter in de keel. De bitterheid in de eerste twee infusies is er, maar ze zakt sneller weg dan bij welke andere sheng in dit rek ook. Wij kochten twee cakes van deze partij; wat u hier ziet is wat er is.",
        en: "Bingdao is expensive because the village is small and everyone knows it. What you get back is a sweetness that is not like sugar but like rock sugar: cool, clear, and it stays in the throat for minutes. The bitterness in the first two infusions is there, but it drops away faster than in any other sheng on this shelf. We bought two cakes of this batch; what you see here is what there is.",
      },
    },
    reviews: [
      { author: "Wouter D.", city: "Gent", rating: 5, date: "2026-05-12", body: { nl: "De achtste infusie was nog steeds de moeite. Dat had ik bij geen enkele sheng eerder.", en: "The eighth infusion was still worth it. I had never had that with any sheng before." } },
      { author: "Marieke V.", city: "Leuven", rating: 5, date: "2026-03-02", body: { nl: "Duur, en ik zou het opnieuw doen. De koelte in de keel is echt geen verkooppraat.", en: "Expensive, and I would do it again. The coolness in the throat really is not sales talk." } },
      { author: "Tom B.", city: "Antwerpen", rating: 4, date: "2026-01-20", body: { nl: "Prachtig, maar je moet er tijd voor nemen. In een mok werkt dit niet.", en: "Beautiful, but you have to make time for it. This does not work in a mug." } },
    ],
    related: ["yiwu-zhengshan-2018", "jingmai-autumn-2022", "lao-mane-bitter-2020"],
  },
  {
    slug: "yiwu-zhengshan-2018",
    name: "Yiwu Zhengshan",
    hanzi: "易武正山",
    pinyin: "Yìwǔ Zhèngshān",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["honey", "magnolia", "longan", "cedar", "caneSugar"],
    vat: 6,
    vaultEligible: true,
    passport: {
      regionId: "yiwu",
      altitudeM: 1350,
      harvestYear: 2018,
      harvestMonth: 4,
      producer: { nl: "Familie Li, Mahei", en: "The Li family, Mahei" },
      cultivar: "Yiwu Da Ye",
      oxidation: 10,
      roast: "none",
      storage: {
        nl: "Acht jaar droog opgeslagen in Kunming. Verder rijpen kan gerust.",
        en: "Eight years of dry storage in Kunming. It can go on ageing without worry.",
      },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 11 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 3, resteeps: 2 },
    variants: [
      { sku: "WY-SH-YW18-25", grams: 25, price: 1900, stock: 40 },
      { sku: "WY-SH-YW18-357", grams: 357, price: 19500, stock: 11, label: { nl: "cake 357 g", en: "cake 357 g" } },
    ],
    copy: {
      tagline: { nl: "Yiwu, 1350 m, acht jaar droge opslag in Kunming.", en: "Yiwu, 1350 m, eight years of dry Kunming storage." },
      description: {
        nl: "Als iemand vraagt waar hij moet beginnen met sheng, is dit het antwoord. Yiwu heeft geen scherpe randen: het blad geeft honing en een beetje magnolia, en de acht jaar hebben de jonge groene toon eruit gehaald zonder dat er al hout voor in de plaats is gekomen. Een cake om te drinken én weg te leggen, wat zelden samengaat.",
        en: "When someone asks where to start with sheng, this is the answer. Yiwu has no sharp edges: the leaf gives honey and a little magnolia, and the eight years have taken out the young green note without yet putting wood in its place. A cake to drink and to put away, which rarely goes together.",
      },
    },
    reviews: [
      { author: "Sanne K.", city: "Brugge", rating: 5, date: "2026-04-18", body: { nl: "Mijn eerste hele cake. Na drie maanden is er al verschil te proeven.", en: "My first whole cake. After three months you can already taste a difference." } },
      { author: "Peter M.", city: "Hasselt", rating: 4, date: "2026-02-08", body: { nl: "Zacht en breed. Wie bitterheid zoekt, moet elders zijn.", en: "Soft and broad. If you are after bitterness, look elsewhere." } },
    ],
    related: ["bingdao-gushu-2021", "jingmai-autumn-2022", "set-puerh-verticaal"],
  },
  {
    slug: "lao-mane-bitter-2020",
    name: "Lao Man'e Bitter",
    hanzi: "老曼峨苦茶",
    pinyin: "Lǎo Mǎn'é Kǔchá",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["betelNut", "bamboo", "caneSugar", "coolMint"],
    vat: 6,
    passport: {
      regionId: "laomane",
      altitudeM: 1650,
      harvestYear: 2020,
      harvestMonth: 4,
      producer: { nl: "Bulang-collectief Lao Man'e", en: "Lao Man'e Bulang collective" },
      cultivar: "Bulang Da Ye, bittere variëteit",
      oxidation: 8,
      roast: "none",
      storage: { nl: "Droog, 60–70 % RV. Bitterheid neemt af met de jaren.", en: "Dry, 60–70 % RH. The bitterness recedes with the years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 6, celsius: 95, rinseSeconds: 5, firstSeconds: 8, incrementSeconds: 5, infusions: 10 },
    western: { grams: 2, ml: 300, celsius: 85, minutes: 2, resteeps: 2 },
    variants: [{ sku: "WY-SH-LM20-25", grams: 25, price: 1400, stock: 33 }],
    copy: {
      tagline: { nl: "De bittere variëteit van Bulang, 1650 m, oogst 2020.", en: "The bitter Bulang varietal, 1650 m, 2020 harvest." },
      description: {
        nl: "Deze thee is niet aardig. De eerste slok is ronduit bitter, en dat is de bedoeling: bij Lao Man'e gaat het om wat daarna komt. Tien tot vijftien seconden later kantelt hij en blijft er een zoetheid achter die breder is dan de bitterheid ooit was. Wie dat nooit heeft meegemaakt, moet het één keer proberen; wie het kent, koopt hier per cake. Zet hem kort en met minder blad dan u gewend bent.",
        en: "This tea is not friendly. The first sip is flatly bitter, and that is the point: with Lao Man'e it is about what comes after. Ten to fifteen seconds later it turns, and leaves a sweetness broader than the bitterness ever was. If you have never had that happen, try it once; if you know it, you buy it by the cake. Steep it short and with less leaf than you are used to.",
      },
    },
    related: ["bingdao-gushu-2021", "yiwu-zhengshan-2018"],
  },
  {
    slug: "jingmai-autumn-2022",
    name: "Jingmai Autumn",
    hanzi: "景迈秋茶",
    pinyin: "Jǐngmài Qiūchá",
    category: "sheng",
    form: "loose",
    liquor: "sheng",
    caffeine: "medium",
    notes: ["orchid", "honeysuckle", "honey", "hay"],
    vat: 6,
    passport: {
      regionId: "jingmai",
      altitudeM: 1400,
      harvestYear: 2022,
      harvestMonth: 10,
      producer: { nl: "Bergdorp Nuogang", en: "Nuogang mountain village" },
      cultivar: "Jingmai Da Ye",
      oxidation: 8,
      roast: "none",
      storage: { nl: "Los blad, luchtdicht en donker. Drink binnen drie jaar.", en: "Loose leaf, airtight and dark. Drink within three years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 6, celsius: 92, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 9 },
    western: { grams: 3, ml: 300, celsius: 88, minutes: 2, resteeps: 2 },
    variants: [{ sku: "WY-SH-JM22-50", grams: 50, price: 2200, stock: 28 }],
    copy: {
      tagline: { nl: "Herfstpluk uit de bostuinen van Jingmai, 1400 m.", en: "Autumn picking from the Jingmai forest gardens, 1400 m." },
      description: {
        nl: "Herfstthee heeft minder body dan de voorjaarspluk en meer geur, en op Jingmai is die geur het punt. De orchidee die iedereen aan deze berg toeschrijft zit er echt in, al ruikt u hem beter in de lege kan dan in het kopje. Los blad, dus niets om weg te leggen: dit is thee voor de komende twee jaar.",
        en: "Autumn tea has less body than the spring picking and more scent, and on Jingmai that scent is the point. The orchid everyone attributes to this mountain really is there, though you smell it better in the empty pitcher than in the cup. Loose leaf, so nothing to put away: this is tea for the next two years.",
      },
    },
    related: ["yiwu-zhengshan-2018", "mi-lan-xiang-dan-cong"],
  },

  // ─── Shou pu-erh ───────────────────────────────────────────────────────────
  {
    slug: "menghai-gong-ting-2016",
    name: "Menghai Gong Ting",
    hanzi: "宫廷普洱",
    pinyin: "Gōngtíng Pǔ'ěr",
    category: "shou",
    form: "loose",
    liquor: "shou",
    caffeine: "medium",
    notes: ["darkChocolate", "driedDate", "forestFloor", "cream"],
    vat: 6,
    featured: true,
    passport: {
      regionId: "menghai",
      altitudeM: 1300,
      harvestYear: 2016,
      harvestMonth: 5,
      producer: { nl: "Menghai Tea Factory", en: "Menghai Tea Factory" },
      cultivar: "Menghai Da Ye",
      oxidation: null,
      fermentation: {
        nl: "Wo dui, natte stapeling van 45 dagen, daarna tien jaar drooggerijpt.",
        en: "Wo dui, a 45-day wet pile, then ten years of dry ageing.",
      },
      roast: "none",
      storage: { nl: "Droog en luchtig. Shou heeft geen verdere rijping meer nodig.", en: "Dry and airy. Shou needs no further ageing." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 8, celsius: 100, rinseSeconds: 8, firstSeconds: 10, incrementSeconds: 5, infusions: 12 },
    western: { grams: 4, ml: 300, celsius: 100, minutes: 4, resteeps: 3 },
    variants: [{ sku: "WY-SU-GT16-50", grams: 50, price: 2600, stock: 35 }],
    copy: {
      tagline: { nl: "Gong ting, de fijnste knopgraad, tien jaar nagerijpt.", en: "Gong ting, the finest bud grade, ten years of ageing." },
      description: {
        nl: "Gong ting betekent hofthee en slaat op de graad, niet op de herkomst: alleen de kleinste knoppen gaan mee. Het aftreksel is bijna zwart en volledig helder, en er zit geen spoor van de kelderlucht die jonge shou vaak heeft — die is er in tien jaar uitgetrokken. Dit is de thee die wij zelf 's ochtends zetten als het buiten grijs is.",
        en: "Gong ting means palace tea and refers to the grade, not the origin: only the smallest buds go in. The liquor is nearly black and completely clear, and there is no trace of the cellar note young shou often has — ten years took that out. This is the tea we brew ourselves on a grey morning.",
      },
    },
    reviews: [
      { author: "Els D.", city: "Kortrijk", rating: 5, date: "2026-06-01", body: { nl: "Geen modderige smaak, wat ik van pu-erh gewend was. Dit is iets anders.", en: "None of the muddy taste I was used to from pu-erh. This is something else." } },
      { author: "Jonas P.", city: "Mechelen", rating: 5, date: "2026-04-03", body: { nl: "Twaalf infusies gehaald en toen pas gestopt omdat het bedtijd was.", en: "Got twelve infusions in and only stopped because it was bedtime." } },
    ],
    related: ["golden-bud-ripe-2019", "lao-cha-tou-2015", "xiaguan-tuocha"],
  },
  {
    slug: "golden-bud-ripe-2019",
    name: "Golden Bud Ripe",
    hanzi: "金芽熟普",
    pinyin: "Jīnyá Shúpǔ",
    category: "shou",
    form: "loose",
    liquor: "shou",
    caffeine: "medium",
    notes: ["brownSugar", "driedDate", "mushroom", "malt"],
    vat: 6,
    passport: {
      regionId: "menghai",
      altitudeM: 1200,
      harvestYear: 2019,
      harvestMonth: 6,
      producer: { nl: "Haiwan-werkplaats, Menghai", en: "Haiwan workshop, Menghai" },
      cultivar: "Menghai Da Ye",
      oxidation: null,
      fermentation: { nl: "Wo dui, 50 dagen, lichte fermentatiegraad.", en: "Wo dui, 50 days, at a light fermentation level." },
      roast: "none",
      storage: { nl: "Droog en luchtig, weg van koffie en kruiden.", en: "Dry and airy, away from coffee and spices." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 8, celsius: 100, rinseSeconds: 8, firstSeconds: 10, incrementSeconds: 5, infusions: 10 },
    western: { grams: 4, ml: 300, celsius: 100, minutes: 4, resteeps: 3 },
    variants: [{ sku: "WY-SU-GB19-50", grams: 50, price: 1800, stock: 52 }],
    copy: {
      tagline: { nl: "Lichte fermentatie, veel gouden knop, oogst 2019.", en: "Lightly fermented, plenty of golden bud, 2019 harvest." },
      description: {
        nl: "De begaanbare shou. Licht gefermenteerd, dus zoeter en minder aards dan wat de meeste mensen van pu-erh kennen, met een duidelijke bruine-suikertoon in de derde en vierde infusie. Vergeeft het als u hem te lang laat staan, wat hem bruikbaar maakt op een dag waarop u niet aan de kan denkt.",
        en: "The approachable shou. Lightly fermented, so sweeter and less earthy than what most people know pu-erh to be, with a clear brown sugar note in the third and fourth infusion. It forgives you for leaving it too long, which makes it usable on a day when you are not thinking about the pot.",
      },
    },
    related: ["menghai-gong-ting-2016", "lao-cha-tou-2015"],
  },
  {
    slug: "lao-cha-tou-2015",
    name: "Lao Cha Tou",
    hanzi: "老茶头",
    pinyin: "Lǎo Chá Tóu",
    category: "shou",
    form: "loose",
    liquor: "shou",
    caffeine: "medium",
    notes: ["darkChocolate", "driedDate", "dampEarth", "caramel"],
    vat: 6,
    passport: {
      regionId: "menghai",
      altitudeM: 1300,
      harvestYear: 2015,
      harvestMonth: 5,
      producer: { nl: "Menghai, partij 1501", en: "Menghai, batch 1501" },
      cultivar: "Menghai Da Ye",
      oxidation: null,
      fermentation: { nl: "Klonters die tijdens de wo dui aan elkaar bakten en apart zijn uitgezocht.", en: "Nuggets that caked together during the wo dui and were sorted out separately." },
      roast: "none",
      storage: { nl: "Droog. De klonters houden zichzelf goed.", en: "Dry. The nuggets keep themselves well." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 9, celsius: 100, rinseSeconds: 10, firstSeconds: 15, incrementSeconds: 8, infusions: 14 },
    western: { grams: 5, ml: 300, celsius: 100, minutes: 5, resteeps: 4 },
    variants: [{ sku: "WY-SU-LCT15-50", grams: 50, price: 2100, stock: 21 }],
    copy: {
      tagline: { nl: "Theekoppen: klonters uit de fermentatiestapel van 2015.", en: "Tea heads: nuggets from the 2015 fermentation pile." },
      description: {
        nl: "Tijdens het fermenteren plakken sommige bladeren met pectine aan elkaar tot harde klonters. Die werden vroeger weggegooid; nu zijn ze duurder dan de rest van de partij, want ze geven water veel trager af. Reken op veertien infusies en een dikte in de mond die los blad niet haalt. Laat de klonters heel, ze vallen vanzelf open.",
        en: "During fermentation some leaves stick together with pectin into hard nuggets. They used to be thrown away; now they cost more than the rest of the batch, because they give up their liquor far more slowly. Expect fourteen infusions and a thickness in the mouth loose leaf does not reach. Leave the nuggets whole, they open by themselves.",
      },
    },
    related: ["menghai-gong-ting-2016", "golden-bud-ripe-2019"],
  },
  {
    slug: "xiaguan-tuocha",
    name: "Xiaguan Tuocha",
    hanzi: "下关沱茶",
    pinyin: "Xiàguān Tuóchá",
    category: "shou",
    form: "tuocha",
    liquor: "shou",
    caffeine: "medium",
    notes: ["charcoal", "dampEarth", "driedDate", "tobacco"],
    vat: 6,
    passport: {
      regionId: "xiaguan",
      altitudeM: 1900,
      harvestYear: 2019,
      harvestMonth: 3,
      producer: { nl: "Xiaguan Tea Factory, Dali", en: "Xiaguan Tea Factory, Dali" },
      cultivar: "Blend uit Lincang en Dali",
      oxidation: null,
      fermentation: { nl: "Wo dui, middelzware graad; daarna strak geperst tot een nest van 100 g.", en: "Wo dui at a medium level; then pressed tight into a 100 g nest." },
      roast: "none",
      storage: { nl: "Droog en hoog opgeslagen in Dali, wat het strakke karakter verklaart.", en: "Stored dry and high in Dali, which explains the tight character." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 100, rinseSeconds: 10, firstSeconds: 10, incrementSeconds: 5, infusions: 10 },
    western: { grams: 4, ml: 300, celsius: 100, minutes: 4, resteeps: 3 },
    variants: [{ sku: "WY-SU-XG-100", grams: 100, price: 1600, stock: 44, label: { nl: "tuocha 100 g", en: "tuocha 100 g" } }],
    copy: {
      tagline: { nl: "Het klassieke nest van 100 g uit Dali, oogst 2019.", en: "The classic 100 g nest from Dali, 2019 harvest." },
      description: {
        nl: "De tuocha die in China in elke kruidenierszaak ligt, en die daarom vaak wordt onderschat. Xiaguan perst harder dan de fabrieken in Banna, dus u hebt een priem nodig en de eerste infusie komt traag op gang. Daarna staat er een strakke, rokerige shou zonder franje. De goedkoopste manier om te leren hoe geperste thee zich gedraagt.",
        en: "The tuocha that sits in every grocery shop in China, and is therefore often underrated. Xiaguan presses harder than the Banna factories, so you need a pick and the first infusion is slow to start. After that you have a tight, smoky shou with no frills. The cheapest way to learn how pressed tea behaves.",
      },
    },
    related: ["golden-bud-ripe-2019", "menghai-gong-ting-2016"],
  },

  // ─── Oolong ────────────────────────────────────────────────────────────────
  {
    slug: "da-hong-pao-zhengyan",
    name: "Da Hong Pao Zhengyan",
    hanzi: "正岩大红袍",
    pinyin: "Zhèngyán Dà Hóng Páo",
    category: "oolong",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["charcoal", "orchid", "wetStone", "driedFig", "darkChocolate"],
    vat: 6,
    featured: true,
    passport: {
      regionId: "wuyi",
      altitudeM: 650,
      harvestYear: 2025,
      harvestMonth: 5,
      producer: { nl: "Familie Chen, Huiyuan-kloof", en: "The Chen family, Huiyuan gorge" },
      cultivar: "Qi Dan en Bei Dou, samengesteld door de maker",
      oxidation: 55,
      roast: "heavy",
      storage: { nl: "Luchtdicht, donker. Na een zware rooster is een half jaar rust een verbetering.", en: "Airtight, dark. After a heavy roast, half a year of rest is an improvement." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 8, celsius: 100, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 9 },
    western: { grams: 4, ml: 300, celsius: 95, minutes: 3, resteeps: 3 },
    variants: [{ sku: "WY-OO-DHP-25", grams: 25, price: 3400, stock: 18 }],
    copy: {
      tagline: { nl: "Zhengyan, binnen het kerngebied: Huiyuan-kloof, 650 m.", en: "Zhengyan, inside the core area: Huiyuan gorge, 650 m." },
      description: {
        nl: "Zhengyan betekent dat de struiken binnen het beschermde rotsgebied staan, en dat is het enige wat het woord betekent — buiten dat gebied groeit dezelfde variëteit en heet ze ook Da Hong Pao. Wat u hier proeft is de zware houtskoolrooster, en daaronder, vanaf de derde infusie, de minerale klank waar het om begonnen is. Geduld: de eerste twee infusies zijn nog vooral vuur.",
        en: "Zhengyan means the bushes stand inside the protected rock area, and that is all the word means — outside that area the same varietal grows and is also called Da Hong Pao. What you taste here is the heavy charcoal roast, and beneath it, from the third infusion, the mineral ring the whole thing is about. Be patient: the first two infusions are still mostly fire.",
      },
    },
    reviews: [
      { author: "Bram S.", city: "Gent", rating: 5, date: "2026-05-28", body: { nl: "De rooster is stevig maar niet verbrand. Vanaf infusie drie klopt alles.", en: "The roast is firm but not burnt. From the third infusion everything falls into place." } },
      { author: "Lien H.", city: "Brussel", rating: 4, date: "2026-02-14", body: { nl: "Ik had eerst een goedkopere Da Hong Pao. Nu snap ik waar het verschil zit.", en: "I had a cheaper Da Hong Pao first. Now I understand where the difference is." } },
    ],
    related: ["rou-gui-cinnamon-rock", "shui-xian-lao-cong", "mi-lan-xiang-dan-cong"],
  },
  {
    slug: "rou-gui-cinnamon-rock",
    name: "Rou Gui",
    hanzi: "肉桂",
    pinyin: "Ròuguì",
    category: "oolong",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["cinnamon", "peach", "wetStone", "charcoal"],
    vat: 6,
    passport: {
      regionId: "wuyi",
      altitudeM: 600,
      harvestYear: 2025,
      harvestMonth: 5,
      producer: { nl: "Werkplaats Niulankeng", en: "Niulankeng workshop" },
      cultivar: "Rou Gui",
      oxidation: 50,
      roast: "medium",
      storage: { nl: "Luchtdicht en donker. Binnen twee jaar drinken.", en: "Airtight and dark. Drink within two years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 8, celsius: 100, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 8 },
    western: { grams: 4, ml: 300, celsius: 95, minutes: 3, resteeps: 3 },
    variants: [{ sku: "WY-OO-RG-25", grams: 25, price: 2400, stock: 26 }],
    copy: {
      tagline: { nl: "Wuyi, 600 m, middelzware rooster uit de Niulankeng-kloof.", en: "Wuyi, 600 m, medium roast from the Niulankeng gorge." },
      description: {
        nl: "Rou Gui betekent kaneel, en dat is geen aroma dat is toegevoegd maar een eigenschap van de variëteit: het zit in de geur van het droge blad en het komt terug in de afdronk. Deze is middelzwaar geroosterd, dus het fruit staat er nog naast — perzik, vooral in de tweede en derde infusie. Van alle yancha in dit rek is dit de meest directe.",
        en: "Rou gui means cinnamon, and that is not an added aroma but a property of the varietal: it is in the smell of the dry leaf and it comes back in the finish. This one is medium roasted, so the fruit still stands beside it — peach, especially in the second and third infusion. Of all the yancha on this shelf, this is the most direct.",
      },
    },
    related: ["da-hong-pao-zhengyan", "shui-xian-lao-cong"],
  },
  {
    slug: "shui-xian-lao-cong",
    name: "Shui Xian Lao Cong",
    hanzi: "老丛水仙",
    pinyin: "Lǎocóng Shuǐxiān",
    category: "oolong",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["oldWood", "orchid", "sandalwood", "caramel"],
    vat: 6,
    passport: {
      regionId: "wuyi",
      altitudeM: 550,
      harvestYear: 2024,
      harvestMonth: 5,
      producer: { nl: "Tuin Wuyuanjian, struiken van 68 jaar", en: "Wuyuanjian garden, bushes 68 years old" },
      cultivar: "Shui Xian",
      oxidation: 55,
      roast: "medium",
      storage: { nl: "Luchtdicht en donker; deze wint aan diepte in het tweede jaar.", en: "Airtight and dark; this one gains depth in its second year." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 8, celsius: 100, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 9 },
    western: { grams: 4, ml: 300, celsius: 95, minutes: 3, resteeps: 3 },
    variants: [{ sku: "WY-OO-SX-25", grams: 25, price: 2000, stock: 30 }],
    copy: {
      tagline: { nl: "Lao cong: struiken van 68 jaar, geverifieerd bij de tuin.", en: "Lao cong: bushes 68 years old, verified with the garden." },
      description: {
        nl: "Lao cong wordt op etiketten roekeloos gebruikt; hier hebben we de leeftijd bij de tuin nagevraagd en het antwoord staat hierboven. Oude Shui Xian smaakt naar mos en oud hout, met een sandelhouttoon die pas na de vijfde infusie helemaal open komt. Rustige thee, meer avond dan ochtend.",
        en: "Lao cong gets used recklessly on labels; here we asked the garden for the age and the answer is above. Old Shui Xian tastes of moss and old wood, with a sandalwood note that only opens fully after the fifth infusion. Quiet tea, more evening than morning.",
      },
    },
    related: ["da-hong-pao-zhengyan", "rou-gui-cinnamon-rock"],
  },
  {
    slug: "tie-guan-yin-anxi",
    name: "Tie Guan Yin",
    hanzi: "铁观音",
    pinyin: "Tiě Guānyīn",
    category: "oolong",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["orchid", "gardenia", "butter", "greenBean"],
    vat: 6,
    passport: {
      regionId: "anxi",
      altitudeM: 800,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Familie Wang, Xiping", en: "The Wang family, Xiping" },
      cultivar: "Tie Guan Yin",
      oxidation: 25,
      roast: "light",
      storage: { nl: "Koel en luchtdicht; deze stijl verliest geur binnen het jaar.", en: "Cool and airtight; this style loses its scent within the year." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 15, incrementSeconds: 8, infusions: 7 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 2, resteeps: 3 },
    variants: [{ sku: "WY-OO-TGY-50", grams: 50, price: 1900, stock: 47 }],
    copy: {
      tagline: { nl: "Voorjaarspluk 2026, Xiping, licht geoxideerd in de moderne stijl.", en: "Spring 2026 picking, Xiping, lightly oxidised in the modern style." },
      description: {
        nl: "Dit is de groene Tie Guan Yin waar Anxi sinds de jaren negentig op is overgestapt: 25 % oxidatie, nauwelijks geroosterd, en daardoor bijna zo bloemig als een parfum. Het aftreksel is lichtgroen, niet oranje — wie de oude, geroosterde stijl zoekt, vindt die hier niet. Drink hem dit jaar, niet volgend jaar.",
        en: "This is the green Tie Guan Yin Anxi switched to in the nineties: 25 % oxidation, barely roasted, and as a result almost as floral as a perfume. The liquor is pale green, not orange — if you are after the old roasted style, you will not find it here. Drink it this year, not next year.",
      },
    },
    related: ["ali-shan-high-mountain", "dong-ding"],
  },
  {
    slug: "mi-lan-xiang-dan-cong",
    name: "Mi Lan Xiang Dan Cong",
    hanzi: "蜜兰香单丛",
    pinyin: "Mì Lán Xiāng Dān Cōng",
    category: "oolong",
    form: "loose",
    liquor: "oolong",
    caffeine: "high",
    notes: ["honey", "orchid", "apricot", "charcoal"],
    vat: 6,
    featured: true,
    passport: {
      regionId: "fenghuang",
      altitudeM: 900,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Boomgaard Wudong, één boom van 40 jaar", en: "Wudong grove, a single 40-year-old tree" },
      cultivar: "Mi Lan Xiang",
      oxidation: 40,
      roast: "medium",
      storage: { nl: "Luchtdicht en donker, weg van warmte.", en: "Airtight and dark, away from heat." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 100, rinseSeconds: 3, firstSeconds: 8, incrementSeconds: 4, infusions: 10 },
    western: { grams: 3, ml: 300, celsius: 95, minutes: 2, resteeps: 3 },
    variants: [{ sku: "WY-OO-MLX-25", grams: 25, price: 2800, stock: 22 }],
    copy: {
      tagline: { nl: "Honing-orchidee uit Wudong, één boom, 900 m.", en: "Honey orchid from Wudong, a single tree, 900 m." },
      description: {
        nl: "Dan cong betekent enkele struik: het blad van één boom wordt apart geplukt en apart verwerkt, en daarom verschilt elke partij. Deze ruikt in het droge blad zo uitgesproken naar honing dat mensen denken dat er iets aan toegevoegd is. Dat is niet zo. Zet hem kort — acht seconden is echt genoeg — want dan cong wordt snel wrang.",
        en: "Dan cong means single bush: the leaf of one tree is picked and processed on its own, which is why every batch differs. The dry leaf of this one smells so pronouncedly of honey that people assume something was added. Nothing was. Steep it short — eight seconds really is enough — because dan cong turns astringent fast.",
      },
    },
    reviews: [
      { author: "Nele V.", city: "Gent", rating: 5, date: "2026-06-15", body: { nl: "De geur van het lege kopje is bijna het beste deel.", en: "The scent of the empty cup is almost the best part." } },
    ],
    related: ["da-hong-pao-zhengyan", "jingmai-autumn-2022"],
  },
  {
    slug: "dong-ding",
    name: "Dong Ding",
    hanzi: "凍頂烏龍",
    pinyin: "Dòngdǐng Wūlóng",
    category: "oolong",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["caramel", "roastedRice", "osmanthus", "cream"],
    vat: 6,
    passport: {
      regionId: "dongding",
      altitudeM: 750,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Familie Lin, Lugu, Nantou", en: "The Lin family, Lugu, Nantou" },
      cultivar: "Qing Xin",
      oxidation: 35,
      roast: "medium",
      storage: { nl: "Luchtdicht. Geroosterde Taiwanese oolong houdt zich twee jaar goed.", en: "Airtight. Roasted Taiwanese oolong keeps well for two years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 20, incrementSeconds: 10, infusions: 8 },
    western: { grams: 3, ml: 300, celsius: 92, minutes: 3, resteeps: 3 },
    variants: [{ sku: "WY-OO-DD-50", grams: 50, price: 2300, stock: 31 }],
    copy: {
      tagline: { nl: "Nantou, 750 m, traditioneel geroosterd door de familie Lin.", en: "Nantou, 750 m, traditionally roasted by the Lin family." },
      description: {
        nl: "Strak opgerolde balletjes die zich pas in de derde infusie helemaal openen; tot dan groeit het kopje nog. De rooster geeft karamel en een lichte toon van geroosterde rijst, zonder dat het bloemige eronder verdwijnt. Van alle oolongs hier is dit degene die het best werkt voor wie van koffie komt.",
        en: "Tightly rolled balls that only open fully in the third infusion; until then the cup is still growing. The roast gives caramel and a light note of toasted rice, without losing the floral underneath. Of all the oolongs here, this is the one that works best for people coming from coffee.",
      },
    },
    related: ["ali-shan-high-mountain", "tie-guan-yin-anxi"],
  },
  {
    slug: "ali-shan-high-mountain",
    name: "Ali Shan High Mountain",
    hanzi: "阿里山高山茶",
    pinyin: "Ālǐshān Gāoshān Chá",
    category: "oolong",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["cream", "lilac", "sweetPea", "butter"],
    vat: 6,
    passport: {
      regionId: "alishan",
      altitudeM: 1450,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Tuin Shizhuo, Chiayi", en: "Shizhuo garden, Chiayi" },
      cultivar: "Qing Xin",
      oxidation: 20,
      roast: "none",
      storage: { nl: "Koel en luchtdicht; hoogbergoolong verliest snel zijn romigheid.", en: "Cool and airtight; high mountain oolong loses its creaminess quickly." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 20, incrementSeconds: 10, infusions: 7 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 3, resteeps: 3 },
    variants: [{ sku: "WY-OO-AS-50", grams: 50, price: 2600, stock: 25 }],
    copy: {
      tagline: { nl: "Chiayi, 1450 m, ongeroosterd, oogst april 2026.", en: "Chiayi, 1450 m, unroasted, picked April 2026." },
      description: {
        nl: "Boven de duizend meter zijn de nachten koud en groeit de struik traag, en dat is precies wat deze thee zijn dikte geeft. Ongeroosterd, dus wat u proeft is het blad zelf: room, seringen, en een zoetheid die eerder aan verse boter doet denken dan aan suiker. Het aftreksel is bijna doorzichtig groen — dat hoort zo.",
        en: "Above a thousand metres the nights are cold and the bush grows slowly, and that is exactly what gives this tea its thickness. Unroasted, so what you taste is the leaf itself: cream, lilac, and a sweetness closer to fresh butter than to sugar. The liquor is almost transparent green — that is how it should be.",
      },
    },
    related: ["dong-ding", "tie-guan-yin-anxi"],
  },

  // ─── Witte thee ────────────────────────────────────────────────────────────
  {
    slug: "bai-hao-yin-zhen-fuding",
    name: "Bai Hao Yin Zhen",
    hanzi: "白毫银针",
    pinyin: "Báiháo Yínzhēn",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "medium",
    notes: ["honeysuckle", "melon", "hay", "honey"],
    vat: 6,
    featured: true,
    passport: {
      regionId: "fuding",
      altitudeM: 500,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: { nl: "Tuin Panxi, Fuding", en: "Panxi garden, Fuding" },
      cultivar: "Fuding Da Bai",
      oxidation: 8,
      roast: "none",
      storage: { nl: "Luchtdicht en donker. Witte thee mag jaren blijven liggen en wordt dan donkerder en zoeter.", en: "Airtight and dark. White tea may sit for years, and turns darker and sweeter as it does." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 90, rinseSeconds: null, firstSeconds: 20, incrementSeconds: 10, infusions: 8 },
    western: { grams: 3, ml: 300, celsius: 85, minutes: 4, resteeps: 2 },
    variants: [{ sku: "WY-WH-BHYZ-25", grams: 25, price: 2200, stock: 29 }],
    copy: {
      tagline: { nl: "Alleen knoppen, pluk van maart 2026, tuin Panxi.", en: "Buds only, picked March 2026, Panxi garden." },
      description: {
        nl: "Alleen de gesloten knop met het witte dons eraan, geplukt in een venster van ongeveer tien dagen. Er gebeurt verder niets mee: verwelken in de zon, drogen, klaar. Daardoor smaakt Yin Zhen naar bijna niets en tegelijk naar heel veel — kamperfoelie, meloen, en een zoetheid die pas komt als het kopje al bijna koud is. Niet spoelen.",
        en: "Only the closed bud with its white down, picked in a window of roughly ten days. Nothing else is done to it: wither in the sun, dry, done. Which is why Yin Zhen tastes of almost nothing and of a great deal at once — honeysuckle, melon, and a sweetness that only arrives when the cup has nearly gone cold. Do not rinse it.",
      },
    },
    reviews: [
      { author: "Ilse R.", city: "Oostende", rating: 5, date: "2026-05-06", body: { nl: "Zo licht dat ik dacht dat ik het verkeerd deed. Bij de vierde infusie viel het kwartje.", en: "So light I thought I was doing it wrong. On the fourth infusion the penny dropped." } },
      { author: "Karel J.", city: "Gent", rating: 4, date: "2026-03-30", body: { nl: "Fijn, maar het vraagt een stille kamer.", en: "Lovely, but it asks for a quiet room." } },
    ],
    related: ["bai-mu-dan", "shou-mei-2017", "yue-guang-bai"],
  },
  {
    slug: "bai-mu-dan",
    name: "Bai Mu Dan",
    hanzi: "白牡丹",
    pinyin: "Bái Mǔdān",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "low",
    notes: ["hay", "apricot", "honey", "cucumber"],
    vat: 6,
    passport: {
      regionId: "fuding",
      altitudeM: 450,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Tuin Panxi, Fuding", en: "Panxi garden, Fuding" },
      cultivar: "Fuding Da Bai",
      oxidation: 10,
      roast: "none",
      storage: { nl: "Luchtdicht en donker; jaarlijks controleren op vocht.", en: "Airtight and dark; check for damp once a year." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 92, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 7 },
    western: { grams: 3, ml: 300, celsius: 88, minutes: 4, resteeps: 2 },
    variants: [{ sku: "WY-WH-BMD-50", grams: 50, price: 1500, stock: 56 }],
    copy: {
      tagline: { nl: "Knop met twee blaadjes, pluk april 2026.", en: "One bud and two leaves, picked April 2026." },
      description: {
        nl: "Dezelfde tuin en dezelfde variëteit als de Yin Zhen, maar geplukt met twee blaadjes aan de knop. Dat maakt hem breder en goedkoper, en eerlijk gezegd voor dagelijks drinken beter. Hooi, abrikoos, en een frisheid die aan komkommer doet denken. Dit is de witte thee die wij zelf in de zomer koud zetten.",
        en: "The same garden and the same varietal as the Yin Zhen, but picked with two leaves on the bud. That makes it broader and cheaper, and honestly better for everyday drinking. Hay, apricot, and a freshness that recalls cucumber. This is the white tea we cold brew ourselves in summer.",
      },
    },
    related: ["bai-hao-yin-zhen-fuding", "shou-mei-2017"],
  },
  {
    slug: "shou-mei-2017",
    name: "Shou Mei 2017",
    hanzi: "寿眉",
    pinyin: "Shòuméi",
    category: "white",
    form: "cake",
    liquor: "white",
    caffeine: "low",
    notes: ["driedDate", "driedLeaf", "honey", "camphor"],
    vat: 6,
    vaultEligible: true,
    passport: {
      regionId: "fuding",
      altitudeM: 400,
      harvestYear: 2017,
      harvestMonth: 5,
      producer: { nl: "Werkplaats Diantou, Fuding", en: "Diantou workshop, Fuding" },
      cultivar: "Fuding Da Bai",
      oxidation: 12,
      roast: "none",
      storage: { nl: "Negen jaar droog opgeslagen in Fujian. Geperst, dus geschikt om verder te laten rijpen.", en: "Nine years of dry storage in Fujian. Pressed, so suitable for further ageing." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 6, celsius: 100, rinseSeconds: 5, firstSeconds: 12, incrementSeconds: 6, infusions: 10 },
    western: { grams: 4, ml: 300, celsius: 95, minutes: 4, resteeps: 3 },
    variants: [{ sku: "WY-WH-SM17-100", grams: 100, price: 1800, stock: 19, label: { nl: "geperst 100 g", en: "pressed 100 g" } }],
    copy: {
      tagline: { nl: "Negen jaar oud, geperst tot een schijf van 100 g.", en: "Nine years old, pressed into a 100 g disc." },
      description: {
        nl: "Er bestaat een Chinees gezegde over witte thee: één jaar thee, drie jaar medicijn, zeven jaar schat. Dat is marketing, maar er zit iets in. Deze Shou Mei uit 2017 is bruin geworden, ruikt naar gedroogde dadel en heeft de kamfertoon gekregen die oude witte thee kenmerkt. Hij kan met kokend water aan, wat verse witte thee niet verdraagt.",
        en: "There is a Chinese saying about white tea: one year tea, three years medicine, seven years treasure. That is marketing, but there is something to it. This 2017 Shou Mei has gone brown, smells of dried dates, and has picked up the camphor note that marks aged white tea. It takes boiling water, which fresh white tea will not.",
      },
    },
    related: ["bai-mu-dan", "menghai-gong-ting-2016"],
  },
  {
    slug: "yue-guang-bai",
    name: "Yue Guang Bai",
    hanzi: "月光白",
    pinyin: "Yuèguāng Bái",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "medium",
    notes: ["plum", "honey", "driedLeaf", "vanilla"],
    vat: 6,
    passport: {
      regionId: "puer-city",
      altitudeM: 1600,
      harvestYear: 2025,
      harvestMonth: 3,
      producer: { nl: "Kleine werkplaats bij Jinggu", en: "Small workshop near Jinggu" },
      cultivar: "Jinggu Da Bai",
      oxidation: 15,
      roast: "none",
      storage: { nl: "Luchtdicht en donker. Verandert langzaam de kant van pu-erh op.", en: "Airtight and dark. Slowly drifts in the direction of pu-erh." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 95, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 8 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 4, resteeps: 2 },
    variants: [{ sku: "WY-WH-YGB-50", grams: 50, price: 1700, stock: 34 }],
    copy: {
      tagline: { nl: "Yunnanese witte thee, Jinggu, 1600 m.", en: "Yunnan white tea, Jinggu, 1600 m." },
      description: {
        nl: "Maanlicht-wit heet zo omdat het blad aan één kant donker is en aan de andere kant zilverwit, alsof er maanlicht op valt. Het is witte thee gemaakt van de grootbladige Yunnan-variëteit, en dat proeft u: voller en fruitiger dan Fuding, met pruim en een zweem vanille. Het verhaal dat hij 's nachts gedroogd wordt is folklore, en wij gaan er niet in mee.",
        en: "Moonlight white is named for the leaf being dark on one side and silver white on the other, as if moonlight fell on it. It is white tea made from the broad-leaf Yunnan varietal, and you taste that: fuller and fruitier than Fuding, with plum and a hint of vanilla. The story that it is dried at night is folklore, and we do not repeat it.",
      },
    },
    related: ["bai-mu-dan", "jingmai-autumn-2022"],
  },

  // ─── Rode thee ─────────────────────────────────────────────────────────────
  {
    slug: "dian-hong-golden-needle",
    name: "Dian Hong Golden Needle",
    hanzi: "滇红金针",
    pinyin: "Diānhóng Jīnzhēn",
    category: "red",
    form: "loose",
    liquor: "red",
    caffeine: "high",
    notes: ["malt", "caramel", "longan", "darkChocolate"],
    vat: 6,
    passport: {
      regionId: "lincang",
      altitudeM: 1600,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Coöperatie Fengqing", en: "Fengqing cooperative" },
      cultivar: "Yunnan Da Ye",
      oxidation: 90,
      roast: "none",
      storage: { nl: "Luchtdicht, donker, weg van vocht. Binnen twee jaar drinken.", en: "Airtight, dark, away from damp. Drink within two years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 90, rinseSeconds: null, firstSeconds: 8, incrementSeconds: 4, infusions: 8 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 3, resteeps: 2 },
    variants: [{ sku: "WY-RE-DH-50", grams: 50, price: 1800, stock: 61 }],
    copy: {
      tagline: { nl: "Alleen gouden knoppen uit Fengqing, 1600 m.", en: "Golden buds only, from Fengqing, 1600 m." },
      description: {
        nl: "Van dezelfde bomen die sheng pu-erh leveren, maar volledig geoxideerd. Dat geeft een dikke, moutige rode thee met karamel en longan, zonder de looierigheid van Indiase thee. Hij verdraagt melk, al zou het zonde zijn. Van alle thee in dit rek is dit de makkelijkste ochtendthee.",
        en: "From the same trees that give sheng pu-erh, but fully oxidised. That yields a thick, malty red tea with caramel and longan, without the tannic grip of Indian tea. It takes milk, though it would be a waste. Of all the tea on this shelf, this is the easiest morning cup.",
      },
    },
    related: ["jin-jun-mei", "zheng-shan-xiao-zhong", "qimen-hao-ya"],
  },
  {
    slug: "jin-jun-mei",
    name: "Jin Jun Mei",
    hanzi: "金骏眉",
    pinyin: "Jīn Jùn Méi",
    category: "red",
    form: "loose",
    liquor: "red",
    caffeine: "high",
    notes: ["honey", "longan", "darkChocolate", "rose"],
    vat: 6,
    passport: {
      regionId: "tongmu",
      altitudeM: 1200,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Familie Jiang, natuurreservaat Tongmu", en: "The Jiang family, Tongmu nature reserve" },
      cultivar: "Wuyi Cai Cha",
      oxidation: 85,
      roast: "none",
      storage: { nl: "Luchtdicht en donker. Binnen achttien maanden drinken.", en: "Airtight and dark. Drink within eighteen months." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 90, rinseSeconds: null, firstSeconds: 6, incrementSeconds: 3, infusions: 9 },
    western: { grams: 3, ml: 300, celsius: 88, minutes: 2, resteeps: 3 },
    variants: [{ sku: "WY-RE-JJM-25", grams: 25, price: 3200, stock: 16 }],
    copy: {
      tagline: { nl: "Knoppen uit Tongmu, binnen het reservaat, 1200 m.", en: "Buds from Tongmu, inside the reserve, 1200 m." },
      description: {
        nl: "Jin Jun Mei bestaat pas sinds 2005 en is meteen de duurste rode thee van China geworden, wat betekent dat het overgrote deel van wat onder die naam wordt verkocht er niet is. Deze komt uit het reservaat zelf. Honing, longan en een rozentoon die je bij geen andere rode thee tegenkomt. Kort zetten en niet te heet.",
        en: "Jin Jun Mei has only existed since 2005 and immediately became the most expensive red tea in China, which means the great majority of what is sold under that name is not it. This one comes from the reserve itself. Honey, longan and a rose note you meet in no other red tea. Steep short and not too hot.",
      },
    },
    reviews: [
      { author: "Dries L.", city: "Brussel", rating: 5, date: "2026-06-22", body: { nl: "Duur per gram, maar je gebruikt er weinig van en het gaat negen keer mee.", en: "Expensive per gram, but you use little and it goes nine rounds." } },
    ],
    related: ["zheng-shan-xiao-zhong", "dian-hong-golden-needle"],
  },
  {
    slug: "zheng-shan-xiao-zhong",
    name: "Zheng Shan Xiao Zhong",
    hanzi: "正山小种",
    pinyin: "Zhèngshān Xiǎozhǒng",
    category: "red",
    form: "loose",
    liquor: "red",
    caffeine: "medium",
    notes: ["longan", "malt", "plum", "cedar"],
    vat: 6,
    passport: {
      regionId: "tongmu",
      altitudeM: 1000,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Familie Jiang, natuurreservaat Tongmu", en: "The Jiang family, Tongmu nature reserve" },
      cultivar: "Wuyi Cai Cha",
      oxidation: 90,
      roast: "none",
      storage: { nl: "Luchtdicht en donker. Binnen twee jaar drinken.", en: "Airtight and dark. Drink within two years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 95, rinseSeconds: null, firstSeconds: 8, incrementSeconds: 4, infusions: 8 },
    western: { grams: 3, ml: 300, celsius: 92, minutes: 3, resteeps: 2 },
    variants: [{ sku: "WY-RE-ZSXZ-50", grams: 50, price: 1900, stock: 38 }],
    copy: {
      tagline: { nl: "De ongerookte versie, zoals ze in Tongmu zelf gedronken wordt.", en: "The unsmoked version, as it is drunk in Tongmu itself." },
      description: {
        nl: "Dit is de thee die in het Westen lapsang souchong heet, maar zonder de dennenrook. Die rook was oorspronkelijk een noodgreep om nat blad te drogen en werd later een exportsmaak; in Tongmu zelf drinkt men de ongerookte versie. Wat overblijft is longan, mout en een lichte cederhouttoon. Wie de rokerige zoekt, moet dit niet bestellen.",
        en: "This is the tea the West calls lapsang souchong, minus the pine smoke. That smoke was originally an emergency measure for drying wet leaf and later became an export flavour; in Tongmu itself people drink the unsmoked version. What remains is longan, malt and a light cedar note. If you want the smoky one, do not order this.",
      },
    },
    related: ["jin-jun-mei", "dian-hong-golden-needle"],
  },
  {
    slug: "qimen-hao-ya",
    name: "Qimen Hao Ya",
    hanzi: "祁门毫芽",
    pinyin: "Qímén Háo Yá",
    category: "red",
    form: "loose",
    liquor: "red",
    caffeine: "high",
    notes: ["rose", "malt", "darkChocolate", "driedFig"],
    vat: 6,
    passport: {
      regionId: "qimen",
      altitudeM: 600,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: { nl: "Fabriek Likou, Qimen", en: "Likou factory, Qimen" },
      cultivar: "Qimen Zhu Ye Zhong",
      oxidation: 90,
      roast: "none",
      storage: { nl: "Luchtdicht en donker. Binnen twee jaar drinken.", en: "Airtight and dark. Drink within two years." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 5, celsius: 95, rinseSeconds: null, firstSeconds: 8, incrementSeconds: 4, infusions: 7 },
    western: { grams: 3, ml: 300, celsius: 95, minutes: 3, resteeps: 2 },
    variants: [{ sku: "WY-RE-QM-50", grams: 50, price: 1600, stock: 42 }],
    copy: {
      tagline: { nl: "Hao ya, de knopgraad van Keemun, oogst mei 2026.", en: "Hao ya, the bud grade of Keemun, picked May 2026." },
      description: {
        nl: "Keemun is de thee waarop het Europese idee van zwarte thee is gebouwd, en de beroemde rozentoon is geen verzinsel van theeverkopers: hij is er, vooral in de geur van het natte blad. Hao ya is de fijnste graad. Dit is de enige thee in ons rek waarvan wij toegeven dat een scheutje melk hem niet kapotmaakt.",
        en: "Keemun is the tea the European idea of black tea was built on, and the famous rose note is not an invention of tea sellers: it is there, above all in the smell of the wet leaf. Hao ya is the finest grade. This is the one tea on our shelf we will admit a splash of milk does not ruin.",
      },
    },
    related: ["dian-hong-golden-needle", "zheng-shan-xiao-zhong"],
  },

  // ─── Groene thee ───────────────────────────────────────────────────────────
  {
    slug: "xi-hu-long-jing",
    name: "Xi Hu Long Jing",
    hanzi: "西湖龙井",
    pinyin: "Xīhú Lóngjǐng",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["chestnut", "sweetPea", "butter", "hay"],
    vat: 6,
    featured: true,
    passport: {
      regionId: "xihu",
      altitudeM: 250,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: { nl: "Meijiawu, familie Weng", en: "Meijiawu, the Weng family" },
      cultivar: "Longjing 43",
      oxidation: 3,
      roast: "light",
      storage: { nl: "In de koelkast, luchtdicht. Groene thee van dit niveau is over het jaar heen.", en: "In the fridge, airtight. Green tea at this level is finished by the end of the year." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 4, celsius: 80, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 5 },
    western: { grams: 3, ml: 300, celsius: 80, minutes: 2, resteeps: 2 },
    variants: [{ sku: "WY-GR-LJ-50", grams: 50, price: 2900, stock: 23 }],
    copy: {
      tagline: { nl: "Vóór Qingming geplukt, Meijiawu, 22 maart 2026.", en: "Picked before Qingming, Meijiawu, 22 March 2026." },
      description: {
        nl: "Long Jing van vóór Qingming is duur om één reden: het venster is ongeveer twee weken lang en het blad groeit in die weken nauwelijks. Meijiawu ligt binnen het kerngebied rond het Westmeer. Kastanje, doperwt, en de boterige toon die de pan geeft. Water van tachtig graden, geen honderd — anders is er van al die precisie niets over.",
        en: "Pre-Qingming Long Jing is expensive for one reason: the window is about two weeks long and the leaf barely grows in them. Meijiawu lies inside the West Lake core area. Chestnut, sweet pea, and the buttery note the pan gives. Water at eighty degrees, not a hundred — otherwise nothing of all that precision survives.",
      },
    },
    reviews: [
      { author: "Anke T.", city: "Gent", rating: 5, date: "2026-04-25", body: { nl: "Op 80 graden. Op 90 was hij bitter. Het advies op de pagina klopt echt.", en: "At 80 degrees. At 90 it was bitter. The advice on the page really is right." } },
      { author: "Filip N.", city: "Kortrijk", rating: 5, date: "2026-04-11", body: { nl: "Ruikt in het droge blad al naar kastanje. Nooit eerder meegemaakt.", en: "The dry leaf already smells of chestnut. Never had that before." } },
    ],
    related: ["bi-luo-chun", "anji-bai-cha", "huangshan-mao-feng"],
  },
  {
    slug: "bi-luo-chun",
    name: "Bi Luo Chun",
    hanzi: "碧螺春",
    pinyin: "Bìluóchūn",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["apricot", "gardenia", "chestnut", "greenBean"],
    vat: 6,
    passport: {
      regionId: "dongting",
      altitudeM: 100,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: { nl: "Oostheuvel, Tai-meer", en: "East hill, Lake Tai" },
      cultivar: "Dongting Qun Ti",
      oxidation: 3,
      roast: "light",
      storage: { nl: "In de koelkast, luchtdicht, in kleine porties.", en: "In the fridge, airtight, in small portions." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 4, celsius: 78, rinseSeconds: null, firstSeconds: 12, incrementSeconds: 6, infusions: 5 },
    western: { grams: 3, ml: 300, celsius: 78, minutes: 2, resteeps: 2 },
    variants: [{ sku: "WY-GR-BLC-50", grams: 50, price: 2400, stock: 27 }],
    copy: {
      tagline: { nl: "Van de oostheuvel in het Tai-meer, pluk maart 2026.", en: "From the east hill in Lake Tai, picked March 2026." },
      description: {
        nl: "Op de twee heuvels in het Tai-meer staan de theestruiken tussen abrikozen- en perzikbomen, en de bloesem valt in dezelfde weken als de pluk. Dat het fruit in de thee terechtkomt klinkt als een verkoopverhaal, maar u ruikt het in de eerste infusie. Het blad is zo dun opgerold dat het meteen zinkt; giet het water langs de wand.",
        en: "On the two hills in Lake Tai the tea bushes stand among apricot and peach trees, and the blossom falls in the same weeks as the picking. That the fruit ends up in the tea sounds like a sales story, but you smell it in the first infusion. The leaf is rolled so fine that it sinks immediately; pour the water down the side.",
      },
    },
    related: ["xi-hu-long-jing", "huangshan-mao-feng"],
  },
  {
    slug: "huangshan-mao-feng",
    name: "Huangshan Mao Feng",
    hanzi: "黄山毛峰",
    pinyin: "Huángshān Máofēng",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["magnolia", "chestnut", "sweetPea", "melon"],
    vat: 6,
    passport: {
      regionId: "huangshan",
      altitudeM: 800,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Dorp Fuxi, Huangshan", en: "Fuxi village, Huangshan" },
      cultivar: "Huangshan Zhong Ye",
      oxidation: 3,
      roast: "light",
      storage: { nl: "In de koelkast, luchtdicht.", en: "In the fridge, airtight." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 4, celsius: 82, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 5 },
    western: { grams: 3, ml: 300, celsius: 82, minutes: 2, resteeps: 2 },
    variants: [{ sku: "WY-GR-HMF-50", grams: 50, price: 1600, stock: 49 }],
    copy: {
      tagline: { nl: "Fuxi, 800 m, in de mist van de Gele Bergen geplukt.", en: "Fuxi, 800 m, picked in the mist of the Yellow Mountains." },
      description: {
        nl: "De meest vergevingsgezinde van onze groene thee: hij wordt niet meteen bitter als het water iets te heet is, en dat maakt hem een goed begin. Magnolia in de geur, kastanje in de mond, en een meloenachtige zoetheid in de afdronk. Voor wie groene thee tot nu toe vooral kende als iets grasachtigs uit een zakje.",
        en: "The most forgiving of our green teas: it does not turn bitter the moment the water is a little too hot, which makes it a good place to start. Magnolia in the scent, chestnut in the mouth, and a melon-like sweetness in the finish. For anyone who so far knew green tea mainly as something grassy from a bag.",
      },
    },
    related: ["xi-hu-long-jing", "anji-bai-cha"],
  },
  {
    slug: "anji-bai-cha",
    name: "Anji Bai Cha",
    hanzi: "安吉白茶",
    pinyin: "Ānjí Báichá",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["sweetPea", "bamboo", "brine", "greenBean"],
    vat: 6,
    passport: {
      regionId: "anji",
      altitudeM: 600,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: { nl: "Tuin Xilong, Anji", en: "Xilong garden, Anji" },
      cultivar: "Bai Ye Yi Hao",
      oxidation: 3,
      roast: "light",
      storage: { nl: "In de koelkast, luchtdicht. De umami zakt merkbaar na zes maanden.", en: "In the fridge, airtight. The umami drops off noticeably after six months." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 4, celsius: 80, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 5 },
    western: { grams: 3, ml: 300, celsius: 80, minutes: 2, resteeps: 2 },
    variants: [{ sku: "WY-GR-ABC-50", grams: 50, price: 2100, stock: 24 }],
    copy: {
      tagline: { nl: "Ondanks de naam groene thee: de bleke variëteit Bai Ye Yi Hao.", en: "Green tea despite the name: the pale Bai Ye Yi Hao varietal." },
      description: {
        nl: "Anji Bai Cha heet witte thee maar is het niet; de naam slaat op de variëteit, die in het voorjaar drie weken lang bijna wit blad maakt voordat het vergroent. In die weken zit er ongewoon veel theanine in, en dat proeft u als een bouillonachtige zoetheid die in geen enkele andere Chinese groene thee zo sterk is. Wij vermelden het hier omdat de naam anders verwarrend is.",
        en: "Anji Bai Cha is called white tea but is not; the name refers to the varietal, which for three weeks in spring makes nearly white leaf before it greens up. In those weeks it holds unusually high theanine, and you taste that as a broth-like sweetness no other Chinese green tea has this strongly. We spell it out because the name is otherwise confusing.",
      },
    },
    related: ["xi-hu-long-jing", "meng-ding-huang-ya"],
  },

  // ─── Gele thee ─────────────────────────────────────────────────────────────
  {
    slug: "meng-ding-huang-ya",
    name: "Meng Ding Huang Ya",
    hanzi: "蒙顶黄芽",
    pinyin: "Méngdǐng Huángyá",
    category: "yellow",
    form: "loose",
    liquor: "yellow",
    caffeine: "medium",
    notes: ["chestnut", "honey", "hay", "steamedGreens"],
    vat: 6,
    passport: {
      regionId: "mengding",
      altitudeM: 1100,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: { nl: "Werkplaats Ya'an, Meng Ding Shan", en: "Ya'an workshop, Meng Ding Shan" },
      cultivar: "Meng Shan Zhong",
      oxidation: 8,
      roast: "light",
      storage: { nl: "Koel en luchtdicht. Binnen een jaar drinken.", en: "Cool and airtight. Drink within a year." },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 4, celsius: 85, rinseSeconds: null, firstSeconds: 20, incrementSeconds: 10, infusions: 6 },
    western: { grams: 3, ml: 300, celsius: 85, minutes: 3, resteeps: 2 },
    variants: [{ sku: "WY-YE-MDHY-25", grams: 25, price: 2600, stock: 14 }],
    copy: {
      tagline: { nl: "Meng Ding Shan, 1100 m, met de hand geel gemaakt.", en: "Meng Ding Shan, 1100 m, yellowed by hand." },
      description: {
        nl: "Gele thee is de zeldzaamste van de zes soorten, en dat komt door één extra stap: men huan, het smoren. Het warme blad wordt in papier of doek gewikkeld en blijft daar uren tot dagen liggen, waardoor de grasachtigheid van groene thee verdwijnt en er kastanje en honing voor in de plaats komen. Er zijn nog maar weinig werkplaatsen die het doen. Wij kopen jaarlijks één partij.",
        en: "Yellow tea is the rarest of the six types, and that comes down to one extra step: men huang, the smothering. The warm leaf is wrapped in paper or cloth and left there for hours or days, which takes away the grassiness of green tea and puts chestnut and honey in its place. Few workshops still do it. We buy one batch a year.",
      },
    },
    related: ["anji-bai-cha", "bai-hao-yin-zhen-fuding"],
  },

  // ─── Matcha, Japanse gastcollectie ─────────────────────────────────────────
  {
    slug: "ceremonial-uji-matcha",
    name: "Ceremonial Uji",
    hanzi: "宇治抹茶",
    pinyin: "Uji Matcha",
    category: "matcha",
    form: "powder",
    liquor: "matcha",
    caffeine: "high",
    notes: ["seaweed", "cream", "sweetPea", "spinach"],
    vat: 6,
    passport: {
      regionId: "uji",
      altitudeM: null,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: { nl: "Steenmolen in Uji-Tawara, Kyoto", en: "Stone mill in Uji-Tawara, Kyoto" },
      cultivar: "Samidori",
      oxidation: 0,
      roast: "none",
      storage: { nl: "In de koelkast, luchtdicht, en na openen binnen zes weken op.", en: "In the fridge, airtight, and used up within six weeks of opening." },
      unknown: {
        nl: "De hoogte van de tuin geven Japanse producenten niet op; wij vullen daar niets in.",
        en: "Japanese producers do not report garden altitude; we leave that blank rather than guess.",
      },
    },
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-MA-UJI-30", grams: 30, price: 3400, stock: 20 }],
    copy: {
      tagline: { nl: "Japanse thee, geen Chinese. Uji, Kyoto, eerste pluk 2026.", en: "Japanese tea, not Chinese. Uji, Kyoto, first picking 2026." },
      description: {
        nl: "Wij verkopen Chinese thee, en matcha is dat niet. Ze staat hier omdat mensen erom vragen en omdat wij liever goede Japanse thee verkopen dan slechte. Deze komt van een steenmolen in Uji-Tawara: eerste pluk, drie weken onder doek, en zo fijn gemalen dat het poeder aan de lepel blijft plakken. Alleen met de chasen kloppen, niet in een zeef duwen.",
        en: "We sell Chinese tea, and matcha is not that. It is here because people ask for it and because we would rather sell good Japanese tea than bad. This one comes from a stone mill in Uji-Tawara: first picking, three weeks under shade cloth, and ground so fine the powder clings to the spoon. Whisk it with a chasen only, do not push it through a sieve.",
      },
    },
    related: ["daily-nishio-matcha", "chasen-bamboe", "chawan-steengoed"],
  },
  {
    slug: "daily-nishio-matcha",
    name: "Daily Nishio",
    hanzi: "西尾抹茶",
    pinyin: "Nishio Matcha",
    category: "matcha",
    form: "powder",
    liquor: "matcha",
    caffeine: "high",
    notes: ["spinach", "malt", "cream", "seaweed"],
    vat: 6,
    passport: {
      regionId: "nishio",
      altitudeM: null,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: { nl: "Coöperatie Nishio, Aichi", en: "Nishio cooperative, Aichi" },
      cultivar: "Yabukita",
      oxidation: 0,
      roast: "none",
      storage: { nl: "In de koelkast, luchtdicht, na openen binnen twee maanden op.", en: "In the fridge, airtight, used up within two months of opening." },
      unknown: {
        nl: "De hoogte van de tuin geven Japanse producenten niet op; wij vullen daar niets in.",
        en: "Japanese producers do not report garden altitude; we leave that blank rather than guess.",
      },
    },
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-MA-NIS-100", grams: 100, price: 2900, stock: 30 }],
    copy: {
      tagline: { nl: "Japanse thee, geen Chinese. Aichi, tweede pluk 2026.", en: "Japanese tea, not Chinese. Aichi, second picking 2026." },
      description: {
        nl: "De matcha voor elke dag, en eerlijk gezegd de betere keuze als er melk bij gaat: hij is vlakker en steviger dan de Uji, en blijft daardoor overeind in een latte waarin de ceremoniële volledig verdwijnt. Honderd gram, want zo drinkt men matcha die men elke ochtend drinkt.",
        en: "The everyday matcha, and honestly the better choice when milk is involved: it is flatter and sturdier than the Uji, and so stands up in a latte where the ceremonial one disappears entirely. A hundred grams, because that is how you buy matcha you drink every morning.",
      },
    },
    related: ["ceremonial-uji-matcha", "chasen-bamboe"],
  },

  // ─── Gerei ─────────────────────────────────────────────────────────────────
  {
    slug: "gaiwan-porselein-110",
    name: "Gaiwan, porselein",
    hanzi: "盖碗",
    pinyin: "Gàiwǎn",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-GW-110", grams: 110, price: 2800, stock: 40, label: { nl: "110 ml", en: "110 ml" } }],
    copy: {
      tagline: { nl: "110 ml, dunwandig porselein uit Jingdezhen.", en: "110 ml, thin-walled porcelain from Jingdezhen." },
      description: {
        nl: "Als u één ding koopt om gongfu te leren, koop dan dit en niet een kannetje. Porselein neemt geen geur op, dus dezelfde gaiwan kan vandaag sheng en morgen witte thee. Honderdtien milliliter is de maat waarop alle parameters op deze site zijn afgestemd. De rand staat naar buiten zodat u hem kunt vasthouden zonder u te branden — dat lukt na een keer of vijf.",
        en: "If you buy one thing to learn gongfu, buy this and not a little pot. Porcelain takes on no scent, so the same gaiwan can do sheng today and white tea tomorrow. A hundred and ten millilitres is the size every parameter on this site is calibrated to. The rim flares outward so you can hold it without burning yourself — which works from about the fifth try.",
      },
    },
    related: ["chahai-glas", "pialas-set-vier", "chaban-bamboe"],
  },
  {
    slug: "yixing-zhuni-100",
    name: "Yixing, zhuni",
    hanzi: "宜兴朱泥",
    pinyin: "Yíxīng Zhūní",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-YX-100", grams: 100, price: 9500, stock: 7, label: { nl: "100 ml", en: "100 ml" } }],
    copy: {
      tagline: { nl: "100 ml, met de hand gemaakt, ongeglazuurde zhuni-klei.", en: "100 ml, handmade, unglazed zhuni clay." },
      description: {
        nl: "Zhuni is de fijnkorrelige rode klei uit Yixing die bij het bakken sterk krimpt; daarom zijn deze kannetjes klein en daarom klinken ze helder als u het deksel erop tikt. Ongeglazuurd, dus de kan neemt smaak op en houdt die vast: één kan, één theesoort. Wij raden hem aan voor yancha of shou, niet voor allebei. Nooit met zeep wassen.",
        en: "Zhuni is the fine-grained red clay from Yixing that shrinks heavily in the kiln; that is why these pots are small and why they ring clear when you tap the lid. Unglazed, so the pot takes on flavour and keeps it: one pot, one kind of tea. We recommend it for yancha or for shou, not for both. Never wash it with soap.",
      },
    },
    related: ["gaiwan-porselein-110", "da-hong-pao-zhengyan", "chaban-bamboe"],
  },
  {
    slug: "chahai-glas",
    name: "Chahai, glas",
    hanzi: "茶海",
    pinyin: "Cháhǎi",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CH-220", grams: 220, price: 2200, stock: 35, label: { nl: "220 ml", en: "220 ml" } }],
    copy: {
      tagline: { nl: "220 ml, hittebestendig glas, met schenklip.", en: "220 ml, heat-resistant glass, with a pouring lip." },
      description: {
        nl: "De billijkheidskan. U giet de gaiwan er in één keer in leeg en schenkt daarna pas de kopjes uit, zodat iedereen dezelfde sterkte krijgt en het blad niet doortrekt. Glas, omdat u dan de kleur van elke infusie ziet veranderen — en dat is precies de informatie die u nodig hebt om te weten wanneer de thee klaar is.",
        en: "The fairness pitcher. You empty the gaiwan into it in one go and only then pour the cups, so everyone gets the same strength and the leaf stops steeping. Glass, because then you see the colour of each infusion change — and that is exactly the information you need to know when the tea is done.",
      },
    },
    related: ["gaiwan-porselein-110", "pialas-set-vier"],
  },
  {
    slug: "pialas-set-vier",
    name: "Pialas, set van vier",
    hanzi: "品茗杯",
    pinyin: "Pǐnmíng Bēi",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CUP-4", grams: 45, price: 2600, stock: 44, label: { nl: "vier stuks, 45 ml", en: "four pieces, 45 ml" } }],
    copy: {
      tagline: { nl: "Vier kopjes van 45 ml, wit geglazuurd van binnen.", en: "Four 45 ml cups, white glazed inside." },
      description: {
        nl: "Klein, want bij gongfu drinkt u veel kleine kopjes in plaats van één grote. Wit van binnen is geen esthetische keuze: tegen wit ziet u de kleur van het aftreksel zoals ze is, en die kleur vertelt u meer over de thee dan het etiket. Vaatwasserbestendig, al doen wij het zelf niet.",
        en: "Small, because in gongfu you drink many small cups instead of one large one. White inside is not an aesthetic choice: against white you see the colour of the liquor as it is, and that colour tells you more about the tea than the label does. Dishwasher safe, though we do not do it ourselves.",
      },
    },
    related: ["gaiwan-porselein-110", "chahai-glas"],
  },
  {
    slug: "chaban-bamboe",
    name: "Chaban, bamboe",
    hanzi: "茶盘",
    pinyin: "Chápán",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CB-36", grams: 360, price: 4800, stock: 15, label: { nl: "36 × 22 cm", en: "36 × 22 cm" } }],
    copy: {
      tagline: { nl: "36 × 22 cm, bamboe, met uitneembare opvangbak.", en: "36 × 22 cm, bamboo, with a removable drip tray." },
      description: {
        nl: "Bij gongfu wordt er gemorst: u spoelt het blad, u warmt de kopjes, u giet over. Het theebord vangt dat op en maakt van morsen een onderdeel van de handeling in plaats van een ongeluk. De bak eronder houdt ongeveer een halve liter, wat genoeg is voor een sessie van twee uur.",
        en: "In gongfu things get spilled: you rinse the leaf, you warm the cups, you pour over. The tea tray catches all of it and turns spilling into part of the procedure instead of an accident. The tray underneath holds about half a litre, which is enough for a two-hour session.",
      },
    },
    related: ["gaiwan-porselein-110", "yixing-zhuni-100"],
  },
  {
    slug: "chasen-bamboe",
    name: "Chasen",
    hanzi: "茶筅",
    pinyin: "Chasen",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CS-80", grams: 30, price: 2400, stock: 28, label: { nl: "80 tanden", en: "80 prongs" } }],
    copy: {
      tagline: { nl: "Tachtig tanden, uit één stuk bamboe gesneden.", en: "Eighty prongs, cut from a single piece of bamboo." },
      description: {
        nl: "Voor matcha, en alleen voor matcha. Uit één stuk bamboe gesneden, wat u ziet aan de nerf die over de hele lengte doorloopt. Week hem voor gebruik dertig seconden in warm water, dan breken de tanden niet. Laat hem drogen met de tanden naar boven, nooit plat, anders vervormt hij binnen een maand.",
        en: "For matcha, and only for matcha. Cut from a single piece of bamboo, which you can see in the grain running the whole length. Soak it in warm water for thirty seconds before use and the prongs will not snap. Let it dry prongs up, never flat, or it warps within a month.",
      },
    },
    related: ["ceremonial-uji-matcha", "chawan-steengoed"],
  },
  {
    slug: "chawan-steengoed",
    name: "Chawan",
    hanzi: "茶碗",
    pinyin: "Chawan",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CW-400", grams: 400, price: 3900, stock: 18, label: { nl: "400 ml", en: "400 ml" } }],
    copy: {
      tagline: { nl: "400 ml steengoed, met een vlakke bodem voor de chasen.", en: "400 ml stoneware, with a flat floor for the chasen." },
      description: {
        nl: "Een matcha-kom is breed en heeft een vlakke bodem, want u moet er met de chasen in kunnen bewegen zonder de tanden tegen een ronding te duwen. Vierhonderd milliliter lijkt veel voor zeventig milliliter thee, en dat is het ook: de ruimte is er om te kloppen, niet om te vullen.",
        en: "A matcha bowl is wide and has a flat floor, because you need room to move the chasen without pushing the prongs against a curve. Four hundred millilitres looks like a lot for seventy millilitres of tea, and it is: the space is there for whisking, not for filling.",
      },
    },
    related: ["chasen-bamboe", "ceremonial-uji-matcha"],
  },
  {
    slug: "weegschaal-01g",
    name: "Weegschaal, 0,1 g",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-SC-500", grams: 500, price: 2600, stock: 32, label: { nl: "tot 500 g", en: "up to 500 g" } }],
    copy: {
      tagline: { nl: "Nauwkeurig tot 0,1 g, bereik tot 500 g, met tarra.", en: "Accurate to 0.1 g, range to 500 g, with tare." },
      description: {
        nl: "Het verschil tussen zes en acht gram in een gaiwan van 110 ml is het verschil tussen twee verschillende thees. Zolang u op het oog doseert, kunt u niet vergelijken en dus ook niet leren. Dit is het saaiste voorwerp op de site en waarschijnlijk het nuttigste.",
        en: "The difference between six and eight grams in a 110 ml gaiwan is the difference between two different teas. As long as you dose by eye, you cannot compare and therefore cannot learn. This is the dullest object on the site and probably the most useful.",
      },
    },
    related: ["gaiwan-porselein-110", "set-kennismaking"],
  },
  {
    slug: "ijzeren-ketel-12l",
    name: "IJzeren ketel, 1,2 l",
    hanzi: "铁壶",
    pinyin: "Tiěhú",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-KT-12", grams: 1200, price: 8900, stock: 9, label: { nl: "1,2 l", en: "1.2 l" } }],
    copy: {
      tagline: { nl: "1,2 liter gietijzer, geëmailleerd van binnen, geschikt voor inductie.", en: "1.2 litres of cast iron, enamelled inside, induction ready." },
      description: {
        nl: "Een ijzeren ketel houdt de temperatuur beter vast dan glas of staal, en dat merkt u bij de achtste infusie van een yancha, wanneer een gewone waterkoker al twintig graden is gezakt. Van binnen geëmailleerd, dus er komt geen ijzersmaak in het water. Zwaar, dat is het nadeel.",
        en: "An iron kettle holds its temperature better than glass or steel, and you notice that at the eighth infusion of a yancha, when an ordinary kettle has already dropped twenty degrees. Enamelled inside, so no iron taste gets into the water. Heavy, that is the drawback.",
      },
    },
    related: ["da-hong-pao-zhengyan", "gaiwan-porselein-110"],
  },

  // ─── Sets en cadeau ────────────────────────────────────────────────────────
  {
    slug: "set-kennismaking",
    name: "Kennismaking",
    category: "sets",
    form: "loose",
    liquor: "neutral",
    caffeine: "medium",
    notes: [],
    vat: 6,
    featured: true,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-ST-KM-6", grams: 60, price: 3900, stock: 26, label: { nl: "zes maal 10 g", en: "six times 10 g" } }],
    copy: {
      tagline: { nl: "Zes soorten van 10 g: sheng, shou, oolong, wit, rood, groen.", en: "Six kinds of 10 g: sheng, shou, oolong, white, red, green." },
      description: {
        nl: "Zes zakjes van tien gram, één uit elke familie, met bij elk zakje een kaartje waarop staat hoeveel gram, hoeveel graden en hoeveel seconden. Tien gram is ongeveer vijf gongfu-sessies, genoeg om te merken of iets bij u past. Wie hierna een volle verpakking bestelt, krijgt de prijs van het zakje in mindering — vermeld uw ordernummer bij de bestelling.",
        en: "Six ten-gram packets, one from each family, each with a card giving grams, degrees and seconds. Ten grams is about five gongfu sessions, enough to find out whether something suits you. If you order a full packet afterwards, we deduct the price of the sample — quote your order number when you do.",
      },
    },
    related: ["set-puerh-verticaal", "gaiwan-porselein-110", "weegschaal-01g"],
  },
  {
    slug: "set-puerh-verticaal",
    name: "Puerh Verticaal",
    category: "sets",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: [],
    vat: 6,
    passport: {
      regionId: "yiwu",
      altitudeM: 1350,
      harvestYear: null,
      harvestMonth: 4,
      producer: { nl: "Familie Li, Mahei — vier opeenvolgende oogsten", en: "The Li family, Mahei — four consecutive harvests" },
      cultivar: "Yiwu Da Ye",
      oxidation: 10,
      roast: "none",
      storage: { nl: "Alle vier de jaren droog opgeslagen in Kunming, in dezelfde ruimte.", en: "All four years dry stored in Kunming, in the same room." },
      unknown: {
        nl: "Eén jaargang is geen zuivere tuinpartij: in 2019 mislukte de voorjaarspluk en kocht de familie blad bij van een buurtuin op dezelfde helling. Dat staat op het kaartje.",
        en: "One vintage is not a pure garden batch: in 2019 the spring picking failed and the family bought leaf from a neighbouring garden on the same slope. That is written on the card.",
      },
    },
    gongfu: { vessel: "gaiwan", vesselMl: 110, grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 11 },
    western: { grams: 3, ml: 300, celsius: 90, minutes: 3, resteeps: 2 },
    variants: [{ sku: "WY-ST-PV-4", grams: 100, price: 6800, stock: 12, label: { nl: "vier maal 25 g", en: "four times 25 g" } }],
    copy: {
      tagline: { nl: "Eén tuin, vier jaargangen: 2018, 2019, 2021, 2023.", en: "One garden, four vintages: 2018, 2019, 2021, 2023." },
      description: {
        nl: "Vier keer vijfentwintig gram van dezelfde tuin in Mahei, uit vier verschillende jaren, allemaal in dezelfde ruimte in Kunming bewaard. Zet ze op één middag naast elkaar en u ziet wat ouderdom met sheng doet zonder dat variabelen als tuin, maker of opslag in de weg zitten. Dit is de snelste manier om te begrijpen waar de Vault over gaat.",
        en: "Four times twenty-five grams from the same garden in Mahei, from four different years, all kept in the same room in Kunming. Set them side by side on one afternoon and you see what age does to sheng without garden, maker or storage getting in the way. This is the fastest way to understand what the Vault is about.",
      },
    },
    related: ["yiwu-zhengshan-2018", "bingdao-gushu-2021", "set-kennismaking"],
  },
  {
    slug: "cadeaubon",
    name: "Cadeaubon",
    category: "sets",
    form: "voucher",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [
      { sku: "WY-GC-25", grams: 25, price: 2500, stock: 999, label: { nl: "€ 25", en: "€ 25" } },
      { sku: "WY-GC-50", grams: 50, price: 5000, stock: 999, label: { nl: "€ 50", en: "€ 50" } },
      { sku: "WY-GC-100", grams: 100, price: 10000, stock: 999, label: { nl: "€ 100", en: "€ 100" } },
    ],
    copy: {
      tagline: { nl: "Per e-mail of op karton, twee jaar geldig.", en: "By email or on card, valid for two years." },
      description: {
        nl: "Een bon is de eerlijke oplossing wanneer u weet dat iemand thee drinkt maar niet welke. Hij komt als code per e-mail, of gedrukt op karton als u dat bij het afrekenen aangeeft. Twee jaar geldig, in één keer of in delen te gebruiken, en ook geldig voor een proeverij of voor bewaring in de Vault.",
        en: "A voucher is the honest solution when you know someone drinks tea but not which one. It arrives as a code by email, or printed on card if you say so at checkout. Valid for two years, usable in one go or in parts, and also valid for a tasting or for storage in the Vault.",
      },
    },
    related: ["set-kennismaking", "set-puerh-verticaal"],
  },
];
