import type { Gongfu, I18nText, Product, Western } from "./types";

/**
 * The catalogue. Deliberately compact: forty-four teas, eight pieces of
 * teaware, five sets. Better forty-four batches the supplier always has than
 * two hundred of which half are out of stock.
 *
 * Prices are a single base per 25 g in euro cents, VAT included; every other
 * format comes off the ladder in `lib/catalog.ts`. Tea carries 6 % Belgian VAT,
 * objects and vouchers 21 %.
 */

const t = (nl: string, en: string): I18nText => ({ nl, en });

/** Gongfu defaults to a 110 ml gaiwan, which is what every parameter is set to. */
const gf = (o: Omit<Gongfu, "vessel" | "vesselMl"> & Partial<Pick<Gongfu, "vessel" | "vesselMl">>): Gongfu => ({
  vessel: "gaiwan",
  vesselMl: 110,
  ...o,
});

const west = (grams: number, ml: number, celsius: number, minutes: number, resteeps: number): Western => ({
  grams,
  ml,
  celsius,
  minutes,
  resteeps,
});

const STORE_PRESSED = t(
  "Droog bij 60 tot 70 % relatieve vochtigheid, donker, weg van geur. Laat het papier eromheen zitten.",
  "Dry at 60 to 70 % relative humidity, dark, away from odours. Leave the wrapper on.",
);
const STORE_LOOSE_DARK = t(
  "Luchtdicht en donker, weg van koffie en kruiden. Hoeft niet koud.",
  "Airtight and dark, away from coffee and spices. Does not need to be cold.",
);
const STORE_ROASTED = t(
  "Luchtdicht en donker. Na een zware rooster wordt hij beter van een half jaar rust.",
  "Airtight and dark. After a heavy roast it improves with half a year of rest.",
);
const STORE_FRIDGE = t(
  "In de koelkast, luchtdicht, in kleine porties. Dit jaar opdrinken.",
  "In the fridge, airtight, in small portions. Finish it this year.",
);
const STORE_WHITE = t(
  "Luchtdicht en donker. Witte thee mag jaren blijven liggen en wordt dan donkerder en zoeter.",
  "Airtight and dark. White tea may sit for years, and turns darker and sweeter as it does.",
);

export const products: Product[] = [
  // ─── Shu pu-erh (7) ────────────────────────────────────────────────────────
  {
    slug: "shu-gongting-bingdao-gushu",
    name: "Shu Gong Ting Bingdao Gushu",
    hanzi: "宫廷冰岛古树熟普",
    pinyin: "Gōngtíng Bīngdǎo Gǔshù Shúpǔ",
    category: "shou",
    form: "cake",
    liquor: "shou",
    caffeine: "medium",
    notes: ["darkChocolate", "driedDate", "cream", "forestFloor"],
    vat: 6,
    vaultEligible: true,
    featured: true,
    badges: ["limited"],
    pricing: { base: 750, formats: [25, 50, 100], stock: 22, pressed: { grams: 357, price: 8900, kind: "cake", stock: 6 } },
    passport: {
      regionId: "mengku",
      altitudeM: 1700,
      harvestYear: 2019,
      harvestMonth: 4,
      producer: t("Coöperatie Bingdao Laozhai", "Bingdao Laozhai cooperative"),
      cultivar: "Mengku Da Ye",
      oxidation: null,
      fermentation: t("Wo dui van 45 dagen op Bingdao-blad, daarna zes jaar droog gerijpt.", "A 45-day wo dui on Bingdao leaf, then six years of dry ageing."),
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 8, firstSeconds: 10, incrementSeconds: 5, infusions: 12 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Gong ting-graad op Bingdao-blad, zes jaar nagerijpt.", "Palace grade on Bingdao leaf, six years of ageing."),
      description: t(
        "Gong ting slaat op de graad, niet op de herkomst: alleen de kleinste knoppen gaan mee. Dat dit op Bingdao-materiaal gedaan is, is ongewoon — dat blad gaat normaal naar sheng. Het aftreksel is bijna zwart, volstrekt helder, en zonder de kelderlucht die jonge shou vaak heeft.",
        "Gong ting refers to the grade, not the origin: only the smallest buds go in. Doing it on Bingdao material is unusual — that leaf normally goes to sheng. The liquor is nearly black, completely clear, and without the cellar note young shou often has.",
      ),
    },
    reviews: [
      { author: "Wouter D.", city: "Gent", rating: 5, date: "2026-05-12", body: t("Twaalf infusies en de laatste was nog steeds zoet.", "Twelve infusions and the last one was still sweet.") },
      { author: "Els D.", city: "Kortrijk", rating: 5, date: "2026-06-01", body: t("Geen modderige smaak, wat ik van pu-erh gewend was.", "None of the muddy taste I was used to from pu-erh.") },
    ],
    related: ["lao-banzhang-shu-2008", "mengku-gushu-shu-2009", "lao-cha-tou"],
  },
  {
    slug: "lao-banzhang-shu-2008",
    name: "Lao Banzhang Shu 2008",
    hanzi: "老班章熟普",
    pinyin: "Lǎo Bānzhāng Shúpǔ",
    category: "shou",
    form: "cake",
    liquor: "shou",
    caffeine: "medium",
    notes: ["driedDate", "oldWood", "darkChocolate", "camphor"],
    vat: 6,
    vaultEligible: true,
    badges: ["limited"],
    pricing: { base: 890, formats: [25, 50, 100], stock: 14, pressed: { grams: 357, price: 10500, kind: "cake", stock: 4 } },
    passport: {
      regionId: "banzhang",
      altitudeM: 1700,
      harvestYear: 2008,
      harvestMonth: 4,
      producer: t("Werkplaats Chen, Bulang", "Chen workshop, Bulang"),
      cultivar: "Bulang Da Ye",
      oxidation: null,
      fermentation: t("Wo dui van 50 dagen, daarna achttien jaar droog in Kunming.", "A 50-day wo dui, then eighteen years dry in Kunming."),
      roast: "none",
      storage: STORE_PRESSED,
      unknown: t(
        "Banzhang is de meest misbruikte naam in de pu-erh-handel. Wij kochten deze van de maker, niet van een tussenhandelaar, maar een laboratoriumbewijs bestaat niet — dat geldt voor iedereen die deze naam gebruikt.",
        "Banzhang is the most abused name in the pu-erh trade. We bought this from the maker rather than a middleman, but there is no laboratory proof — which is true of everyone using the name.",
      ),
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 10, firstSeconds: 10, incrementSeconds: 5, infusions: 14 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Achttien jaar oud, uit het duurste dorp van Bulang.", "Eighteen years old, from the most expensive village on Bulang."),
      description: t(
        "Achttien jaar heeft de aardse kant er helemaal uitgetrokken; wat overblijft is gedroogde dadel, oud hout en de koele kamfertoon die alleen bij echt oude shou opduikt. Dit is de thee waarmee wij mensen overtuigen die denken dat ze pu-erh niet lusten.",
        "Eighteen years have drawn the earthy side out entirely; what is left is dried date, old wood and the cool camphor note that only turns up in genuinely old shou. This is the tea we use on people who think they dislike pu-erh.",
      ),
    },
    related: ["shu-gongting-bingdao-gushu", "banzhang-6-sterren", "chenxiang-2008"],
  },
  {
    slug: "mengku-gushu-shu-2009",
    name: "Mengku Gushu Shu 2009",
    hanzi: "勐库古树熟普",
    pinyin: "Měngkù Gǔshù Shúpǔ",
    category: "shou",
    form: "cake",
    liquor: "shou",
    caffeine: "medium",
    notes: ["driedDate", "brownSugar", "wetWood", "mushroom"],
    vat: 6,
    vaultEligible: true,
    pricing: { base: 690, formats: [25, 50, 100], stock: 26, pressed: { grams: 357, price: 7900, kind: "cake", stock: 8 } },
    passport: {
      regionId: "mengku",
      altitudeM: 1600,
      harvestYear: 2009,
      harvestMonth: 4,
      producer: t("Coöperatie Mengku", "Mengku cooperative"),
      cultivar: "Mengku Da Ye",
      oxidation: null,
      fermentation: t("Wo dui van 45 dagen, daarna zeventien jaar droog gerijpt.", "A 45-day wo dui, then seventeen years of dry ageing."),
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 8, firstSeconds: 10, incrementSeconds: 5, infusions: 12 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Zeventien jaar, van oude bomen in het Mengku-dal.", "Seventeen years, from old trees in the Mengku valley."),
      description: t(
        "Het middenveld van ons shou-rek, en waarschijnlijk de beste verhouding tussen prijs en jaren die wij hebben. Gedroogde dadel en bruine suiker, met een vochtige-houttoon die net niet naar kelder trekt.",
        "The middle of our shou shelf, and probably the best ratio of price to years we have. Dried date and brown sugar, with a wet-wood note that stops just short of cellar.",
      ),
    },
    related: ["shu-gongting-bingdao-gushu", "bulang-chunyun-2009", "shu-1968"],
  },
  {
    slug: "bulang-chunyun-2009",
    name: "Bulang Chun Yun 2009",
    hanzi: "布朗春韵",
    pinyin: "Bùlǎng Chūnyùn",
    category: "shou",
    form: "cake",
    liquor: "shou",
    caffeine: "medium",
    notes: ["brownSugar", "driedPersimmon", "forestFloor", "malt"],
    vat: 6,
    vaultEligible: true,
    pricing: { base: 590, formats: [25, 50, 100], stock: 30, pressed: { grams: 357, price: 6800, kind: "cake", stock: 11 } },
    passport: {
      regionId: "bulang",
      altitudeM: 1500,
      harvestYear: 2009,
      harvestMonth: 4,
      producer: t("Werkplaats Bulang Shan", "Bulang Shan workshop"),
      cultivar: "Bulang Da Ye",
      oxidation: null,
      fermentation: t("Wo dui van 55 dagen, zware graad, daarna zeventien jaar droog.", "A 55-day wo dui at a heavy level, then seventeen years dry."),
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 10, firstSeconds: 10, incrementSeconds: 5, infusions: 12 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Voorjaarspluk 2009 van de Bulang-bergrug.", "Spring 2009 picking from the Bulang ridge."),
      description: t(
        "Zwaarder gefermenteerd dan de Mengku en daardoor donkerder en ronder. Bruine suiker en gedroogde kaki, met bosgrond eronder. De cake is stevig geperst, dus neem er een priem bij.",
        "More heavily fermented than the Mengku and therefore darker and rounder. Brown sugar and dried persimmon, with forest floor underneath. The cake is pressed firmly, so bring a pick.",
      ),
    },
    related: ["mengku-gushu-shu-2009", "shu-1968", "lao-cha-tou"],
  },
  {
    slug: "shu-1968",
    name: "Shu 1968",
    hanzi: "1968 熟砖",
    pinyin: "Shúzhuān 1968",
    category: "shou",
    form: "brick",
    liquor: "shou",
    caffeine: "medium",
    notes: ["darkChocolate", "malt", "dampEarth", "driedDate"],
    vat: 6,
    pricing: { base: 490, formats: [25, 50, 100, 250], stock: 44, pressed: { grams: 250, price: 3900, kind: "brick", stock: 18 } },
    passport: {
      regionId: "menghai",
      altitudeM: 1300,
      harvestYear: 2019,
      harvestMonth: 5,
      producer: t("Menghai, recept 1968", "Menghai, the 1968 recipe"),
      cultivar: "Menghai Da Ye",
      oxidation: null,
      fermentation: t("Wo dui van 45 dagen naar een recept uit 1968, dat het huis nog steeds volgt.", "A 45-day wo dui to a recipe from 1968 the house still follows."),
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 10, firstSeconds: 10, incrementSeconds: 5, infusions: 10 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Het huisrecept uit 1968, geperst tot een baksteen van 250 g.", "The 1968 house recipe, pressed into a 250 g brick."),
      description: t(
        "Het jaartal is het recept, niet de oogst — dat zetten wij er liever bij dan dat u het zelf moet uitzoeken. Dit is de dagelijkse shou: donker, mout, chocolade, en hij vergeeft het als u hem te lang laat staan. De goedkoopste manier om te leren hoe geperste thee zich gedraagt.",
        "The year is the recipe, not the harvest — we would rather say so than have you work it out. This is the everyday shou: dark, malt, chocolate, and it forgives you for leaving it too long. The cheapest way to learn how pressed tea behaves.",
      ),
    },
    related: ["bulang-chunyun-2009", "shu-tuocha-100", "lao-cha-tou"],
  },
  {
    slug: "lao-cha-tou",
    name: "Lao Cha Tou",
    hanzi: "老茶头",
    pinyin: "Lǎo Chá Tóu",
    category: "shou",
    form: "loose",
    liquor: "shou",
    caffeine: "medium",
    notes: ["caramel", "driedDate", "darkChocolate", "dampEarth"],
    vat: 6,
    pricing: { base: 550, formats: [25, 50, 100], stock: 28 },
    passport: {
      regionId: "menghai",
      altitudeM: 1300,
      harvestYear: 2015,
      harvestMonth: 5,
      producer: t("Menghai, partij 1501", "Menghai, batch 1501"),
      cultivar: "Menghai Da Ye",
      oxidation: null,
      fermentation: t("Klonters die tijdens de wo dui met pectine aan elkaar bakten en apart zijn uitgezocht.", "Nuggets that caked together with pectin during the wo dui and were sorted out separately."),
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 9, celsius: 100, rinseSeconds: 10, firstSeconds: 15, incrementSeconds: 8, infusions: 14 }),
    western: west(5, 300, 100, 5, 4),
    copy: {
      tagline: t("Theekoppen: klonters uit de fermentatiestapel van 2015.", "Tea heads: nuggets from the 2015 fermentation pile."),
      description: t(
        "Tijdens het fermenteren plakken bladeren met pectine aan elkaar tot harde klonters. Die werden vroeger weggegooid; nu kosten ze meer dan de rest van de partij, want ze geven hun aftreksel veel trager af. Reken op veertien infusies. Laat de klonters heel, ze vallen vanzelf open.",
        "During fermentation, leaves stick together with pectin into hard nuggets. They used to be thrown away; now they cost more than the rest of the batch, because they give up their liquor far more slowly. Expect fourteen infusions. Leave the nuggets whole, they open by themselves.",
      ),
    },
    related: ["shu-1968", "mengku-gushu-shu-2009", "liu-bao-premium"],
  },
  {
    slug: "shu-tuocha-100",
    name: "Shu Tuocha",
    hanzi: "熟沱茶",
    pinyin: "Shú Tuóchá",
    category: "shou",
    form: "tuocha",
    liquor: "shou",
    caffeine: "medium",
    notes: ["charcoal", "dampEarth", "driedDate", "tobacco"],
    vat: 6,
    pricing: { base: 250, formats: [25], stock: 40, pressed: { grams: 100, price: 990, kind: "tuocha", stock: 48 } },
    passport: {
      regionId: "xiaguan",
      altitudeM: 1900,
      harvestYear: 2021,
      harvestMonth: 3,
      producer: t("Xiaguan Tea Factory, Dali", "Xiaguan Tea Factory, Dali"),
      cultivar: "Blend uit Lincang en Dali",
      oxidation: null,
      fermentation: t("Wo dui, middelzware graad, daarna strak geperst tot een nest van 100 g.", "Wo dui at a medium level, then pressed tight into a 100 g nest."),
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 7, celsius: 100, rinseSeconds: 10, firstSeconds: 10, incrementSeconds: 5, infusions: 10 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Het klassieke nest van 100 g uit Dali.", "The classic 100 g nest from Dali."),
      description: t(
        "De tuocha die in China in elke kruidenierszaak ligt en daarom vaak onderschat wordt. Xiaguan perst harder dan de fabrieken in Banna, dus u hebt een priem nodig en de eerste infusie komt traag op gang. Daarna staat er een strakke, licht rokerige shou zonder franje.",
        "The tuocha that sits in every grocery shop in China and is therefore often underrated. Xiaguan presses harder than the Banna factories, so you need a pick and the first infusion is slow to start. After that you have a tight, faintly smoky shou with no frills.",
      ),
    },
    related: ["shu-1968", "fu-zhuan-jinhua", "lao-cha-tou"],
  },

  // ─── Sheng pu-erh (5) ──────────────────────────────────────────────────────
  {
    slug: "banzhang-6-sterren",
    name: "Banzhang Zes Sterren",
    hanzi: "班章六星",
    pinyin: "Bānzhāng Liù Xīng",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["caneSugar", "coolMint", "orchid", "bark", "apricot"],
    vat: 6,
    vaultEligible: true,
    featured: true,
    badges: ["limited"],
    pricing: { base: 950, formats: [25, 50, 100], stock: 16, pressed: { grams: 357, price: 11900, kind: "cake", stock: 5 } },
    passport: {
      regionId: "banzhang",
      altitudeM: 1700,
      harvestYear: 2021,
      harvestMonth: 4,
      producer: t("Werkplaats Chen, Bulang", "Chen workshop, Bulang"),
      cultivar: "Bulang Da Ye",
      oxidation: 8,
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 13 }),
    western: west(3, 300, 90, 3, 2),
    copy: {
      tagline: t("Banzhang-materiaal, 1700 m, voorjaar 2021.", "Banzhang material, 1700 m, spring 2021."),
      description: t(
        "De eerste slok is ronduit bitter, en dat hoort. Tien seconden later kantelt hij en blijft er een rietsuikerzoetheid achter die breder is dan de bitterheid ooit was, met een koelte achterin de keel. Wie dat nooit heeft meegemaakt, moet het één keer proberen. Zet hem kort en met minder blad dan u gewend bent.",
        "The first sip is flatly bitter, and it should be. Ten seconds later it turns, leaving a cane-sugar sweetness broader than the bitterness ever was, with a coolness at the back of the throat. If you have never had that happen, try it once. Steep it short and with less leaf than you are used to.",
      ),
    },
    reviews: [
      { author: "Marieke V.", city: "Leuven", rating: 5, date: "2026-03-02", body: t("De koelte in de keel is echt geen verkooppraat.", "The coolness in the throat really is not sales talk.") },
      { author: "Tom B.", city: "Antwerpen", rating: 4, date: "2026-01-20", body: t("Prachtig, maar je moet er tijd voor nemen. In een mok werkt dit niet.", "Beautiful, but you have to make time for it. This does not work in a mug.") },
    ],
    related: ["gushu-mengsong-2016", "chenxiang-2008", "lao-banzhang-shu-2008"],
  },
  {
    slug: "gushu-mengsong-2016",
    name: "Gu Shu Mengsong 2016",
    hanzi: "勐宋古树",
    pinyin: "Měngsòng Gǔshù",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["honey", "wildFlowers", "pineResin", "caneSugar"],
    vat: 6,
    vaultEligible: true,
    pricing: { base: 850, formats: [25, 50, 100], stock: 19, pressed: { grams: 357, price: 9900, kind: "cake", stock: 7 } },
    passport: {
      regionId: "mengsong",
      altitudeM: 1800,
      harvestYear: 2016,
      harvestMonth: 4,
      producer: t("Familie Yan, Mengsong", "The Yan family, Mengsong"),
      cultivar: "Mengsong Da Ye",
      oxidation: 8,
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 12 }),
    western: west(3, 300, 90, 3, 2),
    copy: {
      tagline: t("1800 m boven Menghai, tien jaar droog gerijpt.", "1800 m above Menghai, ten years of dry ageing."),
      description: t(
        "Hoger dan de meeste tuinen in Banna, en dat proeft u aan de strakheid: minder breed dan Yiwu, met een harsachtige dennentoon die u bij lager gelegen sheng niet tegenkomt. Tien jaar hebben de groene bovenlaag weggenomen zonder dat er al hout voor in de plaats kwam.",
        "Higher than most gardens in Banna, and you taste that in the tightness: less broad than Yiwu, with a resinous pine note you do not meet in sheng from lower down. Ten years have taken away the green top layer without wood yet arriving in its place.",
      ),
    },
    related: ["banzhang-6-sterren", "tao-zi-zhai", "chenxiang-2008"],
  },
  {
    slug: "chenxiang-2008",
    name: "Chen Xiang 2008",
    hanzi: "陈香",
    pinyin: "Chén Xiāng",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["camphor", "oldWood", "driedDate", "honey"],
    vat: 6,
    vaultEligible: true,
    featured: true,
    pricing: { base: 790, formats: [25, 50, 100], stock: 21, pressed: { grams: 357, price: 9500, kind: "cake", stock: 9 } },
    passport: {
      regionId: "yiwu",
      altitudeM: 1350,
      harvestYear: 2008,
      harvestMonth: 4,
      producer: t("Familie Li, Mahei", "The Li family, Mahei"),
      cultivar: "Yiwu Da Ye",
      oxidation: 10,
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 12 }),
    western: west(3, 300, 90, 3, 2),
    copy: {
      tagline: t("Achttien jaar Yiwu, droog gerijpt in Kunming.", "Eighteen years of Yiwu, dry aged in Kunming."),
      description: t(
        "Chen xiang betekent oude geur, en dat is precies wat hier gebeurd is. De jonge scherpte is weg, de kamfer is gekomen, en het blad is roodbruin geworden. Dit is hoe sheng eruitziet als hij het dal voorbij is waar de meeste mensen hem opgeven.",
        "Chen xiang means aged fragrance, and that is exactly what has happened here. The young sharpness is gone, the camphor has arrived, and the leaf has gone red-brown. This is what sheng looks like once it is past the trough where most people give up on it.",
      ),
    },
    related: ["tao-zi-zhai", "gushu-mengsong-2016", "banzhang-6-sterren"],
  },
  {
    slug: "tao-zi-zhai",
    name: "Tao Zi Zhai",
    hanzi: "桃子寨",
    pinyin: "Táozi Zhài",
    category: "sheng",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: ["peach", "honey", "magnolia", "caneSugar"],
    vat: 6,
    vaultEligible: true,
    pricing: { base: 650, formats: [25, 50, 100], stock: 27, pressed: { grams: 357, price: 7800, kind: "cake", stock: 12 } },
    passport: {
      regionId: "yiwu",
      altitudeM: 1400,
      harvestYear: 2019,
      harvestMonth: 4,
      producer: t("Dorp Taozi Zhai, Yiwu", "Taozi Zhai village, Yiwu"),
      cultivar: "Yiwu Da Ye",
      oxidation: 9,
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 11 }),
    western: west(3, 300, 90, 3, 2),
    copy: {
      tagline: t("Perzikdorp in Yiwu, oogst 2019.", "Peach village in Yiwu, 2019 harvest."),
      description: t(
        "Als iemand vraagt waar hij moet beginnen met sheng, is dit het antwoord. Yiwu heeft geen scherpe randen: honing, magnolia en werkelijk iets van perzik, waar het dorp zijn naam aan dankt. Een cake om te drinken én weg te leggen, wat zelden samengaat.",
        "When someone asks where to start with sheng, this is the answer. Yiwu has no sharp edges: honey, magnolia and genuinely something of peach, which is where the village gets its name. A cake to drink and to put away, which rarely goes together.",
      ),
    },
    related: ["chenxiang-2008", "qing-xiang-2023", "gushu-mengsong-2016"],
  },
  {
    slug: "qing-xiang-2023",
    name: "Qing Xiang 2023",
    hanzi: "清香",
    pinyin: "Qīng Xiāng",
    category: "sheng",
    form: "loose",
    liquor: "sheng",
    caffeine: "high",
    notes: ["greenApple", "hay", "caneSugar", "bamboo"],
    vat: 6,
    badges: ["new"],
    pricing: { base: 450, formats: [25, 50, 100], stock: 46 },
    passport: {
      regionId: "jingmai",
      altitudeM: 1400,
      harvestYear: 2023,
      harvestMonth: 4,
      producer: t("Bergdorp Nuogang, Jingmai", "Nuogang mountain village, Jingmai"),
      cultivar: "Jingmai Da Ye",
      oxidation: 8,
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 6, celsius: 92, rinseSeconds: 5, firstSeconds: 8, incrementSeconds: 4, infusions: 9 }),
    western: west(3, 300, 88, 2, 2),
    copy: {
      tagline: t("Jonge sheng van Jingmai, los blad, oogst 2023.", "Young sheng from Jingmai, loose leaf, 2023 harvest."),
      description: t(
        "Zo smaakt sheng vóór de jaren eraan komen: groene appel, hooi, een bamboetoon en een bitterheid die er eerlijk bij hoort. Los blad, dus niets om weg te leggen. Dit is de goedkoopste manier om te begrijpen waar alle andere cakes in dit rek vandaan komen.",
        "This is what sheng tastes like before the years arrive: green apple, hay, a bamboo note and a bitterness that honestly belongs there. Loose leaf, so nothing to put away. The cheapest way to understand where every other cake on this shelf started.",
      ),
    },
    related: ["tao-zi-zhai", "gushu-mengsong-2016", "set-puerh"],
  },

  // ─── Donkere thee / Hei Cha (2) ────────────────────────────────────────────
  {
    slug: "liu-bao-premium",
    name: "Liu Bao Premium",
    hanzi: "六堡茶",
    pinyin: "Liù Bǎo Chá",
    category: "heicha",
    form: "loose",
    liquor: "shou",
    caffeine: "medium",
    notes: ["betelNut", "driedPersimmon", "wetWood", "driedDate"],
    vat: 6,
    pricing: { base: 590, formats: [25, 50, 100], stock: 31 },
    passport: {
      regionId: "wuzhou",
      altitudeM: 400,
      harvestYear: 2016,
      harvestMonth: 5,
      producer: t("Werkplaats Liubao, Wuzhou", "Liubao workshop, Wuzhou"),
      cultivar: "Guangxi Qun Ti",
      oxidation: null,
      fermentation: t("Natte stapeling en daarna tien jaar rijping in bamboemanden.", "Wet piling, then ten years of ageing in bamboo baskets."),
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 10, firstSeconds: 10, incrementSeconds: 5, infusions: 12 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Guangxi, tien jaar gerijpt in bamboemanden.", "Guangxi, ten years aged in bamboo baskets."),
      description: t(
        "Hei cha is niet hetzelfde als pu-erh, al lijkt het erop: Liu Bao komt uit Guangxi, rijpt in manden en heeft de betelnoottoon die kenners er meteen uit halen. Ronder en zoeter dan shou, met minder aarde. In Maleisië drinken de tinmijnwerkers dit al een eeuw.",
        "Hei cha is not the same thing as pu-erh, though it looks it: Liu Bao comes from Guangxi, ages in baskets, and has the betel nut note connoisseurs pick out at once. Rounder and sweeter than shou, with less earth. Tin miners in Malaysia have been drinking it for a century.",
      ),
    },
    related: ["fu-zhuan-jinhua", "lao-cha-tou", "shu-1968"],
  },
  {
    slug: "fu-zhuan-jinhua",
    name: "Fu Zhuan Jin Hua",
    hanzi: "茯砖金花",
    pinyin: "Fúzhuān Jīnhuā",
    category: "heicha",
    form: "brick",
    liquor: "shou",
    caffeine: "medium",
    notes: ["mushroom", "driedDate", "toastedGrain", "bark"],
    vat: 6,
    badges: ["new"],
    pricing: { base: 490, formats: [25, 50, 100, 250], stock: 33, pressed: { grams: 250, price: 3600, kind: "brick", stock: 20 } },
    passport: {
      regionId: "anhua",
      altitudeM: 500,
      harvestYear: 2020,
      harvestMonth: 6,
      producer: t("Werkplaats Anhua, Hunan", "Anhua workshop, Hunan"),
      cultivar: "Anhua Qun Ti",
      oxidation: null,
      fermentation: t("Geperst en daarna bewust begroeid met Eurotium cristatum, de gouden bloemen die u in de baksteen ziet zitten.", "Pressed, then deliberately grown with Eurotium cristatum, the golden flowers you can see inside the brick."),
      roast: "none",
      storage: STORE_PRESSED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 10, firstSeconds: 12, incrementSeconds: 6, infusions: 10 }),
    western: west(4, 300, 100, 4, 3),
    copy: {
      tagline: t("Hunan, met zichtbare gouden bloemen in de breuk.", "Hunan, with visible golden flowers in the break."),
      description: t(
        "De gele stipjes in de baksteen zijn geen fout maar het product: Eurotium cristatum, een schimmel die men er bewust op laat groeien en die de thee zoeter en zachter maakt. Paddenstoel, gedroogde dadel en geroosterde granen. Vreemd op papier, opvallend makkelijk in het kopje.",
        "The yellow specks in the brick are not a fault but the point: Eurotium cristatum, a fungus deliberately grown on it that makes the tea sweeter and softer. Mushroom, dried date and toasted grain. Strange on paper, remarkably easy in the cup.",
      ),
    },
    related: ["liu-bao-premium", "shu-tuocha-100", "shu-1968"],
  },

  // ─── Oolong · Rotsthee, Wuyi (3) ──────────────────────────────────────────
  {
    slug: "da-hong-pao",
    name: "Da Hong Pao",
    hanzi: "大红袍",
    pinyin: "Dà Hóng Páo",
    category: "oolong",
    style: "rock",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["charcoal", "bakedApple", "wetStone", "darkChocolate", "orchid"],
    vat: 6,
    featured: true,
    pricing: { base: 750, formats: [25, 50, 100], stock: 29 },
    passport: {
      regionId: "wuyi",
      altitudeM: 650,
      harvestYear: 2025,
      harvestMonth: 5,
      producer: t("Familie Chen, Huiyuan-kloof", "The Chen family, Huiyuan gorge"),
      cultivar: "Qi Dan en Bei Dou, samengesteld door de maker",
      oxidation: 55,
      roast: "heavy",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 9 }),
    western: west(4, 300, 95, 3, 3),
    copy: {
      tagline: t("Zhengyan, binnen het kerngebied: Huiyuan-kloof, 650 m.", "Zhengyan, inside the core area: Huiyuan gorge, 650 m."),
      description: t(
        "Zhengyan betekent dat de struiken binnen het beschermde rotsgebied staan, en dat is het enige wat het woord betekent. Wat u eerst proeft is de houtskoolrooster; vanaf de derde infusie komt daaronder de natte-steentoon vandaan waar het om begonnen is. Geduld dus: de eerste twee zijn nog vooral vuur.",
        "Zhengyan means the bushes stand inside the protected rock area, and that is all the word means. What you taste first is the charcoal roast; from the third infusion the wet-stone note underneath comes through, which is the whole point. So be patient: the first two are still mostly fire.",
      ),
    },
    reviews: [
      { author: "Bram S.", city: "Gent", rating: 5, date: "2026-05-28", body: t("De rooster is stevig maar niet verbrand. Vanaf infusie drie klopt alles.", "The roast is firm but not burnt. From the third infusion everything falls into place.") },
    ],
    related: ["rou-gui", "shui-xian-qing-xiang", "mi-lan-xiang"],
  },
  {
    slug: "rou-gui",
    name: "Rou Gui",
    hanzi: "肉桂",
    pinyin: "Ròuguì",
    category: "oolong",
    style: "rock",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["cinnamon", "peach", "wetStone", "charcoal"],
    vat: 6,
    pricing: { base: 890, formats: [25, 50, 100], stock: 23 },
    passport: {
      regionId: "wuyi",
      altitudeM: 600,
      harvestYear: 2025,
      harvestMonth: 5,
      producer: t("Werkplaats Niulankeng", "Niulankeng workshop"),
      cultivar: "Rou Gui",
      oxidation: 50,
      roast: "medium",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 9 }),
    western: west(4, 300, 95, 3, 3),
    copy: {
      tagline: t("Niulankeng-kloof, middelzware rooster, oogst 2025.", "Niulankeng gorge, medium roast, 2025 harvest."),
      description: t(
        "Rou gui betekent kaneel, en dat is geen toegevoegd aroma maar een eigenschap van de variëteit: het zit in de geur van het droge blad en het komt terug in de afdronk. Middelzwaar geroosterd, dus het fruit staat er nog naast — perzik, vooral in de tweede en derde infusie.",
        "Rou gui means cinnamon, and that is not an added aroma but a property of the varietal: it is in the smell of the dry leaf and it comes back in the finish. Medium roasted, so the fruit still stands beside it — peach, especially in the second and third infusion.",
      ),
    },
    related: ["da-hong-pao", "shui-xian-qing-xiang", "ya-shi-xiang"],
  },
  {
    slug: "shui-xian-qing-xiang",
    name: "Shui Xian Qing Xiang",
    hanzi: "水仙清香",
    pinyin: "Shuǐxiān Qīngxiāng",
    category: "oolong",
    style: "rock",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["narcissus", "oldWood", "caramel", "sandalwood"],
    vat: 6,
    pricing: { base: 590, formats: [25, 50, 100], stock: 36 },
    passport: {
      regionId: "wuyi",
      altitudeM: 550,
      harvestYear: 2025,
      harvestMonth: 5,
      producer: t("Tuin Wuyuanjian", "Wuyuanjian garden"),
      cultivar: "Shui Xian",
      oxidation: 45,
      roast: "light",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 8, celsius: 100, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 8 }),
    western: west(4, 300, 95, 3, 3),
    copy: {
      tagline: t("Licht geroosterde Shui Xian, de zachtste rotsthee van het rek.", "Lightly roasted Shui Xian, the gentlest rock tea on the shelf."),
      description: t(
        "Qing xiang betekent heldere geur en slaat op de lichte rooster. Shui Xian betekent narcis, en die bloemige toon is hier niet weggebrand zoals bij de zware roosters. Als u wilt weten wat de rots doet zónder dat het vuur ervoor staat, begin dan hier.",
        "Qing xiang means clear fragrance and refers to the light roast. Shui Xian means narcissus, and that floral note has not been burnt away here as it is under a heavy roast. If you want to know what the rock does without the fire in front of it, start here.",
      ),
    },
    related: ["da-hong-pao", "rou-gui", "tie-guan-yin-guo-xiang"],
  },

  // ─── Oolong · Lichte oolong, Anxi (2) ─────────────────────────────────────
  {
    slug: "tie-guan-yin-guo-xiang",
    name: "Tie Guan Yin Guo Xiang",
    hanzi: "铁观音果香",
    pinyin: "Tiě Guānyīn Guǒxiāng",
    category: "oolong",
    style: "light",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["orchid", "gardenia", "butter", "bakedApple"],
    vat: 6,
    featured: true,
    pricing: { base: 590, formats: [25, 50, 100], stock: 42 },
    passport: {
      regionId: "anxi",
      altitudeM: 800,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Familie Wang, Xiping", "The Wang family, Xiping"),
      cultivar: "Tie Guan Yin",
      oxidation: 30,
      roast: "light",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 15, incrementSeconds: 8, infusions: 7 }),
    western: west(3, 300, 90, 2, 3),
    copy: {
      tagline: t("Voorjaar 2026, Xiping, met een fruitige rooster.", "Spring 2026, Xiping, with a fruity roast."),
      description: t(
        "Guo xiang is de fruitige stijl: iets verder geoxideerd en iets warmer geroosterd dan de knalgroene Tie Guan Yin die de laatste dertig jaar de norm werd. Orchidee en gardenia zijn er nog, maar er staat gebakken appel naast. Drink hem dit jaar.",
        "Guo xiang is the fruity style: oxidised a little further and roasted a little warmer than the bright green Tie Guan Yin that became the norm over the last thirty years. Orchid and gardenia are still there, with baked apple alongside. Drink it this year.",
      ),
    },
    related: ["jin-xuan-milk", "shui-xian-qing-xiang", "ali-shan-gao-shan"],
  },
  {
    slug: "jin-xuan-milk",
    name: "Jin Xuan",
    hanzi: "金萱",
    pinyin: "Jīn Xuān",
    category: "oolong",
    style: "light",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["cream", "butter", "lilac", "sweetPea"],
    vat: 6,
    pricing: { base: 450, formats: [25, 50, 100, 250], stock: 51 },
    passport: {
      regionId: "anxi",
      altitudeM: 700,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Coöperatie Anxi", "Anxi cooperative"),
      cultivar: "Jin Xuan (TTES nr. 12)",
      oxidation: 25,
      roast: "none",
      storage: STORE_FRIDGE,
      unknown: t(
        "Jin Xuan is een Taiwanese kweekvariëteit die ook in Fujian geplant wordt. Deze komt uit Anxi, niet uit Taiwan; dat zetten wij erbij omdat de naam anders verwarrend is.",
        "Jin Xuan is a Taiwanese cultivar that is also planted in Fujian. This one comes from Anxi, not Taiwan; we say so because the name is otherwise confusing.",
      ),
    },
    gongfu: gf({ grams: 7, celsius: 90, rinseSeconds: 3, firstSeconds: 15, incrementSeconds: 8, infusions: 6 }),
    western: west(3, 300, 88, 2, 3),
    copy: {
      tagline: t("De melkige variëteit, zonder toegevoegd aroma.", "The milky cultivar, with nothing added."),
      description: t(
        "De romige toon van Jin Xuan zit in de variëteit zelf; wat u in supermarkten als melkoolong vindt, is meestal met melkaroma besproeid. Deze niet. Room, boter en sering, en zo licht dat hij ook koud gezet werkt. De goedkoopste ingang tot oolong in dit rek.",
        "The creamy note in Jin Xuan is in the cultivar itself; what you find in supermarkets as milk oolong is usually sprayed with milk flavouring. This is not. Cream, butter and lilac, and light enough to work cold brewed. The cheapest way into oolong on this shelf.",
      ),
    },
    related: ["tie-guan-yin-guo-xiang", "ali-shan-gao-shan", "dong-ding"],
  },

  // ─── Oolong · Dan Cong, Guangdong (2) ─────────────────────────────────────
  {
    slug: "mi-lan-xiang",
    name: "Mi Lan Xiang",
    hanzi: "蜜兰香",
    pinyin: "Mì Lán Xiāng",
    category: "oolong",
    style: "dancong",
    form: "loose",
    liquor: "oolong",
    caffeine: "high",
    notes: ["honey", "orchid", "apricot", "charcoal"],
    vat: 6,
    featured: true,
    pricing: { base: 890, formats: [25, 50, 100], stock: 24 },
    passport: {
      regionId: "fenghuang",
      altitudeM: 900,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Boomgaard Wudong, één boom van 40 jaar", "Wudong grove, a single 40-year-old tree"),
      cultivar: "Mi Lan Xiang",
      oxidation: 40,
      roast: "medium",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 7, celsius: 100, rinseSeconds: 3, firstSeconds: 8, incrementSeconds: 4, infusions: 10 }),
    western: west(3, 300, 95, 2, 3),
    copy: {
      tagline: t("Honing-orchidee uit Wudong, één boom, 900 m.", "Honey orchid from Wudong, a single tree, 900 m."),
      description: t(
        "Dan cong betekent enkele struik: het blad van één boom wordt apart geplukt en apart verwerkt, en daarom verschilt elke partij. Het droge blad ruikt zo uitgesproken naar honing dat mensen denken dat er iets aan toegevoegd is. Zet hem kort — acht seconden is genoeg — want dan cong wordt snel wrang.",
        "Dan cong means single bush: the leaf of one tree is picked and processed on its own, which is why every batch differs. The dry leaf smells so pronouncedly of honey that people assume something was added. Steep it short — eight seconds is enough — because dan cong turns astringent fast.",
      ),
    },
    reviews: [
      { author: "Nele V.", city: "Gent", rating: 5, date: "2026-06-15", body: t("De geur van het lege kopje is bijna het beste deel.", "The scent of the empty cup is almost the best part.") },
    ],
    related: ["ya-shi-xiang", "da-hong-pao", "dong-fang-mei-ren"],
  },
  {
    slug: "ya-shi-xiang",
    name: "Ya Shi Xiang",
    hanzi: "鸭屎香",
    pinyin: "Yā Shǐ Xiāng",
    category: "oolong",
    style: "dancong",
    form: "loose",
    liquor: "oolong",
    caffeine: "high",
    notes: ["gardenia", "driedMandarin", "wetStone", "honey"],
    vat: 6,
    badges: ["limited"],
    pricing: { base: 990, formats: [25, 50, 100], stock: 17 },
    passport: {
      regionId: "fenghuang",
      altitudeM: 1000,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Familie Wen, Pingkeng", "The Wen family, Pingkeng"),
      cultivar: "Ya Shi Xiang",
      oxidation: 40,
      roast: "medium",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 7, celsius: 100, rinseSeconds: 3, firstSeconds: 8, incrementSeconds: 4, infusions: 11 }),
    western: west(3, 300, 95, 2, 3),
    copy: {
      tagline: t("Pingkeng, 1000 m. De naam is een grap van de boer.", "Pingkeng, 1000 m. The name is the farmer's joke."),
      description: t(
        "Ya shi xiang betekent letterlijk eendenpoepgeur. Het verhaal is dat de boer die de struik bezat niet wilde dat iemand er stekken van nam en er daarom de lelijkste naam op plakte die hij kon bedenken. Wat er werkelijk in zit is gardenia, gedroogde mandarijnschil en een stevige minerale onderkant.",
        "Ya shi xiang literally means duck droppings fragrance. The story is that the farmer who owned the bush did not want anyone taking cuttings and gave it the ugliest name he could think of. What is actually in it is gardenia, dried mandarin peel and a firm mineral floor.",
      ),
    },
    related: ["mi-lan-xiang", "rou-gui", "dong-fang-mei-ren"],
  },

  // ─── Oolong · Taiwan (3) ──────────────────────────────────────────────────
  {
    slug: "dong-ding",
    name: "Dong Ding",
    hanzi: "冻顶乌龙",
    pinyin: "Dòngdǐng Wūlóng",
    category: "oolong",
    style: "taiwan",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["caramel", "toastedGrain", "osmanthus", "cream"],
    vat: 6,
    pricing: { base: 790, formats: [25, 50, 100], stock: 28 },
    passport: {
      regionId: "dongding",
      altitudeM: 750,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Familie Lin, Lugu, Nantou", "The Lin family, Lugu, Nantou"),
      cultivar: "Qing Xin",
      oxidation: 35,
      roast: "medium",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 20, incrementSeconds: 10, infusions: 8 }),
    western: west(3, 300, 92, 3, 3),
    copy: {
      tagline: t("Nantou, 750 m, traditioneel geroosterd door de familie Lin.", "Nantou, 750 m, traditionally roasted by the Lin family."),
      description: t(
        "Strak opgerolde balletjes die zich pas in de derde infusie helemaal openen; tot dan groeit het kopje nog. De rooster geeft karamel en geroosterd graan zonder dat het bloemige eronder verdwijnt. Van alle oolongs hier is dit degene die het best werkt voor wie van koffie komt.",
        "Tightly rolled balls that only open fully in the third infusion; until then the cup is still growing. The roast gives caramel and toasted grain without losing the floral underneath. Of all the oolongs here, this is the one that works best for people coming from coffee.",
      ),
    },
    related: ["ali-shan-gao-shan", "gaba-ali-shan", "jin-xuan-milk"],
  },
  {
    slug: "ali-shan-gao-shan",
    name: "Ali Shan Gao Shan",
    hanzi: "阿里山高山茶",
    pinyin: "Ālǐshān Gāoshān Chá",
    category: "oolong",
    style: "taiwan",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["cream", "lilac", "sweetPea", "butter"],
    vat: 6,
    pricing: { base: 950, formats: [25, 50, 100], stock: 20 },
    passport: {
      regionId: "alishan",
      altitudeM: 1450,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Tuin Shizhuo, Chiayi", "Shizhuo garden, Chiayi"),
      cultivar: "Qing Xin",
      oxidation: 20,
      roast: "none",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 20, incrementSeconds: 10, infusions: 7 }),
    western: west(3, 300, 90, 3, 3),
    copy: {
      tagline: t("Chiayi, 1450 m, ongeroosterd, oogst april 2026.", "Chiayi, 1450 m, unroasted, picked April 2026."),
      description: t(
        "Boven de duizend meter zijn de nachten koud en groeit de struik traag, en dat is precies wat deze thee zijn dikte geeft. Ongeroosterd, dus wat u proeft is het blad zelf: room, seringen en een zoetheid die eerder aan verse boter doet denken dan aan suiker. Het aftreksel is bijna doorzichtig groen; dat hoort zo.",
        "Above a thousand metres the nights are cold and the bush grows slowly, and that is exactly what gives this tea its thickness. Unroasted, so what you taste is the leaf itself: cream, lilac and a sweetness closer to fresh butter than to sugar. The liquor is almost transparent green; that is how it should be.",
      ),
    },
    related: ["dong-ding", "gaba-ali-shan", "tie-guan-yin-guo-xiang"],
  },
  {
    slug: "dong-fang-mei-ren",
    name: "Dong Fang Mei Ren",
    hanzi: "东方美人",
    pinyin: "Dōngfāng Měirén",
    category: "oolong",
    style: "taiwan",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["honey", "driedPersimmon", "vanilla", "wildFlowers", "raisin"],
    vat: 6,
    badges: ["limited"],
    pricing: { base: 1190, formats: [25, 50], stock: 13 },
    passport: {
      regionId: "hsinchu",
      altitudeM: 400,
      harvestYear: 2025,
      harvestMonth: 6,
      producer: t("Familie Xu, Beipu", "The Xu family, Beipu"),
      cultivar: "Qing Xin Da Mao",
      oxidation: 70,
      roast: "light",
      storage: STORE_ROASTED,
    },
    gongfu: gf({ grams: 6, celsius: 90, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 8 }),
    western: west(3, 300, 88, 3, 2),
    copy: {
      tagline: t("Zomerpluk, aangeprikt door de bladluis. Beipu, Hsinchu.", "Summer picking, bitten by the leafhopper. Beipu, Hsinchu."),
      description: t(
        "Deze thee bestaat dankzij een insect. De groene bladcicade prikt het blad aan, de struik reageert met stoffen die honing en druif ruiken, en de boer plukt precies dan. Dat betekent ook: geen bestrijdingsmiddelen, anders komt het insect niet. Zeventig procent geoxideerd, dus dit is oolong die tegen rode thee aan schuurt.",
        "This tea exists because of an insect. The green leafhopper bites the leaf, the bush answers with compounds that smell of honey and grape, and the farmer picks exactly then. Which also means: no pesticides, or the insect stays away. Seventy percent oxidised, so this is oolong brushing up against red tea.",
      ),
    },
    related: ["mi-lan-xiang", "ya-shi-xiang", "jin-jun-mei"],
  },

  // ─── GABA (2) ─────────────────────────────────────────────────────────────
  {
    slug: "gaba-ali-shan",
    name: "GABA Ali Shan",
    hanzi: "佳葉龍茶",
    pinyin: "Jiāyèlóng Chá",
    category: "gaba",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["driedPersimmon", "caramel", "bakedApple", "cream"],
    vat: 6,
    badges: ["new"],
    pricing: { base: 850, formats: [25, 50, 100], stock: 25 },
    passport: {
      regionId: "alishan",
      altitudeM: 1300,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: t("Tuin Shizhuo, Chiayi", "Shizhuo garden, Chiayi"),
      cultivar: "Qing Xin",
      oxidation: 30,
      roast: "light",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 20, incrementSeconds: 10, infusions: 8 }),
    western: west(3, 300, 92, 3, 3),
    copy: {
      tagline: t("Ali Shan-blad, acht uur onder stikstof verwerkt.", "Ali Shan leaf, processed for eight hours under nitrogen."),
      description: t(
        "GABA is geen soort maar een verwerkingsmethode: het blad gaat na de pluk in een afgesloten vat waar de zuurstof door stikstof vervangen is. In die omstandigheden zet de plant glutaminezuur om in gamma-aminoboterzuur. Wat het met de smaak doet is duidelijk: gedroogde kaki en karamel, veel ronder dan dezelfde tuin zonder die stap.",
        "GABA is not a type but a processing method: after picking, the leaf goes into a sealed vessel where the oxygen is replaced by nitrogen. Under those conditions the plant converts glutamic acid into gamma-aminobutyric acid. What it does to the taste is plain: dried persimmon and caramel, far rounder than the same garden without that step.",
      ),
    },
    related: ["gaba-marine", "ali-shan-gao-shan", "dong-ding"],
  },
  {
    slug: "gaba-marine",
    name: "GABA Marine",
    hanzi: "佳葉龍茶",
    pinyin: "Jiāyèlóng Chá",
    category: "gaba",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: ["brine", "driedDate", "toastedGrain", "sesame"],
    vat: 6,
    pricing: { base: 790, formats: [25, 50, 100], stock: 27 },
    passport: {
      regionId: "dongding",
      altitudeM: 700,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: t("Familie Lin, Lugu, Nantou", "The Lin family, Lugu, Nantou"),
      cultivar: "Qing Xin",
      oxidation: 45,
      roast: "medium",
      storage: STORE_LOOSE_DARK,
      unknown: t(
        "Marine is een handelsnaam, geen plaats: hij beschrijft de zilte toon die deze partij heeft. Wij verzinnen er geen Chinese naam bij.",
        "Marine is a trade name, not a place: it describes the saline note this batch has. We are not inventing a Chinese name for it.",
      ),
    },
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 3, firstSeconds: 20, incrementSeconds: 10, infusions: 8 }),
    western: west(3, 300, 92, 3, 3),
    copy: {
      tagline: t("Zwaarder geoxideerd en geroosterd dan de Ali Shan.", "More oxidised and more roasted than the Ali Shan."),
      description: t(
        "Dezelfde stikstofmethode, maar op verder geoxideerd en geroosterd blad, en dat schuift de smaak helemaal weg van fruit. Wat overblijft is zilt, gedroogde dadel, geroosterd graan en sesam. Ongewoon, en de meest gedronken thee achter onze eigen toonbank in de winter.",
        "The same nitrogen method, but on leaf that is oxidised and roasted further, and that shifts the taste right away from fruit. What is left is saline, dried date, toasted grain and sesame. Unusual, and the most-drunk tea behind our own counter in winter.",
      ),
    },
    related: ["gaba-ali-shan", "dong-ding", "liu-bao-premium"],
  },

  // ─── Zwarte thee / Hong Cha (5) ───────────────────────────────────────────
  {
    slug: "dian-hong-gao-shan",
    name: "Dian Hong Gao Shan",
    hanzi: "滇红高山",
    pinyin: "Diānhóng Gāoshān",
    category: "black",
    form: "loose",
    liquor: "red",
    caffeine: "high",
    notes: ["malt", "caramel", "longan", "darkChocolate"],
    vat: 6,
    pricing: { base: 490, formats: [25, 50, 100, 250], stock: 58 },
    passport: {
      regionId: "lincang",
      altitudeM: 1600,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Coöperatie Fengqing", "Fengqing cooperative"),
      cultivar: "Yunnan Da Ye",
      oxidation: 90,
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 5, celsius: 90, rinseSeconds: null, firstSeconds: 8, incrementSeconds: 4, infusions: 8 }),
    western: west(3, 300, 90, 3, 2),
    copy: {
      tagline: t("Fengqing, 1600 m, gouden knop, oogst 2026.", "Fengqing, 1600 m, golden bud, 2026 harvest."),
      description: t(
        "Van dezelfde bomen die sheng leveren, maar volledig geoxideerd. Dat geeft een dikke, moutige thee met karamel en longan, zonder de looierigheid van Indiase thee. Hij verdraagt melk, al zou het zonde zijn. Van alles hier is dit de makkelijkste ochtendthee.",
        "From the same trees that give sheng, but fully oxidised. That yields a thick, malty tea with caramel and longan, without the tannic grip of Indian tea. It takes milk, though it would be a waste. Of everything here, this is the easiest morning cup.",
      ),
    },
    related: ["gushu-hong-cha", "zheng-shan-xiao-zhong", "jin-jun-mei"],
  },
  {
    slug: "jin-jun-mei",
    name: "Jin Jun Mei",
    hanzi: "金骏眉",
    pinyin: "Jīn Jùn Méi",
    category: "black",
    form: "loose",
    liquor: "red",
    caffeine: "high",
    notes: ["honey", "longan", "darkChocolate", "rose"],
    vat: 6,
    badges: ["limited"],
    pricing: { base: 1190, formats: [25, 50], stock: 12 },
    passport: {
      regionId: "tongmu",
      altitudeM: 1200,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Familie Jiang, natuurreservaat Tongmu", "The Jiang family, Tongmu nature reserve"),
      cultivar: "Wuyi Cai Cha",
      oxidation: 85,
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 5, celsius: 90, rinseSeconds: null, firstSeconds: 6, incrementSeconds: 3, infusions: 9 }),
    western: west(3, 300, 88, 2, 3),
    copy: {
      tagline: t("Alleen knoppen, uit het reservaat zelf, 1200 m.", "Buds only, from inside the reserve, 1200 m."),
      description: t(
        "Jin Jun Mei bestaat pas sinds 2005 en werd meteen de duurste rode thee van China, wat betekent dat het overgrote deel van wat onder die naam verkocht wordt het niet is. Deze komt uit Tongmu zelf. Honing, longan en een rozentoon die u bij geen andere rode thee tegenkomt. Kort zetten en niet te heet.",
        "Jin Jun Mei has only existed since 2005 and immediately became the most expensive red tea in China, which means the great majority sold under the name is not it. This comes from Tongmu itself. Honey, longan and a rose note you meet in no other red tea. Steep short and not too hot.",
      ),
    },
    reviews: [
      { author: "Dries L.", city: "Brussel", rating: 5, date: "2026-06-22", body: t("Duur per gram, maar je gebruikt er weinig van en het gaat negen keer mee.", "Expensive per gram, but you use little and it goes nine rounds.") },
    ],
    related: ["zheng-shan-xiao-zhong", "dian-hong-gao-shan", "dong-fang-mei-ren"],
  },
  {
    slug: "zheng-shan-xiao-zhong",
    name: "Zheng Shan Xiao Zhong",
    hanzi: "正山小种",
    pinyin: "Zhèngshān Xiǎozhǒng",
    category: "black",
    form: "loose",
    liquor: "red",
    caffeine: "medium",
    notes: ["longan", "malt", "plum", "cedar"],
    vat: 6,
    pricing: { base: 450, formats: [25, 50, 100, 250], stock: 47 },
    passport: {
      regionId: "tongmu",
      altitudeM: 1000,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Familie Jiang, natuurreservaat Tongmu", "The Jiang family, Tongmu nature reserve"),
      cultivar: "Wuyi Cai Cha",
      oxidation: 90,
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 5, celsius: 95, rinseSeconds: null, firstSeconds: 8, incrementSeconds: 4, infusions: 8 }),
    western: west(3, 300, 92, 3, 2),
    copy: {
      tagline: t("De ongerookte versie, zoals ze in Tongmu zelf gedronken wordt.", "The unsmoked version, as it is drunk in Tongmu itself."),
      description: t(
        "Dit is de thee die in het Westen lapsang souchong heet, maar zonder de dennenrook. Die rook was oorspronkelijk een noodgreep om nat blad te drogen en werd later een exportsmaak; in Tongmu drinkt men de ongerookte versie. Wat overblijft is longan, mout en een lichte cedertoon. Wie de rokerige zoekt, moet dit niet bestellen.",
        "This is the tea the West calls lapsang souchong, minus the pine smoke. That smoke was originally an emergency measure for drying wet leaf and later became an export flavour; in Tongmu people drink the unsmoked version. What remains is longan, malt and a light cedar note. If you want the smoky one, do not order this.",
      ),
    },
    related: ["jin-jun-mei", "dian-hong-gao-shan", "ye-sheng-hong"],
  },
  {
    slug: "gushu-hong-cha",
    name: "Gu Shu Hong Cha",
    hanzi: "古树红茶",
    pinyin: "Gǔshù Hóngchá",
    category: "black",
    form: "loose",
    liquor: "red",
    caffeine: "high",
    notes: ["honey", "bakedApple", "malt", "sandalwood"],
    vat: 6,
    featured: true,
    pricing: { base: 690, formats: [25, 50, 100], stock: 34 },
    passport: {
      regionId: "lincang",
      altitudeM: 1750,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Coöperatie Bingdao Laozhai", "Bingdao Laozhai cooperative"),
      cultivar: "Mengku Da Ye, bomen van 150 jaar en ouder",
      oxidation: 88,
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 5, celsius: 92, rinseSeconds: null, firstSeconds: 8, incrementSeconds: 4, infusions: 10 }),
    western: west(3, 300, 90, 3, 3),
    copy: {
      tagline: t("Rode thee van oude bomen, 1750 m, Lincang.", "Red tea from old trees, 1750 m, Lincang."),
      description: t(
        "Hetzelfde blad dat anders naar sheng zou gaan, hier volledig geoxideerd. Oude bomen brengen meer oplosbare stof mee, en dat merkt u aan de dikte: tien infusies waar een gewone Dian Hong er acht haalt. Honing en gebakken appel, met sandelhout onderin.",
        "The same leaf that would otherwise go to sheng, fully oxidised here. Old trees carry more dissolved matter, and you notice it in the body: ten infusions where an ordinary Dian Hong manages eight. Honey and baked apple, with sandalwood at the bottom.",
      ),
    },
    related: ["dian-hong-gao-shan", "ye-sheng-hong", "jin-jun-mei"],
  },
  {
    slug: "ye-sheng-hong",
    name: "Ye Sheng Hong",
    hanzi: "野生红",
    pinyin: "Yěshēng Hóng",
    category: "black",
    form: "loose",
    liquor: "red",
    caffeine: "medium",
    notes: ["pineResin", "driedPersimmon", "bark", "honey"],
    vat: 6,
    badges: ["limited"],
    pricing: { base: 750, formats: [25, 50], stock: 18 },
    passport: {
      regionId: "puer-city",
      altitudeM: 1900,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Verzamelaars uit Zhen Yuan", "Gatherers from Zhen Yuan"),
      cultivar: "Camellia taliensis, wilde populatie",
      oxidation: 85,
      roast: "none",
      storage: STORE_LOOSE_DARK,
    },
    gongfu: gf({ grams: 5, celsius: 92, rinseSeconds: null, firstSeconds: 10, incrementSeconds: 5, infusions: 9 }),
    western: west(3, 300, 90, 3, 2),
    copy: {
      tagline: t("Van wilde Camellia taliensis, geplukt in het bos op 1900 m.", "From wild Camellia taliensis, gathered in forest at 1900 m."),
      description: t(
        "Strikt genomen is dit geen Camellia sinensis maar taliensis, een verwante soort die in Yunnan in het wild groeit. Dat proeft u: harsachtig, met dennenhars en schors waar gewone rode thee mout heeft. Wij verkopen er twaalf kilo per jaar van, want er is niet meer.",
        "Strictly speaking this is not Camellia sinensis but taliensis, a related species growing wild in Yunnan. You taste it: resinous, with pine resin and bark where ordinary red tea has malt. We sell twelve kilos a year, because there is no more.",
      ),
    },
    related: ["gushu-hong-cha", "zheng-shan-xiao-zhong", "yue-guang-bai"],
  },

  // ─── Witte thee (4) ───────────────────────────────────────────────────────
  {
    slug: "bai-hao-yin-zhen",
    name: "Bai Hao Yin Zhen",
    hanzi: "白毫银针",
    pinyin: "Báiháo Yínzhēn",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "medium",
    notes: ["honeysuckle", "melon", "hay", "honey"],
    vat: 6,
    featured: true,
    pricing: { base: 990, formats: [25, 50, 100], stock: 22 },
    passport: {
      regionId: "fuding",
      altitudeM: 500,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: t("Tuin Panxi, Fuding", "Panxi garden, Fuding"),
      cultivar: "Fuding Da Bai",
      oxidation: 8,
      roast: "none",
      storage: STORE_WHITE,
    },
    gongfu: gf({ grams: 5, celsius: 90, rinseSeconds: null, firstSeconds: 20, incrementSeconds: 10, infusions: 8 }),
    western: west(3, 300, 85, 4, 2),
    copy: {
      tagline: t("Alleen gesloten knoppen, pluk van maart 2026.", "Closed buds only, picked March 2026."),
      description: t(
        "Alleen de gesloten knop met het witte dons eraan, geplukt in een venster van ongeveer tien dagen. Er gebeurt verder niets mee: verwelken in de zon, drogen, klaar. Daardoor smaakt Yin Zhen naar bijna niets en tegelijk naar heel veel — kamperfoelie, meloen, en een zoetheid die pas komt als het kopje bijna koud is. Niet spoelen.",
        "Only the closed bud with its white down, picked in a window of about ten days. Nothing else is done to it: wither in the sun, dry, done. Which is why Yin Zhen tastes of almost nothing and of a great deal at once — honeysuckle, melon, and a sweetness that only arrives when the cup has nearly gone cold. Do not rinse it.",
      ),
    },
    reviews: [
      { author: "Ilse R.", city: "Oostende", rating: 5, date: "2026-05-06", body: t("Zo licht dat ik dacht dat ik het verkeerd deed. Bij de vierde infusie viel het kwartje.", "So light I thought I was doing it wrong. On the fourth infusion the penny dropped.") },
    ],
    related: ["bai-mu-dan-huang-ye-2017", "shou-mei-huang-ye", "yue-guang-bai"],
  },
  {
    slug: "bai-mu-dan-huang-ye-2017",
    name: "Bai Mu Dan Huang Ye 2017",
    hanzi: "白牡丹荒野",
    pinyin: "Bái Mǔdān Huāngyě",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "low",
    notes: ["driedDate", "driedLeaf", "honey", "camphor"],
    vat: 6,
    pricing: { base: 550, formats: [25, 50, 100], stock: 30 },
    passport: {
      regionId: "fuding",
      altitudeM: 600,
      harvestYear: 2017,
      harvestMonth: 4,
      producer: t("Verwilderde tuin bij Diantou, Fuding", "A gone-wild garden near Diantou, Fuding"),
      cultivar: "Fuding Da Bai",
      oxidation: 12,
      roast: "none",
      storage: STORE_WHITE,
    },
    gongfu: gf({ grams: 6, celsius: 100, rinseSeconds: 5, firstSeconds: 12, incrementSeconds: 6, infusions: 10 }),
    western: west(4, 300, 95, 4, 3),
    copy: {
      tagline: t("Verwilderde tuin, negen jaar oud, huang ye-blad.", "A gone-wild garden, nine years old, huang ye leaf."),
      description: t(
        "Huang ye betekent verwilderd: struiken waar jaren niets aan gedaan is en die daardoor trager groeien en dikker blad maken. Negen jaar hebben deze bruin gemaakt, met gedroogde dadel en de kamfertoon die oude witte thee kenmerkt. Verdraagt kokend water, wat verse witte thee niet doet.",
        "Huang ye means gone wild: bushes left alone for years, which grow more slowly and make thicker leaf. Nine years have turned this brown, with dried date and the camphor note that marks aged white tea. It takes boiling water, which fresh white tea will not.",
      ),
    },
    related: ["shou-mei-huang-ye", "bai-hao-yin-zhen", "chenxiang-2008"],
  },
  {
    slug: "shou-mei-huang-ye",
    name: "Shou Mei Huang Ye",
    hanzi: "寿眉荒野",
    pinyin: "Shòuméi Huāngyě",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "low",
    notes: ["hay", "driedPersimmon", "honey", "wetWood"],
    vat: 6,
    pricing: { base: 390, formats: [25, 50, 100, 250], stock: 55 },
    passport: {
      regionId: "fuding",
      altitudeM: 450,
      harvestYear: 2021,
      harvestMonth: 5,
      producer: t("Verwilderde tuin bij Diantou, Fuding", "A gone-wild garden near Diantou, Fuding"),
      cultivar: "Fuding Da Bai",
      oxidation: 14,
      roast: "none",
      storage: STORE_WHITE,
    },
    gongfu: gf({ grams: 6, celsius: 100, rinseSeconds: 5, firstSeconds: 12, incrementSeconds: 6, infusions: 9 }),
    western: west(4, 300, 95, 4, 3),
    copy: {
      tagline: t("Groot blad, vijf jaar oud, de goedkoopste thee in het rek.", "Large leaf, five years old, the cheapest tea on the shelf."),
      description: t(
        "Shou Mei is de grofste graad witte thee: groot blad, weinig knop, en daarom goedkoop. Dat maakt hem niet minder — hij verdraagt kokend water, gaat negen infusies mee en wordt met de jaren alleen maar zoeter. Dit is wat wij zelf in een grote kan zetten als er visite is.",
        "Shou Mei is the coarsest grade of white tea: big leaf, little bud, and therefore cheap. That does not make it lesser — it takes boiling water, goes nine infusions and only gets sweeter with the years. This is what we put in a big pot ourselves when there are guests.",
      ),
    },
    related: ["bai-mu-dan-huang-ye-2017", "bai-hao-yin-zhen", "liu-bao-premium"],
  },
  {
    slug: "yue-guang-bai",
    name: "Yue Guang Bai",
    hanzi: "月光白",
    pinyin: "Yuèguāng Bái",
    category: "white",
    form: "loose",
    liquor: "white",
    caffeine: "medium",
    notes: ["plum", "honey", "vanilla", "driedLeaf"],
    vat: 6,
    pricing: { base: 590, formats: [25, 50, 100], stock: 32 },
    passport: {
      regionId: "puer-city",
      altitudeM: 1600,
      harvestYear: 2025,
      harvestMonth: 3,
      producer: t("Kleine werkplaats bij Jinggu", "Small workshop near Jinggu"),
      cultivar: "Jinggu Da Bai",
      oxidation: 15,
      roast: "none",
      storage: STORE_WHITE,
    },
    gongfu: gf({ grams: 5, celsius: 95, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 8 }),
    western: west(3, 300, 90, 4, 2),
    copy: {
      tagline: t("Yunnanese witte thee, Jinggu, 1600 m.", "Yunnan white tea, Jinggu, 1600 m."),
      description: t(
        "Maanlicht-wit heet zo omdat het blad aan één kant donker is en aan de andere zilverwit. Het is witte thee van de grootbladige Yunnan-variëteit, en dat proeft u: voller en fruitiger dan Fuding, met pruim en een zweem vanille. Het verhaal dat hij ’s nachts gedroogd wordt is folklore, en daar gaan wij niet in mee.",
        "Moonlight white is named for the leaf being dark on one side and silver white on the other. It is white tea from the broad-leaf Yunnan varietal, and you taste that: fuller and fruitier than Fuding, with plum and a hint of vanilla. The story that it is dried at night is folklore, and we do not repeat it.",
      ),
    },
    related: ["bai-hao-yin-zhen", "ye-sheng-hong", "qing-xiang-2023"],
  },

  // ─── Groene thee (4) ──────────────────────────────────────────────────────
  {
    slug: "long-jing",
    name: "Long Jing",
    hanzi: "龙井",
    pinyin: "Lóngjǐng",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["chestnut", "sweetPea", "butter", "toastedGrain"],
    vat: 6,
    featured: true,
    badges: ["limited"],
    pricing: { base: 790, formats: [25, 50, 100], stock: 26 },
    passport: {
      regionId: "xihu",
      altitudeM: 250,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: t("Meijiawu, familie Weng", "Meijiawu, the Weng family"),
      cultivar: "Longjing 43",
      oxidation: 3,
      roast: "light",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 4, celsius: 80, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 5 }),
    western: west(3, 300, 80, 2, 2),
    copy: {
      tagline: t("Vóór Qingming geplukt, Meijiawu, 22 maart 2026.", "Picked before Qingming, Meijiawu, 22 March 2026."),
      description: t(
        "Long Jing van vóór Qingming is duur om één reden: het venster is ongeveer twee weken en het blad groeit in die weken nauwelijks. Meijiawu ligt binnen het kerngebied rond het Westmeer. Kastanje, doperwt en de boterige toon die de pan geeft. Water van tachtig graden, geen honderd, anders is er van al die precisie niets over.",
        "Pre-Qingming Long Jing is expensive for one reason: the window is about two weeks and the leaf barely grows in them. Meijiawu lies inside the West Lake core area. Chestnut, sweet pea and the buttery note the pan gives. Water at eighty degrees, not a hundred, or nothing of all that precision survives.",
      ),
    },
    reviews: [
      { author: "Anke T.", city: "Gent", rating: 5, date: "2026-04-25", body: t("Op 80 graden. Op 90 was hij bitter. Het advies op de pagina klopt echt.", "At 80 degrees. At 90 it was bitter. The advice on the page really is right.") },
    ],
    related: ["bi-luo-chun", "tai-ping-hou-kui", "xin-yang-mao-jian"],
  },
  {
    slug: "bi-luo-chun",
    name: "Bi Luo Chun",
    hanzi: "碧螺春",
    pinyin: "Bìluóchūn",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["apricot", "gardenia", "chestnut", "greenBean"],
    vat: 6,
    pricing: { base: 750, formats: [25, 50, 100], stock: 28 },
    passport: {
      regionId: "dongting",
      altitudeM: 100,
      harvestYear: 2026,
      harvestMonth: 3,
      producer: t("Oostheuvel, Tai-meer", "East hill, Lake Tai"),
      cultivar: "Dongting Qun Ti",
      oxidation: 3,
      roast: "light",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 4, celsius: 78, rinseSeconds: null, firstSeconds: 12, incrementSeconds: 6, infusions: 5 }),
    western: west(3, 300, 78, 2, 2),
    copy: {
      tagline: t("Van de oostheuvel in het Tai-meer, pluk maart 2026.", "From the east hill in Lake Tai, picked March 2026."),
      description: t(
        "Op de twee heuvels in het Tai-meer staan de theestruiken tussen abrikozen- en perzikbomen, en de bloesem valt in dezelfde weken als de pluk. Dat het fruit in de thee terechtkomt klinkt als een verkoopverhaal, maar u ruikt het in de eerste infusie. Het blad is zo dun opgerold dat het meteen zinkt; giet het water langs de wand.",
        "On the two hills in Lake Tai the tea bushes stand among apricot and peach trees, and the blossom falls in the same weeks as the picking. That the fruit ends up in the tea sounds like a sales story, but you smell it in the first infusion. The leaf is rolled so fine that it sinks at once; pour the water down the side.",
      ),
    },
    related: ["long-jing", "tai-ping-hou-kui", "xin-yang-mao-jian"],
  },
  {
    slug: "tai-ping-hou-kui",
    name: "Tai Ping Hou Kui",
    hanzi: "太平猴魁",
    pinyin: "Tàipíng Hóukuí",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["orchid", "sweetPea", "steamedRice", "cucumber"],
    vat: 6,
    badges: ["limited"],
    pricing: { base: 950, formats: [25, 50], stock: 15 },
    passport: {
      regionId: "taiping",
      altitudeM: 700,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Dorp Hou Keng, Tai Ping", "Hou Keng village, Tai Ping"),
      cultivar: "Shi Da Cha",
      oxidation: 3,
      roast: "light",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 4, celsius: 80, rinseSeconds: null, firstSeconds: 25, incrementSeconds: 12, infusions: 4 }),
    western: west(3, 400, 80, 3, 2),
    copy: {
      tagline: t("Bladeren van tien centimeter, plat geperst tussen doeken.", "Ten-centimetre leaves, pressed flat between cloths."),
      description: t(
        "De opvallendste groene thee die er is: hele bladeren van acht tot tien centimeter, met de hand recht gelegd en tussen doeken plat geperst, zodat u het weefsel van de doek in het blad ziet. Zet hem in een hoog glas, niet in een gaiwan — anders passen de bladeren er niet in. Orchidee en doperwt, opvallend zacht.",
        "The most striking green tea there is: whole leaves of eight to ten centimetres, laid straight by hand and pressed flat between cloths, so you can see the weave of the cloth in the leaf. Brew it in a tall glass, not a gaiwan — the leaves will not fit. Orchid and sweet pea, remarkably soft.",
      ),
    },
    related: ["long-jing", "bi-luo-chun", "huang-shan-ya"],
  },
  {
    slug: "xin-yang-mao-jian",
    name: "Xin Yang Mao Jian",
    hanzi: "信阳毛尖",
    pinyin: "Xìnyáng Máojiān",
    category: "green",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["chestnut", "greenBean", "hay", "ginseng"],
    vat: 6,
    pricing: { base: 550, formats: [25, 50, 100, 250], stock: 41 },
    passport: {
      regionId: "xinyang",
      altitudeM: 600,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Coöperatie Che Yun Shan", "Che Yun Shan cooperative"),
      cultivar: "Xinyang Qun Ti",
      oxidation: 3,
      roast: "light",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 4, celsius: 80, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 5 }),
    western: west(3, 300, 80, 2, 2),
    copy: {
      tagline: t("Henan, 600 m, de noordelijkste theestreek van betekenis.", "Henan, 600 m, the northernmost tea region of any consequence."),
      description: t(
        "Zo ver naar het noorden is de winter lang en de oogst laat, en dat maakt het blad dikker en de smaak steviger dan bij Zuid-Chinese groene thee. Veel dons op de knop, waardoor het aftreksel licht troebel is — dat hoort en is geen fout. Kastanje en sperzieboon, met een ginsengachtige bittertoon in de afdronk.",
        "This far north the winter is long and the harvest late, which makes the leaf thicker and the taste firmer than southern Chinese green tea. Heavy down on the bud leaves the liquor slightly cloudy — that belongs and is not a fault. Chestnut and green bean, with a ginseng-like bitterness in the finish.",
      ),
    },
    related: ["long-jing", "bi-luo-chun", "mo-li-hua-cha"],
  },

  // ─── Gele thee (1) ────────────────────────────────────────────────────────
  {
    slug: "huang-shan-ya",
    name: "Huang Shan Ya",
    hanzi: "黄山芽",
    pinyin: "Huángshān Yá",
    category: "yellow",
    form: "loose",
    liquor: "yellow",
    caffeine: "medium",
    notes: ["chestnut", "honey", "hay", "steamedRice"],
    vat: 6,
    badges: ["limited"],
    pricing: { base: 890, formats: [25, 50], stock: 11 },
    passport: {
      regionId: "huangshan",
      altitudeM: 800,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Werkplaats Fuxi, Huangshan", "Fuxi workshop, Huangshan"),
      cultivar: "Huangshan Zhong Ye",
      oxidation: 8,
      roast: "light",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 4, celsius: 85, rinseSeconds: null, firstSeconds: 20, incrementSeconds: 10, infusions: 6 }),
    western: west(3, 300, 85, 3, 2),
    copy: {
      tagline: t("Met de hand geel gemaakt, één partij per jaar.", "Yellowed by hand, one batch a year."),
      description: t(
        "Gele thee is de zeldzaamste van de zes soorten, en dat komt door één extra stap: men huang, het smoren. Het warme blad wordt in papier gewikkeld en blijft daar uren tot dagen liggen, waardoor de grasachtigheid van groene thee verdwijnt en er kastanje en honing voor in de plaats komen. Er zijn nog maar weinig werkplaatsen die het doen.",
        "Yellow tea is the rarest of the six types, because of one extra step: men huang, the smothering. The warm leaf is wrapped in paper and left for hours or days, which takes away the grassiness of green tea and puts chestnut and honey in its place. Few workshops still do it.",
      ),
    },
    related: ["tai-ping-hou-kui", "bai-hao-yin-zhen", "long-jing"],
  },

  // ─── Matcha, Japanse gastcollectie (2) ────────────────────────────────────
  {
    slug: "ceremonial-uji-matcha",
    name: "Ceremoniële Uji",
    hanzi: "宇治抹茶",
    pinyin: "Uji Matcha",
    category: "matcha",
    form: "powder",
    liquor: "matcha",
    caffeine: "high",
    notes: ["seaweed", "cream", "sweetPea", "spinach"],
    vat: 6,
    variants: [{ sku: "WY-MATCHA-UJI-30", grams: 30, price: 2490, stock: 24, label: t("30 g blik", "30 g tin") }],
    passport: {
      regionId: "uji",
      altitudeM: null,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: t("Steenmolen in Uji-Tawara, Kyoto", "Stone mill in Uji-Tawara, Kyoto"),
      cultivar: "Samidori",
      oxidation: 0,
      roast: "none",
      storage: t("In de koelkast, luchtdicht, en na openen binnen zes weken op.", "In the fridge, airtight, and used up within six weeks of opening."),
      unknown: t("Japanse producenten geven de hoogte van de tuin niet op; wij vullen daar niets in.", "Japanese producers do not report garden altitude; we leave that blank rather than guess."),
    },
    gongfu: null,
    western: null,
    copy: {
      tagline: t("Japanse thee, geen Chinese. Uji, Kyoto, eerste pluk 2026.", "Japanese tea, not Chinese. Uji, Kyoto, first picking 2026."),
      description: t(
        "Wij verkopen Chinese thee, en matcha is dat niet. Ze staat hier omdat mensen erom vragen en omdat wij liever goede Japanse thee verkopen dan slechte. Deze komt van een steenmolen in Uji-Tawara: eerste pluk, drie weken onder doek, zo fijn gemalen dat het poeder aan de lepel blijft plakken. Alleen met de chasen kloppen.",
        "We sell Chinese tea, and matcha is not that. It is here because people ask and because we would rather sell good Japanese tea than bad. This comes from a stone mill in Uji-Tawara: first picking, three weeks under shade cloth, ground so fine the powder clings to the spoon. Whisk it with a chasen only.",
      ),
    },
    related: ["daily-matcha-latte", "chasen-bamboe", "chawan-matcha"],
  },
  {
    slug: "daily-matcha-latte",
    name: "Dagelijkse matcha",
    hanzi: "抹茶",
    pinyin: "Matcha",
    category: "matcha",
    form: "powder",
    liquor: "matcha",
    caffeine: "high",
    notes: ["spinach", "malt", "cream", "seaweed"],
    vat: 6,
    variants: [{ sku: "WY-MATCHA-DAY-100", grams: 100, price: 1990, stock: 36, label: t("100 g zak", "100 g pouch") }],
    passport: {
      regionId: "nishio",
      altitudeM: null,
      harvestYear: 2026,
      harvestMonth: 5,
      producer: t("Coöperatie Nishio, Aichi", "Nishio cooperative, Aichi"),
      cultivar: "Yabukita",
      oxidation: 0,
      roast: "none",
      storage: t("In de koelkast, luchtdicht, na openen binnen twee maanden op.", "In the fridge, airtight, used up within two months of opening."),
      unknown: t("Japanse producenten geven de hoogte van de tuin niet op; wij vullen daar niets in.", "Japanese producers do not report garden altitude; we leave that blank rather than guess."),
    },
    gongfu: null,
    western: null,
    copy: {
      tagline: t("Japanse thee, geen Chinese. Aichi, voor melk en elke dag.", "Japanese tea, not Chinese. Aichi, for milk and for every day."),
      description: t(
        "De matcha voor elke dag, en eerlijk gezegd de betere keuze als er melk bij gaat: vlakker en steviger dan de Uji, en daardoor blijft hij overeind in een latte waarin de ceremoniële volledig verdwijnt. Honderd gram, want zo koopt men matcha die men elke ochtend drinkt.",
        "The everyday matcha, and honestly the better choice when milk is involved: flatter and sturdier than the Uji, so it stands up in a latte where the ceremonial one disappears entirely. A hundred grams, because that is how you buy matcha you drink every morning.",
      ),
    },
    related: ["ceremonial-uji-matcha", "chasen-bamboe", "chawan-matcha"],
  },

  // ─── Gearomatiseerd / bloementhee (2) ─────────────────────────────────────
  {
    slug: "mo-li-hua-cha",
    name: "Mo Li Hua Cha Extra",
    hanzi: "茉莉花茶",
    pinyin: "Mòlì Huāchá",
    category: "flavoured",
    form: "loose",
    liquor: "green",
    caffeine: "medium",
    notes: ["jasmine", "sweetPea", "honey", "chestnut"],
    vat: 6,
    pricing: { base: 450, formats: [25, 50, 100, 250], stock: 49 },
    passport: {
      regionId: "fuzhou",
      altitudeM: 300,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Werkplaats Fuzhou, vijf laagjes", "Fuzhou workshop, five layerings"),
      cultivar: "Fuding Da Bai op groene basis",
      oxidation: 5,
      roast: "none",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 5, celsius: 85, rinseSeconds: null, firstSeconds: 12, incrementSeconds: 6, infusions: 6 }),
    western: west(3, 300, 85, 2, 2),
    copy: {
      tagline: t("Vijf keer met verse jasmijn gelaagd, Fuzhou.", "Layered five times with fresh jasmine, Fuzhou."),
      description: t(
        "Er zit geen jasmijn in het zakje, en dat is precies de bedoeling. De bloemen gaan ’s nachts open, worden dan op het blad gelegd, en er de volgende ochtend weer uit gehaald; dat gebeurt hier vijf keer met steeds verse bloemen. Wat u ruikt is dus opgenomen geur, geen toegevoegd aroma en geen gedroogde bloem als decoratie.",
        "There is no jasmine in the packet, and that is the point. The flowers open at night, are laid on the leaf, and are taken out again the next morning; here that happens five times with fresh flowers each round. So what you smell is absorbed scent, not added flavouring and not dried petals as decoration.",
      ),
    },
    related: ["da-yin-zhen-mo-li", "xin-yang-mao-jian", "bi-luo-chun"],
  },
  {
    slug: "da-yin-zhen-mo-li",
    name: "Da Yin Zhen Mo Li",
    hanzi: "大银针茉莉",
    pinyin: "Dà Yínzhēn Mòlì",
    category: "flavoured",
    form: "loose",
    liquor: "white",
    caffeine: "medium",
    notes: ["jasmine", "honeysuckle", "melon", "honey"],
    vat: 6,
    badges: ["new"],
    pricing: { base: 890, formats: [25, 50, 100], stock: 21 },
    passport: {
      regionId: "fuzhou",
      altitudeM: 300,
      harvestYear: 2026,
      harvestMonth: 4,
      producer: t("Werkplaats Fuzhou, negen laagjes", "Fuzhou workshop, nine layerings"),
      cultivar: "Fuding Da Bai, alleen knop",
      oxidation: 8,
      roast: "none",
      storage: STORE_FRIDGE,
    },
    gongfu: gf({ grams: 5, celsius: 85, rinseSeconds: null, firstSeconds: 15, incrementSeconds: 8, infusions: 7 }),
    western: west(3, 300, 85, 3, 2),
    copy: {
      tagline: t("Jasmijnnaalden op witte knop, negen keer gelaagd.", "Jasmine needles on white bud, layered nine times."),
      description: t(
        "Dezelfde methode als de Mo Li Hua Cha, maar op alleen zilveren knop en negen ronden in plaats van vijf. Dat is bijna twee weken werk voor één partij, en u proeft het verschil vooral in de afdronk: de jasmijn blijft, terwijl hij bij de goedkopere versie na twee infusies verdwenen is.",
        "The same method as the Mo Li Hua Cha, but on silver bud only and nine rounds instead of five. That is nearly two weeks of work for one batch, and you taste the difference mostly in the finish: the jasmine stays, where in the cheaper version it is gone after two infusions.",
      ),
    },
    related: ["mo-li-hua-cha", "bai-hao-yin-zhen", "long-jing"],
  },

  // ─── Theeservies (8) ──────────────────────────────────────────────────────
  {
    slug: "gaiwan-porselein-110",
    name: "Gaiwan, porselein",
    hanzi: "盖碗",
    pinyin: "Gàiwǎn",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    featured: true,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-GW-110", grams: 110, price: 1990, stock: 44, label: t("110 ml", "110 ml") }],
    copy: {
      tagline: t("110 ml, dunwandig porselein uit Jingdezhen.", "110 ml, thin-walled porcelain from Jingdezhen."),
      description: t(
        "Als u één ding koopt om gongfu te leren, koop dan dit en geen kannetje. Porselein neemt geen geur op, dus dezelfde gaiwan kan vandaag sheng en morgen witte thee. Honderdtien milliliter is de maat waarop alle parameters op deze site zijn afgestemd. De rand staat naar buiten zodat u hem kunt vasthouden zonder u te branden.",
        "If you buy one thing to learn gongfu, buy this and not a little pot. Porcelain takes on no scent, so the same gaiwan can do sheng today and white tea tomorrow. A hundred and ten millilitres is the size every parameter on this site is calibrated to. The rim flares outward so you can hold it without burning yourself.",
      ),
    },
    related: ["chahai-200", "pialas-set-vier", "set-gongfu-start"],
  },
  {
    slug: "yixing-zhuni-100",
    name: "Yixing, zhuni",
    hanzi: "宜兴朱泥",
    pinyin: "Yíxīng Zhūní",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-YX-100", grams: 100, price: 6900, stock: 8, label: t("100 ml", "100 ml") }],
    copy: {
      tagline: t("100 ml, met de hand gemaakt, ongeglazuurde zhuni-klei.", "100 ml, handmade, unglazed zhuni clay."),
      description: t(
        "Zhuni is de fijnkorrelige rode klei uit Yixing die bij het bakken sterk krimpt; daarom zijn deze kannetjes klein en klinken ze helder als u het deksel erop tikt. Ongeglazuurd, dus de kan neemt smaak op en houdt die vast: één kan, één theesoort. Wij raden hem aan voor yancha of shou, niet voor allebei. Nooit met zeep wassen.",
        "Zhuni is the fine-grained red clay from Yixing that shrinks heavily in the kiln; that is why these pots are small and ring clear when you tap the lid. Unglazed, so the pot takes on flavour and keeps it: one pot, one kind of tea. We recommend it for yancha or for shou, not both. Never wash it with soap.",
      ),
    },
    related: ["gaiwan-porselein-110", "da-hong-pao", "chaban-bamboe"],
  },
  {
    slug: "chahai-200",
    name: "Chahai, glas",
    hanzi: "茶海",
    pinyin: "Cháhǎi",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CH-200", grams: 200, price: 1690, stock: 38, label: t("200 ml", "200 ml") }],
    copy: {
      tagline: t("200 ml, hittebestendig glas, met schenklip.", "200 ml, heat-resistant glass, with a pouring lip."),
      description: t(
        "De billijkheidskan. U giet de gaiwan er in één keer in leeg en schenkt daarna pas de kopjes uit, zodat iedereen dezelfde sterkte krijgt en het blad niet doortrekt. Glas, omdat u dan de kleur van elke infusie ziet veranderen — en dat is precies de informatie die u nodig hebt om te weten wanneer de thee klaar is.",
        "The fairness pitcher. You empty the gaiwan into it in one go and only then pour the cups, so everyone gets the same strength and the leaf stops steeping. Glass, because then you see the colour of each infusion change — exactly the information you need to know when the tea is done.",
      ),
    },
    related: ["gaiwan-porselein-110", "pialas-set-vier", "set-gongfu-start"],
  },
  {
    slug: "pialas-set-vier",
    name: "Pialas, set van vier",
    hanzi: "品茗杯",
    pinyin: "Pǐnmíng Bēi",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CUP-4", grams: 45, price: 1890, stock: 46, label: t("vier stuks, 45 ml", "four pieces, 45 ml") }],
    copy: {
      tagline: t("Vier kopjes van 45 ml, wit geglazuurd van binnen.", "Four 45 ml cups, white glazed inside."),
      description: t(
        "Klein, want bij gongfu drinkt u veel kleine kopjes in plaats van één grote. Wit van binnen is geen esthetische keuze: tegen wit ziet u de kleur van het aftreksel zoals ze is, en die kleur vertelt u meer over de thee dan het etiket. Vaatwasserbestendig, al doen wij het zelf niet.",
        "Small, because in gongfu you drink many small cups instead of one large one. White inside is not an aesthetic choice: against white you see the colour of the liquor as it is, and that colour tells you more about the tea than the label does. Dishwasher safe, though we do not do it ourselves.",
      ),
    },
    related: ["gaiwan-porselein-110", "chahai-200", "set-gongfu-start"],
  },
  {
    slug: "chaban-bamboe",
    name: "Chaban, bamboe",
    hanzi: "茶盘",
    pinyin: "Chápán",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CB-36", grams: 360, price: 3490, stock: 17, label: t("36 × 22 cm", "36 × 22 cm") }],
    copy: {
      tagline: t("36 × 22 cm, bamboe, met uitneembare opvangbak.", "36 × 22 cm, bamboo, with a removable drip tray."),
      description: t(
        "Bij gongfu wordt er gemorst: u spoelt het blad, u warmt de kopjes, u giet over. Het theebord vangt dat op en maakt van morsen een onderdeel van de handeling in plaats van een ongeluk. De bak eronder houdt ongeveer een halve liter, genoeg voor een sessie van twee uur.",
        "In gongfu things get spilled: you rinse the leaf, you warm the cups, you pour over. The tea tray catches it and turns spilling into part of the procedure instead of an accident. The tray underneath holds about half a litre, enough for a two-hour session.",
      ),
    },
    related: ["gaiwan-porselein-110", "yixing-zhuni-100", "chahai-200"],
  },
  {
    slug: "chasen-bamboe",
    name: "Chasen",
    hanzi: "茶筅",
    pinyin: "Chasen",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CS-80", grams: 30, price: 1890, stock: 32, label: t("80 tanden", "80 prongs") }],
    copy: {
      tagline: t("Tachtig tanden, uit één stuk bamboe gesneden.", "Eighty prongs, cut from a single piece of bamboo."),
      description: t(
        "Voor matcha, en alleen voor matcha. Uit één stuk bamboe gesneden, wat u ziet aan de nerf die over de hele lengte doorloopt. Week hem voor gebruik dertig seconden in warm water, dan breken de tanden niet. Laat hem drogen met de tanden naar boven, nooit plat, anders vervormt hij binnen een maand.",
        "For matcha, and only for matcha. Cut from a single piece of bamboo, which you can see in the grain running the whole length. Soak it in warm water for thirty seconds before use and the prongs will not snap. Let it dry prongs up, never flat, or it warps within a month.",
      ),
    },
    related: ["chawan-matcha", "ceremonial-uji-matcha", "daily-matcha-latte"],
  },
  {
    slug: "chawan-matcha",
    name: "Chawan",
    hanzi: "茶碗",
    pinyin: "Chawan",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-CW-400", grams: 400, price: 2990, stock: 19, label: t("400 ml", "400 ml") }],
    copy: {
      tagline: t("400 ml steengoed, met een vlakke bodem voor de chasen.", "400 ml stoneware, with a flat floor for the chasen."),
      description: t(
        "Een matchakom is breed en heeft een vlakke bodem, want u moet er met de chasen in kunnen bewegen zonder de tanden tegen een ronding te duwen. Vierhonderd milliliter lijkt veel voor zeventig milliliter thee, en dat is het ook: de ruimte is er om te kloppen, niet om te vullen.",
        "A matcha bowl is wide with a flat floor, because you need room to move the chasen without pushing the prongs against a curve. Four hundred millilitres looks like a lot for seventy millilitres of tea, and it is: the space is there for whisking, not for filling.",
      ),
    },
    related: ["chasen-bamboe", "ceremonial-uji-matcha", "daily-matcha-latte"],
  },
  {
    slug: "weegschaal-01g",
    name: "Weegschaal, 0,1 g",
    category: "teaware",
    form: "object",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-TW-SC-500", grams: 500, price: 1890, stock: 35, label: t("tot 500 g", "up to 500 g") }],
    copy: {
      tagline: t("Nauwkeurig tot 0,1 g, bereik tot 500 g, met tarra.", "Accurate to 0.1 g, range to 500 g, with tare."),
      description: t(
        "Het verschil tussen zes en acht gram in een gaiwan van 110 ml is het verschil tussen twee verschillende thees. Zolang u op het oog doseert, kunt u niet vergelijken en dus ook niet leren. Dit is het saaiste voorwerp op de site en waarschijnlijk het nuttigste.",
        "The difference between six and eight grams in a 110 ml gaiwan is the difference between two different teas. As long as you dose by eye, you cannot compare and therefore cannot learn. This is the dullest object on the site and probably the most useful.",
      ),
    },
    related: ["gaiwan-porselein-110", "set-kennismaking", "chahai-200"],
  },

  // ─── Sets & cadeaus (5) ───────────────────────────────────────────────────
  {
    slug: "set-kennismaking",
    name: "Kennismaking",
    category: "sets",
    form: "loose",
    liquor: "neutral",
    caffeine: "medium",
    notes: [],
    vat: 6,
    featured: true,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-ST-KM-6", grams: 60, price: 2490, stock: 30, label: t("zes maal 10 g", "six times 10 g") }],
    copy: {
      tagline: t("Zes maal 10 g: shu, sheng, oolong, wit, zwart, groen.", "Six times 10 g: shu, sheng, oolong, white, black, green."),
      description: t(
        "Zes zakjes van tien gram, één uit elke familie, met bij elk een kaartje waarop staat hoeveel gram, hoeveel graden en hoeveel seconden. Tien gram is ongeveer vijf gongfu-sessies, genoeg om te merken of iets bij u past. Bestelt u daarna een volle verpakking, dan trekken wij de prijs van het zakje eraf.",
        "Six ten-gram packets, one from each family, each with a card giving grams, degrees and seconds. Ten grams is about five gongfu sessions, enough to find out whether something suits you. If you order a full packet afterwards, we deduct the price of the sample.",
      ),
    },
    related: ["set-puerh", "set-oolong-reis", "set-gongfu-start"],
  },
  {
    slug: "set-puerh",
    name: "Pu-erh",
    category: "sets",
    form: "cake",
    liquor: "sheng",
    caffeine: "high",
    notes: [],
    vat: 6,
    passport: null,
    gongfu: gf({ grams: 7, celsius: 95, rinseSeconds: 5, firstSeconds: 10, incrementSeconds: 5, infusions: 11 }),
    western: west(3, 300, 90, 3, 2),
    variants: [{ sku: "WY-ST-PE-4", grams: 60, price: 2790, stock: 24, label: t("vier maal 15 g", "four times 15 g") }],
    copy: {
      tagline: t("Vier maal 15 g: twee shu en twee sheng, naast elkaar.", "Four times 15 g: two shu and two sheng, side by side."),
      description: t(
        "Twee rijpe en twee rauwe, uit hetzelfde rek, zodat u het verschil op één middag kunt proeven in plaats van erover te lezen. Wij kiezen er één jonge en één oude van elk, want dat is waar het verschil zit. Met een kaartje per zakje en de volgorde waarin u ze het best zet.",
        "Two ripe and two raw from the same shelf, so you can taste the difference in one afternoon instead of reading about it. We pick one young and one old of each, because that is where the difference lies. With a card per packet and the order to brew them in.",
      ),
    },
    related: ["set-kennismaking", "chenxiang-2008", "shu-1968"],
  },
  {
    slug: "set-oolong-reis",
    name: "Oolong reis",
    category: "sets",
    form: "loose",
    liquor: "oolong",
    caffeine: "medium",
    notes: [],
    vat: 6,
    badges: ["new"],
    passport: null,
    gongfu: gf({ grams: 7, celsius: 98, rinseSeconds: 3, firstSeconds: 12, incrementSeconds: 6, infusions: 9 }),
    western: west(3, 300, 95, 3, 3),
    variants: [{ sku: "WY-ST-OL-4", grams: 60, price: 2990, stock: 26, label: t("vier maal 15 g", "four times 15 g") }],
    copy: {
      tagline: t("Vier maal 15 g, één uit elk van de vier oolong-stijlen.", "Four times 15 g, one from each of the four oolong styles."),
      description: t(
        "Rotsthee uit Wuyi, lichte oolong uit Anxi, dan cong uit Guangdong en een Taiwanese. Vier keer hetzelfde woord op het etiket en vier volstrekt verschillende thees in het kopje — dat is precies waarom wij oolong in vier onderverdelen en de meeste winkels niet.",
        "Rock tea from Wuyi, light oolong from Anxi, dan cong from Guangdong and one from Taiwan. The same word on four labels and four entirely different teas in the cup — which is exactly why we split oolong in four and most shops do not.",
      ),
    },
    related: ["set-kennismaking", "da-hong-pao", "mi-lan-xiang"],
  },
  {
    slug: "set-gongfu-start",
    name: "Gongfu start",
    category: "sets",
    form: "object",
    liquor: "neutral",
    caffeine: "medium",
    notes: [],
    vat: 21,
    featured: true,
    passport: null,
    gongfu: null,
    western: null,
    variants: [{ sku: "WY-ST-GF-1", grams: 1, price: 6900, stock: 14, label: t("volledige set", "complete set") }],
    copy: {
      tagline: t("Gaiwan, chahai, twee pialas en drie thee’s.", "Gaiwan, pitcher, two cups and three teas."),
      description: t(
        "Alles wat u nodig hebt om vanavond te beginnen, en niets meer: de gaiwan van 110 ml waarop elke parameter op deze site is afgestemd, de glazen chahai, twee kopjes en drie zakjes van 15 g uit verschillende families. Los gekocht kost dit ruim tachtig euro. Er zit een kaart bij met de vier stappen.",
        "Everything you need to start tonight and nothing more: the 110 ml gaiwan every parameter on this site is calibrated to, the glass pitcher, two cups and three 15 g packets from different families. Bought separately this comes to well over eighty euro. A card with the four steps is included.",
      ),
    },
    related: ["gaiwan-porselein-110", "set-kennismaking", "chahai-200"],
  },
  {
    slug: "cadeaubon",
    name: "Cadeaubon",
    category: "sets",
    form: "voucher",
    liquor: "neutral",
    caffeine: "none",
    notes: [],
    vat: 21,
    passport: null,
    gongfu: null,
    western: null,
    variants: [
      { sku: "WY-GC-25", grams: 25, price: 2500, stock: 999, label: t("€ 25", "€ 25") },
      { sku: "WY-GC-50", grams: 50, price: 5000, stock: 999, label: t("€ 50", "€ 50") },
      { sku: "WY-GC-100", grams: 100, price: 10000, stock: 999, label: t("€ 100", "€ 100") },
    ],
    copy: {
      tagline: t("Per e-mail of op karton, twee jaar geldig.", "By email or on card, valid for two years."),
      description: t(
        "Een bon is de eerlijke oplossing wanneer u weet dat iemand thee drinkt maar niet welke. Hij komt als code per e-mail, of gedrukt op karton als u dat bij het afrekenen aangeeft. Twee jaar geldig, in één keer of in delen te gebruiken, en ook geldig voor een proeverij of voor bewaring in de Vault.",
        "A voucher is the honest solution when you know someone drinks tea but not which one. It arrives as a code by email, or printed on card if you say so at checkout. Valid for two years, usable in one go or in parts, and also valid for a tasting or for storage in the Vault.",
      ),
    },
    related: ["set-kennismaking", "set-gongfu-start", "set-puerh"],
  },
];
