import type { Flavour, Region } from "./types";

/**
 * Where the tea comes from. Six of these are dots on the home page map:
 * Menghai, Yiwu, Lincang, Wuyi, Fuding, Anxi.
 */
export const regions: Region[] = [
  {
    id: "lincang",
    name: "Lincang",
    hanzi: "临沧",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 22,
    y: 46,
    onMap: true,
    blurb: {
      nl: "Westelijk Yunnan, tegen de Birmese grens. Hoge, koele tuinen; het blad is dik en de bitterheid keert snel om in zoet.",
      en: "Western Yunnan, up against the Burmese border. High, cool gardens; thick leaf, and bitterness that turns to sweet quickly.",
    },
  },
  {
    id: "menghai",
    name: "Menghai",
    hanzi: "勐海",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 44,
    y: 72,
    onMap: true,
    blurb: {
      nl: "Xishuangbanna. Warm en vochtig, en daarom de plek waar shou pu-erh is uitgevonden en nog altijd het best gemaakt wordt.",
      en: "Xishuangbanna. Warm and humid, which is why shou pu-erh was invented here and is still made best here.",
    },
  },
  {
    id: "yiwu",
    name: "Yiwu",
    hanzi: "易武",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 62,
    y: 74,
    onMap: true,
    blurb: {
      nl: "Oude thee-bergen aan de Laotiaanse kant. Zachte, brede sheng zonder scherpe kanten; de klassieke keuze om weg te leggen.",
      en: "Old tea mountains on the Lao side. Soft, broad sheng with no sharp edges; the classic thing to put away.",
    },
  },
  {
    id: "jingmai",
    name: "Jingmai",
    hanzi: "景迈",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 34,
    y: 66,
    onMap: false,
    blurb: {
      nl: "Bos-tuinen waar de theebomen tussen ander bos staan. Bloemig, herkenbaar aan een geur die eerder naar orchidee trekt dan naar blad.",
      en: "Forest gardens where the tea trees stand among other trees. Floral, recognisable by a scent closer to orchid than to leaf.",
    },
  },
  {
    id: "laomane",
    name: "Lao Man'e",
    hanzi: "老曼峨",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 50,
    y: 80,
    onMap: false,
    blurb: {
      nl: "Bulang-dorp bij Menghai, berucht om zijn bittere variëteit. Wie hem kent, drinkt hem om de omslag.",
      en: "A Bulang village near Menghai, notorious for its bitter varietal. People who know it drink it for the turn.",
    },
  },
  {
    id: "xiaguan",
    name: "Xiaguan",
    hanzi: "下关",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 26,
    y: 30,
    onMap: false,
    blurb: {
      nl: "Dali, hoog en droog. De fabriek perst al sinds 1941 tuocha's die strakker en roker zijn dan die uit Banna.",
      en: "Dali, high and dry. The factory has been pressing tuocha since 1941, tighter and smokier than those from Banna.",
    },
  },
  {
    id: "puer-city",
    name: "Pu'er",
    hanzi: "普洱",
    province: { nl: "Yunnan", en: "Yunnan" },
    x: 40,
    y: 54,
    onMap: false,
    blurb: {
      nl: "De stad die de thee haar naam gaf, en tegenwoordig vooral het gebied waar Dian Hong en Yue Guang Bai vandaan komen.",
      en: "The city that gave the tea its name, and these days mostly the area Dian Hong and Yue Guang Bai come from.",
    },
  },
  {
    id: "wuyi",
    name: "Wuyi",
    hanzi: "武夷",
    province: { nl: "Fujian", en: "Fujian" },
    x: 82,
    y: 40,
    onMap: true,
    blurb: {
      nl: "Zandsteenkloven in noordelijk Fujian. Yancha groeit letterlijk tussen de rotsen; die mineraliteit heet yan yun, rotsklank.",
      en: "Sandstone gorges in northern Fujian. Yancha grows literally between the rocks; that minerality is called yan yun, rock rhyme.",
    },
  },
  {
    id: "tongmu",
    name: "Tongmu",
    hanzi: "桐木",
    province: { nl: "Fujian", en: "Fujian" },
    x: 86,
    y: 34,
    onMap: false,
    blurb: {
      nl: "Het beschermde dal binnen Wuyi waar de rode thee is uitgevonden. Jin Jun Mei en de originele lapsang komen hiervandaan.",
      en: "The protected valley inside Wuyi where red tea was invented. Jin Jun Mei and the original lapsang come from here.",
    },
  },
  {
    id: "fuding",
    name: "Fuding",
    hanzi: "福鼎",
    province: { nl: "Fujian", en: "Fujian" },
    x: 92,
    y: 26,
    onMap: true,
    blurb: {
      nl: "Kust van noordoost Fujian. De Da Bai-variëteit met de dikke witte donsknop; alle serieuze witte thee begint hier.",
      en: "The north-east Fujian coast. The Da Bai varietal with its thick white downy bud; all serious white tea starts here.",
    },
  },
  {
    id: "anxi",
    name: "Anxi",
    hanzi: "安溪",
    province: { nl: "Fujian", en: "Fujian" },
    x: 84,
    y: 56,
    onMap: true,
    blurb: {
      nl: "Zuidelijk Fujian, thuis van Tie Guan Yin. Sinds de jaren negentig groener en lichter gerold dan de generatie ervoor.",
      en: "Southern Fujian, home of Tie Guan Yin. Rolled greener and lighter since the nineties than the generation before.",
    },
  },
  {
    id: "fenghuang",
    name: "Fenghuang",
    hanzi: "凤凰",
    province: { nl: "Guangdong", en: "Guangdong" },
    x: 76,
    y: 68,
    onMap: false,
    blurb: {
      nl: "De Phoenix-bergen. Dan Cong betekent enkele struik: elke boom wordt apart geplukt en apart verwerkt.",
      en: "The Phoenix mountains. Dan cong means single bush: every tree is picked and processed on its own.",
    },
  },
  {
    id: "xihu",
    name: "Xi Hu",
    hanzi: "西湖",
    province: { nl: "Zhejiang", en: "Zhejiang" },
    x: 90,
    y: 10,
    onMap: false,
    blurb: {
      nl: "De heuvels rond het Westmeer bij Hangzhou. Het kerngebied van Long Jing is klein en de oogst voor Qingming is er half april voorbij.",
      en: "The hills around West Lake at Hangzhou. The Long Jing core area is small, and the pre-Qingming harvest is over by mid-April.",
    },
  },
  {
    id: "anji",
    name: "Anji",
    hanzi: "安吉",
    province: { nl: "Zhejiang", en: "Zhejiang" },
    x: 86,
    y: 6,
    onMap: false,
    blurb: {
      nl: "Noordelijk Zhejiang. De bleke variëteit maakt maar drie weken per jaar wit blad aan; daarbuiten is het gewone groene thee.",
      en: "Northern Zhejiang. The pale varietal only makes white leaf for three weeks a year; outside that it is ordinary green tea.",
    },
  },
  {
    id: "dongting",
    name: "Dongting",
    hanzi: "洞庭",
    province: { nl: "Jiangsu", en: "Jiangsu" },
    x: 94,
    y: 2,
    onMap: false,
    blurb: {
      nl: "Twee heuvels in het Tai-meer, waar de theestruiken tussen abrikoos en perzik staan. Dat is geen folklore, je proeft het.",
      en: "Two hills in Lake Tai, where the tea bushes stand among apricot and peach. That is not folklore, you can taste it.",
    },
  },
  {
    id: "huangshan",
    name: "Huangshan",
    hanzi: "黄山",
    province: { nl: "Anhui", en: "Anhui" },
    x: 80,
    y: 16,
    onMap: false,
    blurb: {
      nl: "De Gele Bergen. Mist blijft er hangen tot ver in de ochtend, wat de oogst laat en het blad zacht houdt.",
      en: "The Yellow Mountains. Mist hangs there well into the morning, which delays the harvest and keeps the leaf soft.",
    },
  },
  {
    id: "qimen",
    name: "Qimen",
    hanzi: "祁门",
    province: { nl: "Anhui", en: "Anhui" },
    x: 76,
    y: 20,
    onMap: false,
    blurb: {
      nl: "Keemun. De thee die Europa in de negentiende eeuw als zwarte thee leerde kennen, en die daar nog steeds naar smaakt.",
      en: "Keemun. The tea Europe learned to call black tea in the nineteenth century, and which still tastes of that.",
    },
  },
  {
    id: "mengding",
    name: "Meng Ding",
    hanzi: "蒙顶",
    province: { nl: "Sichuan", en: "Sichuan" },
    x: 12,
    y: 18,
    onMap: false,
    blurb: {
      nl: "De oudste bekende theetuin van China, op een mistige bergrug boven Ya'an. Gele thee wordt hier nog met de hand geel gemaakt.",
      en: "The oldest documented tea garden in China, on a misty ridge above Ya'an. Yellow tea is still yellowed by hand here.",
    },
  },
  {
    id: "dongding",
    name: "Dong Ding",
    hanzi: "凍頂",
    province: { nl: "Taiwan", en: "Taiwan" },
    x: 96,
    y: 62,
    onMap: false,
    blurb: {
      nl: "Nantou, midden-Taiwan. De klassieke geroosterde bal-oolong; het roosteren is er een ambacht op zich.",
      en: "Nantou, central Taiwan. The classic roasted ball oolong; there the roasting is a craft of its own.",
    },
  },
  {
    id: "alishan",
    name: "Ali Shan",
    hanzi: "阿里山",
    province: { nl: "Taiwan", en: "Taiwan" },
    x: 96,
    y: 70,
    onMap: false,
    blurb: {
      nl: "Boven de duizend meter in Chiayi. Koude nachten geven een dikke, romige oolong die nauwelijks geroosterd wordt.",
      en: "Above a thousand metres in Chiayi. Cold nights give a thick, creamy oolong that is barely roasted at all.",
    },
  },
  {
    id: "uji",
    name: "Uji",
    hanzi: "宇治",
    province: { nl: "Kyoto, Japan", en: "Kyoto, Japan" },
    x: 4,
    y: 84,
    onMap: false,
    blurb: {
      nl: "Japan, niet China. Uji is het oudste matcha-gebied; de struiken staan drie weken onder doek voor ze geplukt worden.",
      en: "Japan, not China. Uji is the oldest matcha region; the bushes stand under shade cloth for three weeks before picking.",
    },
  },
  {
    id: "nishio",
    name: "Nishio",
    hanzi: "西尾",
    province: { nl: "Aichi, Japan", en: "Aichi, Japan" },
    x: 8,
    y: 90,
    onMap: false,
    blurb: {
      nl: "Japan, niet China. Aichi levert het volume-matcha van het land: vlakker dan Uji, en juist daardoor stabiel in melk.",
      en: "Japan, not China. Aichi supplies the country's volume matcha: flatter than Uji, and stable in milk exactly because of it.",
    },
  },
];

export const regionById = new Map(regions.map((r) => [r.id, r]));

/**
 * The controlled flavour vocabulary. Every tasting note on the site is a key in
 * this list, which is what makes the flavour wheel possible: each key maps to
 * one of six axes, and the wheel plots how many notes land on each axis.
 * Translations live in messages/*.json under `flavour`.
 */
export const flavours: Flavour[] = [
  { key: "orchid", axis: "floral" },
  { key: "osmanthus", axis: "floral" },
  { key: "jasmine", axis: "floral" },
  { key: "magnolia", axis: "floral" },
  { key: "honeysuckle", axis: "floral" },
  { key: "lilac", axis: "floral" },
  { key: "gardenia", axis: "floral" },
  { key: "rose", axis: "floral" },

  { key: "peach", axis: "fruit" },
  { key: "apricot", axis: "fruit" },
  { key: "lychee", axis: "fruit" },
  { key: "longan", axis: "fruit" },
  { key: "citrusPeel", axis: "fruit" },
  { key: "raisin", axis: "fruit" },
  { key: "plum", axis: "fruit" },
  { key: "greenApple", axis: "fruit" },
  { key: "melon", axis: "fruit" },
  { key: "redBerry", axis: "fruit" },
  { key: "driedFig", axis: "fruit" },

  { key: "honey", axis: "sweet" },
  { key: "caneSugar", axis: "sweet" },
  { key: "caramel", axis: "sweet" },
  { key: "brownSugar", axis: "sweet" },
  { key: "malt", axis: "sweet" },
  { key: "vanilla", axis: "sweet" },
  { key: "driedDate", axis: "sweet" },
  { key: "darkChocolate", axis: "sweet" },
  { key: "cream", axis: "sweet" },
  { key: "butter", axis: "sweet" },

  { key: "sweetPea", axis: "green" },
  { key: "steamedGreens", axis: "green" },
  { key: "seaweed", axis: "green" },
  { key: "chestnut", axis: "green" },
  { key: "bamboo", axis: "green" },
  { key: "hay", axis: "green" },
  { key: "cucumber", axis: "green" },
  { key: "spinach", axis: "green" },
  { key: "greenBean", axis: "green" },
  { key: "pineNeedle", axis: "green" },

  { key: "wetStone", axis: "mineral" },
  { key: "flint", axis: "mineral" },
  { key: "limestone", axis: "mineral" },
  { key: "brine", axis: "mineral" },
  { key: "coolMint", axis: "mineral" },
  { key: "camphor", axis: "mineral" },

  { key: "cedar", axis: "wood" },
  { key: "sandalwood", axis: "wood" },
  { key: "oldWood", axis: "wood" },
  { key: "forestFloor", axis: "wood" },
  { key: "dampEarth", axis: "wood" },
  { key: "leather", axis: "wood" },
  { key: "tobacco", axis: "wood" },
  { key: "betelNut", axis: "wood" },
  { key: "driedLeaf", axis: "wood" },
  { key: "cinnamon", axis: "wood" },
  { key: "clove", axis: "wood" },
  { key: "roastedRice", axis: "wood" },
  { key: "charcoal", axis: "wood" },
  { key: "pineSmoke", axis: "wood" },
  { key: "mushroom", axis: "wood" },
];

export const flavourByKey = new Map(flavours.map((f) => [f.key, f]));

export const flavourAxes = ["floral", "fruit", "sweet", "green", "mineral", "wood"] as const;
